/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cbm_constants.h"

namespace cbm {

const cbmConstants g_cbm_constants;

cbmConstants::cbmConstants() {
}

} // namespace

