/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ctrl_constants.h"

namespace ctrl {

const ctrlConstants g_ctrl_constants;

ctrlConstants::ctrlConstants() {
}

} // namespace

