# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\coal_design_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_coal_design_dlg(object):
    def setupUi(self, coal_design_dlg):
        coal_design_dlg.setObjectName(_fromUtf8("coal_design_dlg"))
        coal_design_dlg.resize(443, 330)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        coal_design_dlg.setWindowIcon(icon)
        self.label_6 = QtGui.QLabel(coal_design_dlg)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(coal_design_dlg)
        self.label_7.setGeometry(QtCore.QRect(120, 10, 16, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.thick = QtGui.QLineEdit(coal_design_dlg)
        self.thick.setGeometry(QtCore.QRect(70, 10, 41, 20))
        self.thick.setObjectName(_fromUtf8("thick"))
        self.minable = QtGui.QCheckBox(coal_design_dlg)
        self.minable.setGeometry(QtCore.QRect(360, 10, 71, 21))
        self.minable.setObjectName(_fromUtf8("minable"))
        self.rank = QtGui.QComboBox(coal_design_dlg)
        self.rank.setGeometry(QtCore.QRect(200, 10, 81, 22))
        self.rank.setObjectName(_fromUtf8("rank"))
        self.rank.addItem(_fromUtf8(""))
        self.rank.addItem(_fromUtf8(""))
        self.rank.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(coal_design_dlg)
        self.label_13.setGeometry(QtCore.QRect(170, 10, 31, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_10 = QtGui.QLabel(coal_design_dlg)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(coal_design_dlg)
        self.label_11.setGeometry(QtCore.QRect(170, 50, 31, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.hw = QtGui.QLineEdit(coal_design_dlg)
        self.hw.setGeometry(QtCore.QRect(200, 50, 61, 20))
        self.hw.setObjectName(_fromUtf8("hw"))
        self.label_12 = QtGui.QLabel(coal_design_dlg)
        self.label_12.setGeometry(QtCore.QRect(270, 50, 12, 14))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_8 = QtGui.QLabel(coal_design_dlg)
        self.label_8.setGeometry(QtCore.QRect(340, 50, 21, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.dip_angle = QtGui.QLineEdit(coal_design_dlg)
        self.dip_angle.setGeometry(QtCore.QRect(70, 50, 41, 20))
        self.dip_angle.setObjectName(_fromUtf8("dip_angle"))
        self.label_9 = QtGui.QLabel(coal_design_dlg)
        self.label_9.setGeometry(QtCore.QRect(120, 50, 12, 14))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.f_value = QtGui.QLineEdit(coal_design_dlg)
        self.f_value.setGeometry(QtCore.QRect(370, 50, 61, 20))
        self.f_value.setObjectName(_fromUtf8("f_value"))
        self.label_16 = QtGui.QLabel(coal_design_dlg)
        self.label_16.setGeometry(QtCore.QRect(170, 90, 41, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_14 = QtGui.QLabel(coal_design_dlg)
        self.label_14.setGeometry(QtCore.QRect(330, 90, 41, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gas_penetration = QtGui.QLineEdit(coal_design_dlg)
        self.gas_penetration.setGeometry(QtCore.QRect(370, 90, 61, 20))
        self.gas_penetration.setObjectName(_fromUtf8("gas_penetration"))
        self.gas_content = QtGui.QLineEdit(coal_design_dlg)
        self.gas_content.setGeometry(QtCore.QRect(210, 90, 51, 20))
        self.gas_content.setObjectName(_fromUtf8("gas_content"))
        self.pressure = QtGui.QLineEdit(coal_design_dlg)
        self.pressure.setGeometry(QtCore.QRect(70, 90, 41, 20))
        self.pressure.setObjectName(_fromUtf8("pressure"))
        self.label_17 = QtGui.QLabel(coal_design_dlg)
        self.label_17.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(coal_design_dlg)
        self.label_18.setGeometry(QtCore.QRect(120, 90, 12, 14))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_15 = QtGui.QLabel(coal_design_dlg)
        self.label_15.setGeometry(QtCore.QRect(270, 90, 16, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.res_abundance = QtGui.QComboBox(coal_design_dlg)
        self.res_abundance.setGeometry(QtCore.QRect(100, 130, 121, 22))
        self.res_abundance.setObjectName(_fromUtf8("res_abundance"))
        self.res_abundance.addItem(_fromUtf8(""))
        self.res_abundance.addItem(_fromUtf8(""))
        self.res_abundance.addItem(_fromUtf8(""))
        self.label_34 = QtGui.QLabel(coal_design_dlg)
        self.label_34.setGeometry(QtCore.QRect(260, 130, 71, 21))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_33 = QtGui.QLabel(coal_design_dlg)
        self.label_33.setGeometry(QtCore.QRect(10, 130, 91, 21))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.const_complexity = QtGui.QComboBox(coal_design_dlg)
        self.const_complexity.setGeometry(QtCore.QRect(340, 130, 91, 22))
        self.const_complexity.setObjectName(_fromUtf8("const_complexity"))
        self.const_complexity.addItem(_fromUtf8(""))
        self.const_complexity.addItem(_fromUtf8(""))
        self.const_complexity.addItem(_fromUtf8(""))
        self.const_complexity.addItem(_fromUtf8(""))
        self.caving_zone_height = QtGui.QLineEdit(coal_design_dlg)
        self.caving_zone_height.setGeometry(QtCore.QRect(80, 210, 41, 20))
        self.caving_zone_height.setObjectName(_fromUtf8("caving_zone_height"))
        self.var_coeff = QtGui.QLineEdit(coal_design_dlg)
        self.var_coeff.setGeometry(QtCore.QRect(290, 170, 71, 20))
        self.var_coeff.setObjectName(_fromUtf8("var_coeff"))
        self.mine_index = QtGui.QLineEdit(coal_design_dlg)
        self.mine_index.setGeometry(QtCore.QRect(80, 170, 41, 20))
        self.mine_index.setObjectName(_fromUtf8("mine_index"))
        self.stability_cacl = QtGui.QPushButton(coal_design_dlg)
        self.stability_cacl.setGeometry(QtCore.QRect(370, 210, 61, 23))
        self.stability_cacl.setObjectName(_fromUtf8("stability_cacl"))
        self.stability = QtGui.QComboBox(coal_design_dlg)
        self.stability.setGeometry(QtCore.QRect(280, 210, 81, 22))
        self.stability.setObjectName(_fromUtf8("stability"))
        self.stability.addItem(_fromUtf8(""))
        self.stability.setItemText(0, _fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.var_coeff_cacl = QtGui.QPushButton(coal_design_dlg)
        self.var_coeff_cacl.setGeometry(QtCore.QRect(370, 170, 61, 23))
        self.var_coeff_cacl.setObjectName(_fromUtf8("var_coeff_cacl"))
        self.label_40 = QtGui.QLabel(coal_design_dlg)
        self.label_40.setGeometry(QtCore.QRect(10, 250, 101, 21))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.layer_gap = QtGui.QLineEdit(coal_design_dlg)
        self.layer_gap.setGeometry(QtCore.QRect(110, 250, 51, 20))
        self.layer_gap.setObjectName(_fromUtf8("layer_gap"))
        self.czh_cacl = QtGui.QPushButton(coal_design_dlg)
        self.czh_cacl.setGeometry(QtCore.QRect(140, 210, 61, 23))
        self.czh_cacl.setObjectName(_fromUtf8("czh_cacl"))
        self.label_36 = QtGui.QLabel(coal_design_dlg)
        self.label_36.setGeometry(QtCore.QRect(210, 170, 71, 21))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.influence_factor_cacl = QtGui.QPushButton(coal_design_dlg)
        self.influence_factor_cacl.setGeometry(QtCore.QRect(370, 250, 61, 23))
        self.influence_factor_cacl.setObjectName(_fromUtf8("influence_factor_cacl"))
        self.mine_index_cacl = QtGui.QPushButton(coal_design_dlg)
        self.mine_index_cacl.setGeometry(QtCore.QRect(140, 170, 61, 23))
        self.mine_index_cacl.setObjectName(_fromUtf8("mine_index_cacl"))
        self.label_42 = QtGui.QLabel(coal_design_dlg)
        self.label_42.setGeometry(QtCore.QRect(170, 250, 12, 14))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_38 = QtGui.QLabel(coal_design_dlg)
        self.label_38.setGeometry(QtCore.QRect(210, 210, 61, 21))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_37 = QtGui.QLabel(coal_design_dlg)
        self.label_37.setGeometry(QtCore.QRect(10, 210, 61, 21))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_41 = QtGui.QLabel(coal_design_dlg)
        self.label_41.setGeometry(QtCore.QRect(200, 250, 71, 21))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_35 = QtGui.QLabel(coal_design_dlg)
        self.label_35.setGeometry(QtCore.QRect(10, 170, 61, 21))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_39 = QtGui.QLabel(coal_design_dlg)
        self.label_39.setGeometry(QtCore.QRect(130, 210, 12, 14))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.influence_factor = QtGui.QLineEdit(coal_design_dlg)
        self.influence_factor.setEnabled(True)
        self.influence_factor.setGeometry(QtCore.QRect(280, 250, 81, 20))
        self.influence_factor.setObjectName(_fromUtf8("influence_factor"))
        self.cancel = QtGui.QPushButton(coal_design_dlg)
        self.cancel.setGeometry(QtCore.QRect(230, 280, 101, 41))
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.save = QtGui.QPushButton(coal_design_dlg)
        self.save.setGeometry(QtCore.QRect(70, 280, 101, 41))
        self.save.setObjectName(_fromUtf8("save"))

        self.retranslateUi(coal_design_dlg)
        QtCore.QMetaObject.connectSlotsByName(coal_design_dlg)

    def retranslateUi(self, coal_design_dlg):
        coal_design_dlg.setWindowTitle(_translate("coal_design_dlg", "煤层设计", None))
        self.label_6.setText(_translate("coal_design_dlg", "煤层厚度", None))
        self.label_7.setText(_translate("coal_design_dlg", "<html><head/><body><p>m</p></body></html>", None))
        self.minable.setText(_translate("coal_design_dlg", "可采煤层", None))
        self.rank.setItemText(0, _translate("coal_design_dlg", "烟煤", None))
        self.rank.setItemText(1, _translate("coal_design_dlg", "褐煤", None))
        self.rank.setItemText(2, _translate("coal_design_dlg", "无烟煤", None))
        self.label_13.setText(_translate("coal_design_dlg", "煤阶", None))
        self.label_10.setText(_translate("coal_design_dlg", "煤层倾角", None))
        self.label_11.setText(_translate("coal_design_dlg", "采高", None))
        self.label_12.setText(_translate("coal_design_dlg", "<html><head/><body><p>m</p></body></html>", None))
        self.label_8.setText(_translate("coal_design_dlg", "<html><head/><body><p>f值</p></body></html>", None))
        self.label_9.setText(_translate("coal_design_dlg", "<html><head/><body><p>°</p></body></html>", None))
        self.label_16.setText(_translate("coal_design_dlg", "气含量", None))
        self.label_14.setText(_translate("coal_design_dlg", "<html><head/><body><p>渗透率</p></body></html>", None))
        self.label_17.setText(_translate("coal_design_dlg", "储层压力", None))
        self.label_18.setText(_translate("coal_design_dlg", "<html><head/><body><p>Pa</p></body></html>", None))
        self.label_15.setText(_translate("coal_design_dlg", "<html><head/><body><p>%</p></body></html>", None))
        self.res_abundance.setItemText(0, _translate("coal_design_dlg", "中(0.5~3.0)", None))
        self.res_abundance.setItemText(1, _translate("coal_design_dlg", "高(>3.0)", None))
        self.res_abundance.setItemText(2, _translate("coal_design_dlg", "低(<3.0)", None))
        self.label_34.setText(_translate("coal_design_dlg", "构造复杂程度", None))
        self.label_33.setText(_translate("coal_design_dlg", "煤层气储量丰度", None))
        self.const_complexity.setItemText(0, _translate("coal_design_dlg", "复杂", None))
        self.const_complexity.setItemText(1, _translate("coal_design_dlg", "极复杂", None))
        self.const_complexity.setItemText(2, _translate("coal_design_dlg", "中等", None))
        self.const_complexity.setItemText(3, _translate("coal_design_dlg", "简单", None))
        self.stability_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.stability.setItemText(1, _translate("coal_design_dlg", "稳定煤层", None))
        self.stability.setItemText(2, _translate("coal_design_dlg", "较稳定煤层", None))
        self.stability.setItemText(3, _translate("coal_design_dlg", "不稳定煤层", None))
        self.stability.setItemText(4, _translate("coal_design_dlg", "极不稳定煤层", None))
        self.var_coeff_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.label_40.setText(_translate("coal_design_dlg", "与上覆煤层层间距", None))
        self.czh_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.label_36.setText(_translate("coal_design_dlg", "煤厚变异系数", None))
        self.influence_factor_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.mine_index_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.label_42.setText(_translate("coal_design_dlg", "<html><head/><body><p>m</p></body></html>", None))
        self.label_38.setText(_translate("coal_design_dlg", "煤层稳定性", None))
        self.label_37.setText(_translate("coal_design_dlg", "冒落带高度", None))
        self.label_41.setText(_translate("coal_design_dlg", "采动影响倍数", None))
        self.label_35.setText(_translate("coal_design_dlg", "可采性指数", None))
        self.label_39.setText(_translate("coal_design_dlg", "<html><head/><body><p>m</p></body></html>", None))
        self.cancel.setText(_translate("coal_design_dlg", "取  消", None))
        self.save.setText(_translate("coal_design_dlg", "保  存", None))

import usecad_rc
