# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\coal_design_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_coal_design_dlg(object):
    def setupUi(self, coal_design_dlg):
        coal_design_dlg.setObjectName(_fromUtf8("coal_design_dlg"))
        coal_design_dlg.resize(511, 441)
        font = QtGui.QFont()
        font.setPointSize(12)
        coal_design_dlg.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        coal_design_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(coal_design_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 511, 411))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.label_38 = QtGui.QLabel(self.widget_main)
        self.label_38.setGeometry(QtCore.QRect(240, 220, 81, 31))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.cancel = QtGui.QPushButton(self.widget_main)
        self.cancel.setGeometry(QtCore.QRect(280, 370, 101, 31))
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.dip_angle = QtGui.QLineEdit(self.widget_main)
        self.dip_angle.setGeometry(QtCore.QRect(80, 70, 61, 31))
        self.dip_angle.setObjectName(_fromUtf8("dip_angle"))
        self.mine_index = QtGui.QLineEdit(self.widget_main)
        self.mine_index.setGeometry(QtCore.QRect(100, 220, 61, 31))
        self.mine_index.setObjectName(_fromUtf8("mine_index"))
        self.complexity = QtGui.QComboBox(self.widget_main)
        self.complexity.setGeometry(QtCore.QRect(410, 170, 91, 31))
        self.complexity.setObjectName(_fromUtf8("complexity"))
        self.complexity.addItem(_fromUtf8(""))
        self.complexity.addItem(_fromUtf8(""))
        self.complexity.addItem(_fromUtf8(""))
        self.complexity.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.widget_main)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 71, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_6 = QtGui.QLabel(self.widget_main)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 71, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.mine_index_cacl = QtGui.QPushButton(self.widget_main)
        self.mine_index_cacl.setGeometry(QtCore.QRect(170, 220, 61, 31))
        self.mine_index_cacl.setObjectName(_fromUtf8("mine_index_cacl"))
        self.minable = QtGui.QCheckBox(self.widget_main)
        self.minable.setGeometry(QtCore.QRect(390, 20, 91, 31))
        self.minable.setObjectName(_fromUtf8("minable"))
        self.label_33 = QtGui.QLabel(self.widget_main)
        self.label_33.setGeometry(QtCore.QRect(10, 170, 121, 31))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.stability_cacl = QtGui.QPushButton(self.widget_main)
        self.stability_cacl.setGeometry(QtCore.QRect(440, 220, 61, 31))
        self.stability_cacl.setObjectName(_fromUtf8("stability_cacl"))
        self.label_9 = QtGui.QLabel(self.widget_main)
        self.label_9.setGeometry(QtCore.QRect(150, 70, 41, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_18 = QtGui.QLabel(self.widget_main)
        self.label_18.setGeometry(QtCore.QRect(150, 120, 41, 31))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_13 = QtGui.QLabel(self.widget_main)
        self.label_13.setGeometry(QtCore.QRect(210, 20, 41, 31))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.f_value = QtGui.QLineEdit(self.widget_main)
        self.f_value.setGeometry(QtCore.QRect(230, 120, 61, 31))
        self.f_value.setObjectName(_fromUtf8("f_value"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(120, 370, 101, 31))
        self.save.setObjectName(_fromUtf8("save"))
        self.czh_cacl = QtGui.QPushButton(self.widget_main)
        self.czh_cacl.setGeometry(QtCore.QRect(200, 270, 61, 31))
        self.czh_cacl.setObjectName(_fromUtf8("czh_cacl"))
        self.label_14 = QtGui.QLabel(self.widget_main)
        self.label_14.setGeometry(QtCore.QRect(340, 120, 61, 31))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_7 = QtGui.QLabel(self.widget_main)
        self.label_7.setGeometry(QtCore.QRect(150, 20, 31, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pressure = QtGui.QLineEdit(self.widget_main)
        self.pressure.setGeometry(QtCore.QRect(80, 120, 61, 31))
        self.pressure.setObjectName(_fromUtf8("pressure"))
        self.gas_penetration = QtGui.QLineEdit(self.widget_main)
        self.gas_penetration.setGeometry(QtCore.QRect(400, 120, 61, 31))
        self.gas_penetration.setObjectName(_fromUtf8("gas_penetration"))
        self.res_abundance = QtGui.QComboBox(self.widget_main)
        self.res_abundance.setGeometry(QtCore.QRect(130, 170, 131, 31))
        self.res_abundance.setObjectName(_fromUtf8("res_abundance"))
        self.res_abundance.addItem(_fromUtf8(""))
        self.res_abundance.addItem(_fromUtf8(""))
        self.res_abundance.addItem(_fromUtf8(""))
        self.rank = QtGui.QComboBox(self.widget_main)
        self.rank.setGeometry(QtCore.QRect(250, 20, 101, 31))
        self.rank.setObjectName(_fromUtf8("rank"))
        self.rank.addItem(_fromUtf8(""))
        self.rank.addItem(_fromUtf8(""))
        self.rank.addItem(_fromUtf8(""))
        self.var_coeff_cacl = QtGui.QPushButton(self.widget_main)
        self.var_coeff_cacl.setGeometry(QtCore.QRect(440, 270, 61, 31))
        self.var_coeff_cacl.setObjectName(_fromUtf8("var_coeff_cacl"))
        self.stability = QtGui.QComboBox(self.widget_main)
        self.stability.setGeometry(QtCore.QRect(320, 220, 111, 31))
        self.stability.setObjectName(_fromUtf8("stability"))
        self.stability.addItem(_fromUtf8(""))
        self.stability.setItemText(0, _fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.label_16 = QtGui.QLabel(self.widget_main)
        self.label_16.setGeometry(QtCore.QRect(340, 70, 61, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.layer_gap = QtGui.QLineEdit(self.widget_main)
        self.layer_gap.setGeometry(QtCore.QRect(150, 320, 61, 31))
        self.layer_gap.setObjectName(_fromUtf8("layer_gap"))
        self.label_17 = QtGui.QLabel(self.widget_main)
        self.label_17.setGeometry(QtCore.QRect(10, 120, 71, 31))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_41 = QtGui.QLabel(self.widget_main)
        self.label_41.setGeometry(QtCore.QRect(260, 320, 111, 31))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_15 = QtGui.QLabel(self.widget_main)
        self.label_15.setGeometry(QtCore.QRect(470, 70, 31, 31))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gas_content = QtGui.QLineEdit(self.widget_main)
        self.gas_content.setGeometry(QtCore.QRect(400, 70, 61, 31))
        self.gas_content.setObjectName(_fromUtf8("gas_content"))
        self.hw = QtGui.QLineEdit(self.widget_main)
        self.hw.setGeometry(QtCore.QRect(230, 70, 61, 31))
        self.hw.setObjectName(_fromUtf8("hw"))
        self.label_39 = QtGui.QLabel(self.widget_main)
        self.label_39.setGeometry(QtCore.QRect(160, 270, 31, 31))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.influence_factor = QtGui.QLineEdit(self.widget_main)
        self.influence_factor.setEnabled(True)
        self.influence_factor.setGeometry(QtCore.QRect(370, 320, 61, 31))
        self.influence_factor.setObjectName(_fromUtf8("influence_factor"))
        self.label_40 = QtGui.QLabel(self.widget_main)
        self.label_40.setGeometry(QtCore.QRect(10, 320, 141, 31))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_37 = QtGui.QLabel(self.widget_main)
        self.label_37.setGeometry(QtCore.QRect(10, 270, 91, 31))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.influence_factor_cacl = QtGui.QPushButton(self.widget_main)
        self.influence_factor_cacl.setGeometry(QtCore.QRect(440, 320, 61, 31))
        self.influence_factor_cacl.setObjectName(_fromUtf8("influence_factor_cacl"))
        self.label_34 = QtGui.QLabel(self.widget_main)
        self.label_34.setGeometry(QtCore.QRect(300, 170, 111, 31))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_36 = QtGui.QLabel(self.widget_main)
        self.label_36.setGeometry(QtCore.QRect(270, 270, 101, 31))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.caving_zone_height = QtGui.QLineEdit(self.widget_main)
        self.caving_zone_height.setGeometry(QtCore.QRect(100, 270, 61, 31))
        self.caving_zone_height.setObjectName(_fromUtf8("caving_zone_height"))
        self.label_11 = QtGui.QLabel(self.widget_main)
        self.label_11.setGeometry(QtCore.QRect(190, 70, 31, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_35 = QtGui.QLabel(self.widget_main)
        self.label_35.setGeometry(QtCore.QRect(10, 220, 91, 31))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.var_coeff = QtGui.QLineEdit(self.widget_main)
        self.var_coeff.setGeometry(QtCore.QRect(370, 270, 61, 31))
        self.var_coeff.setObjectName(_fromUtf8("var_coeff"))
        self.thick = QtGui.QLineEdit(self.widget_main)
        self.thick.setGeometry(QtCore.QRect(80, 20, 61, 31))
        self.thick.setObjectName(_fromUtf8("thick"))
        self.label_42 = QtGui.QLabel(self.widget_main)
        self.label_42.setGeometry(QtCore.QRect(220, 320, 31, 31))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_8 = QtGui.QLabel(self.widget_main)
        self.label_8.setGeometry(QtCore.QRect(190, 120, 21, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_19 = QtGui.QLabel(self.widget_main)
        self.label_19.setGeometry(QtCore.QRect(300, 70, 31, 31))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.widget_title = QtGui.QWidget(coal_design_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 511, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 421, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(470, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(coal_design_dlg)
        QtCore.QMetaObject.connectSlotsByName(coal_design_dlg)

    def retranslateUi(self, coal_design_dlg):
        coal_design_dlg.setWindowTitle(_translate("coal_design_dlg", "煤层设计", None))
        self.label_38.setText(_translate("coal_design_dlg", "煤层稳定性", None))
        self.cancel.setText(_translate("coal_design_dlg", "取  消", None))
        self.complexity.setItemText(0, _translate("coal_design_dlg", "简单", None))
        self.complexity.setItemText(1, _translate("coal_design_dlg", "中等", None))
        self.complexity.setItemText(2, _translate("coal_design_dlg", "复杂", None))
        self.complexity.setItemText(3, _translate("coal_design_dlg", "极复杂", None))
        self.label_10.setText(_translate("coal_design_dlg", "煤层倾角", None))
        self.label_6.setText(_translate("coal_design_dlg", "煤层厚度", None))
        self.mine_index_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.minable.setText(_translate("coal_design_dlg", "可采煤层", None))
        self.label_33.setText(_translate("coal_design_dlg", "煤层气储量丰度", None))
        self.stability_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.label_9.setText(_translate("coal_design_dlg", "<html><head/><body><p>(°)</p></body></html>", None))
        self.label_18.setText(_translate("coal_design_dlg", "<html><head/><body><p>(Pa)</p></body></html>", None))
        self.label_13.setText(_translate("coal_design_dlg", "煤阶", None))
        self.save.setText(_translate("coal_design_dlg", "保  存", None))
        self.czh_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.label_14.setText(_translate("coal_design_dlg", "<html><head/><body><p>渗透率</p></body></html>", None))
        self.label_7.setText(_translate("coal_design_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.res_abundance.setItemText(0, _translate("coal_design_dlg", "低(<3.0)", None))
        self.res_abundance.setItemText(1, _translate("coal_design_dlg", "高(>3.0)", None))
        self.res_abundance.setItemText(2, _translate("coal_design_dlg", "中(0.5~3.0)", None))
        self.rank.setItemText(0, _translate("coal_design_dlg", "褐煤", None))
        self.rank.setItemText(1, _translate("coal_design_dlg", "烟煤", None))
        self.rank.setItemText(2, _translate("coal_design_dlg", "无烟煤", None))
        self.var_coeff_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.stability.setItemText(1, _translate("coal_design_dlg", "稳定煤层", None))
        self.stability.setItemText(2, _translate("coal_design_dlg", "较稳定煤层", None))
        self.stability.setItemText(3, _translate("coal_design_dlg", "不稳定煤层", None))
        self.stability.setItemText(4, _translate("coal_design_dlg", "极不稳定煤层", None))
        self.label_16.setText(_translate("coal_design_dlg", "气含量", None))
        self.label_17.setText(_translate("coal_design_dlg", "储层压力", None))
        self.label_41.setText(_translate("coal_design_dlg", "采动影响倍数", None))
        self.label_15.setText(_translate("coal_design_dlg", "<html><head/><body><p>(%)</p></body></html>", None))
        self.label_39.setText(_translate("coal_design_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_40.setText(_translate("coal_design_dlg", "与上覆煤层层间距", None))
        self.label_37.setText(_translate("coal_design_dlg", "冒落带高度", None))
        self.influence_factor_cacl.setText(_translate("coal_design_dlg", "计算", None))
        self.label_34.setText(_translate("coal_design_dlg", "构造复杂程度", None))
        self.label_36.setText(_translate("coal_design_dlg", "煤厚变异系数", None))
        self.label_11.setText(_translate("coal_design_dlg", "采高", None))
        self.label_35.setText(_translate("coal_design_dlg", "可采性指数", None))
        self.label_42.setText(_translate("coal_design_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_8.setText(_translate("coal_design_dlg", "<html><head/><body><p>f值</p></body></html>", None))
        self.label_19.setText(_translate("coal_design_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.lab_Ico.setText(_translate("coal_design_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
