# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\decision_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_decision_dlg(object):
    def setupUi(self, decision_dlg):
        decision_dlg.setObjectName(_fromUtf8("decision_dlg"))
        decision_dlg.resize(591, 659)
        font = QtGui.QFont()
        font.setPointSize(12)
        decision_dlg.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        decision_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(decision_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 591, 621))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.graph = QtGui.QPushButton(self.widget_main)
        self.graph.setGeometry(QtCore.QRect(300, 570, 271, 41))
        self.graph.setObjectName(_fromUtf8("graph"))
        self.decision = QtGui.QPushButton(self.widget_main)
        self.decision.setGeometry(QtCore.QRect(20, 570, 271, 41))
        self.decision.setObjectName(_fromUtf8("decision"))
        self.protect_layer_table = QtGui.QTableWidget(self.widget_main)
        self.protect_layer_table.setGeometry(QtCore.QRect(10, 213, 571, 151))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.protect_layer_table.setFont(font)
        self.protect_layer_table.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.protect_layer_table.setGridStyle(QtCore.Qt.DashLine)
        self.protect_layer_table.setObjectName(_fromUtf8("protect_layer_table"))
        self.protect_layer_table.setColumnCount(4)
        self.protect_layer_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.protect_layer_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.protect_layer_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.protect_layer_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.protect_layer_table.setHorizontalHeaderItem(3, item)
        self.protect_layer_table.horizontalHeader().setVisible(True)
        self.protect_layer_table.verticalHeader().setVisible(False)
        self.protect_layer_table.verticalHeader().setHighlightSections(False)
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(10, 184, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.widget_main)
        self.label_2.setGeometry(QtCore.QRect(10, -2, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.permeability_k_table = QtGui.QTableWidget(self.widget_main)
        self.permeability_k_table.setGeometry(QtCore.QRect(10, 28, 571, 151))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.permeability_k_table.setFont(font)
        self.permeability_k_table.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.permeability_k_table.setGridStyle(QtCore.Qt.DashLine)
        self.permeability_k_table.setObjectName(_fromUtf8("permeability_k_table"))
        self.permeability_k_table.setColumnCount(4)
        self.permeability_k_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.permeability_k_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.permeability_k_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.permeability_k_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.permeability_k_table.setHorizontalHeaderItem(3, item)
        self.permeability_k_table.horizontalHeader().setVisible(True)
        self.permeability_k_table.verticalHeader().setVisible(False)
        self.permeability_k_table.verticalHeader().setHighlightSections(False)
        self.coal_population_table = QtGui.QTableWidget(self.widget_main)
        self.coal_population_table.setGeometry(QtCore.QRect(10, 397, 571, 151))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.coal_population_table.setFont(font)
        self.coal_population_table.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.coal_population_table.setGridStyle(QtCore.Qt.DashLine)
        self.coal_population_table.setObjectName(_fromUtf8("coal_population_table"))
        self.coal_population_table.setColumnCount(5)
        self.coal_population_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.coal_population_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.coal_population_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.coal_population_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.coal_population_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.coal_population_table.setHorizontalHeaderItem(4, item)
        self.coal_population_table.horizontalHeader().setVisible(True)
        self.coal_population_table.verticalHeader().setVisible(False)
        self.coal_population_table.verticalHeader().setHighlightSections(False)
        self.label_3 = QtGui.QLabel(self.widget_main)
        self.label_3.setGeometry(QtCore.QRect(10, 367, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.widget_title = QtGui.QWidget(decision_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 591, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 221, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(550, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(decision_dlg)
        QtCore.QMetaObject.connectSlotsByName(decision_dlg)

    def retranslateUi(self, decision_dlg):
        decision_dlg.setWindowTitle(_translate("decision_dlg", "依据示范矿区智能决策", None))
        self.graph.setText(_translate("decision_dlg", "查 看 煤 层 赋 存 立 体 示 意 图", None))
        self.decision.setText(_translate("decision_dlg", "煤层气抽采技术模式决策", None))
        item = self.protect_layer_table.horizontalHeaderItem(0)
        item.setText(_translate("decision_dlg", "序号", None))
        item = self.protect_layer_table.horizontalHeaderItem(1)
        item.setText(_translate("decision_dlg", "煤层编号", None))
        item = self.protect_layer_table.horizontalHeaderItem(2)
        item.setText(_translate("decision_dlg", "煤层倾角", None))
        item = self.protect_layer_table.horizontalHeaderItem(3)
        item.setText(_translate("decision_dlg", "是否具备保护层开采条件?", None))
        self.label.setText(_translate("decision_dlg", "<html><head/><body><p><img src=\":/images/arrow.png\"/>保护层开采条件</p></body></html>", None))
        self.label_2.setText(_translate("decision_dlg", "<html><head/><body><p><img src=\":/images/arrow.png\"/>煤层渗透率条件</p></body></html>", None))
        item = self.permeability_k_table.horizontalHeaderItem(0)
        item.setText(_translate("decision_dlg", "序号", None))
        item = self.permeability_k_table.horizontalHeaderItem(1)
        item.setText(_translate("decision_dlg", "煤层编号", None))
        item = self.permeability_k_table.horizontalHeaderItem(2)
        item.setText(_translate("decision_dlg", "煤层渗透率", None))
        item = self.permeability_k_table.horizontalHeaderItem(3)
        item.setText(_translate("decision_dlg", "煤层渗透率>5mD?", None))
        item = self.coal_population_table.horizontalHeaderItem(0)
        item.setText(_translate("decision_dlg", "序号", None))
        item = self.coal_population_table.horizontalHeaderItem(1)
        item.setText(_translate("decision_dlg", "煤层编号", None))
        item = self.coal_population_table.horizontalHeaderItem(2)
        item.setText(_translate("decision_dlg", "与上覆煤层间距", None))
        item = self.coal_population_table.horizontalHeaderItem(3)
        item.setText(_translate("decision_dlg", "冒落带高度", None))
        item = self.coal_population_table.horizontalHeaderItem(4)
        item.setText(_translate("decision_dlg", "采动影响倍数", None))
        self.label_3.setText(_translate("decision_dlg", "<html><head/><body><p><img src=\":/images/arrow.png\"/>煤层群条件</p></body></html>", None))
        self.lab_Ico.setText(_translate("decision_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
