# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\gas_design_p2_3_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_gas_design_p2_3_dlg(object):
    def setupUi(self, gas_design_p2_3_dlg):
        gas_design_p2_3_dlg.setObjectName(_fromUtf8("gas_design_p2_3_dlg"))
        gas_design_p2_3_dlg.resize(611, 471)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gas_design_p2_3_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(gas_design_p2_3_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 611, 441))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.plane_graph = QtGui.QPushButton(self.widget_main)
        self.plane_graph.setGeometry(QtCore.QRect(460, 40, 130, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plane_graph.setFont(font)
        self.plane_graph.setObjectName(_fromUtf8("plane_graph"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 210, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gp = QtGui.QLineEdit(self.groupBox_3)
        self.gp.setGeometry(QtCore.QRect(100, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gp.setFont(font)
        self.gp.setObjectName(_fromUtf8("gp"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(20, 60, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.dp = QtGui.QLineEdit(self.groupBox_3)
        self.dp.setGeometry(QtCore.QRect(100, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dp.setFont(font)
        self.dp.setObjectName(_fromUtf8("dp"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(20, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(210, 60, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.pore_angle = QtGui.QLineEdit(self.groupBox_3)
        self.pore_angle.setGeometry(QtCore.QRect(310, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pore_angle.setFont(font)
        self.pore_angle.setObjectName(_fromUtf8("pore_angle"))
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(210, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.pore_stubble = QtGui.QLineEdit(self.groupBox_3)
        self.pore_stubble.setGeometry(QtCore.QRect(310, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pore_stubble.setFont(font)
        self.pore_stubble.setObjectName(_fromUtf8("pore_stubble"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(380, 30, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(170, 30, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(170, 60, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(380, 60, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.dip_angle = QtGui.QLineEdit(self.groupBox)
        self.dip_angle.setGeometry(QtCore.QRect(310, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dip_angle.setFont(font)
        self.dip_angle.setObjectName(_fromUtf8("dip_angle"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(210, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.thick = QtGui.QLineEdit(self.groupBox)
        self.thick.setGeometry(QtCore.QRect(100, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.thick.setFont(font)
        self.thick.setObjectName(_fromUtf8("thick"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(170, 30, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(380, 30, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(460, 280, 130, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.dip_graph = QtGui.QPushButton(self.widget_main)
        self.dip_graph.setGeometry(QtCore.QRect(460, 200, 130, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dip_graph.setFont(font)
        self.dip_graph.setObjectName(_fromUtf8("dip_graph"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 100, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.l2 = QtGui.QLineEdit(self.groupBox_2)
        self.l2.setGeometry(QtCore.QRect(310, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2.setFont(font)
        self.l2.setObjectName(_fromUtf8("l2"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(210, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.l1 = QtGui.QLineEdit(self.groupBox_2)
        self.l1.setGeometry(QtCore.QRect(100, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1.setFont(font)
        self.l1.setObjectName(_fromUtf8("l1"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.h = QtGui.QLineEdit(self.groupBox_2)
        self.h.setGeometry(QtCore.QRect(310, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.h.setFont(font)
        self.h.setObjectName(_fromUtf8("h"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 60, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(210, 60, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.w = QtGui.QLineEdit(self.groupBox_2)
        self.w.setGeometry(QtCore.QRect(100, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.setFont(font)
        self.w.setObjectName(_fromUtf8("w"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(170, 30, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(170, 60, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(380, 60, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(380, 30, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.head_graph = QtGui.QPushButton(self.widget_main)
        self.head_graph.setGeometry(QtCore.QRect(460, 120, 130, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.head_graph.setFont(font)
        self.head_graph.setObjectName(_fromUtf8("head_graph"))
        self.groupBox_4 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 320, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pore_type4 = QtGui.QRadioButton(self.groupBox_4)
        self.pore_type4.setGeometry(QtCore.QRect(160, 60, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pore_type4.setFont(font)
        self.pore_type4.setObjectName(_fromUtf8("pore_type4"))
        self.pore_type1 = QtGui.QRadioButton(self.groupBox_4)
        self.pore_type1.setGeometry(QtCore.QRect(20, 30, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pore_type1.setFont(font)
        self.pore_type1.setChecked(True)
        self.pore_type1.setObjectName(_fromUtf8("pore_type1"))
        self.pore_type3 = QtGui.QRadioButton(self.groupBox_4)
        self.pore_type3.setGeometry(QtCore.QRect(20, 60, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pore_type3.setFont(font)
        self.pore_type3.setObjectName(_fromUtf8("pore_type3"))
        self.pore_type2 = QtGui.QRadioButton(self.groupBox_4)
        self.pore_type2.setGeometry(QtCore.QRect(160, 30, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pore_type2.setFont(font)
        self.pore_type2.setObjectName(_fromUtf8("pore_type2"))
        self.creat_report = QtGui.QPushButton(self.widget_main)
        self.creat_report.setGeometry(QtCore.QRect(460, 360, 130, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.creat_report.setFont(font)
        self.creat_report.setObjectName(_fromUtf8("creat_report"))
        self.widget_title = QtGui.QWidget(gas_design_p2_3_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 611, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 521, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(570, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(gas_design_p2_3_dlg)
        QtCore.QMetaObject.connectSlotsByName(gas_design_p2_3_dlg)
        gas_design_p2_3_dlg.setTabOrder(self.thick, self.dip_angle)
        gas_design_p2_3_dlg.setTabOrder(self.dip_angle, self.l1)
        gas_design_p2_3_dlg.setTabOrder(self.l1, self.l2)
        gas_design_p2_3_dlg.setTabOrder(self.l2, self.w)
        gas_design_p2_3_dlg.setTabOrder(self.w, self.h)
        gas_design_p2_3_dlg.setTabOrder(self.h, self.dp)
        gas_design_p2_3_dlg.setTabOrder(self.dp, self.pore_stubble)
        gas_design_p2_3_dlg.setTabOrder(self.pore_stubble, self.gp)
        gas_design_p2_3_dlg.setTabOrder(self.gp, self.pore_angle)
        gas_design_p2_3_dlg.setTabOrder(self.pore_angle, self.pore_type1)
        gas_design_p2_3_dlg.setTabOrder(self.pore_type1, self.pore_type2)
        gas_design_p2_3_dlg.setTabOrder(self.pore_type2, self.pore_type3)
        gas_design_p2_3_dlg.setTabOrder(self.pore_type3, self.pore_type4)
        gas_design_p2_3_dlg.setTabOrder(self.pore_type4, self.plane_graph)
        gas_design_p2_3_dlg.setTabOrder(self.plane_graph, self.head_graph)
        gas_design_p2_3_dlg.setTabOrder(self.head_graph, self.dip_graph)
        gas_design_p2_3_dlg.setTabOrder(self.dip_graph, self.save)

    def retranslateUi(self, gas_design_p2_3_dlg):
        gas_design_p2_3_dlg.setWindowTitle(_translate("gas_design_p2_3_dlg", "顺层平行钻孔抽采工作面瓦斯", None))
        self.plane_graph.setText(_translate("gas_design_p2_3_dlg", "平 面 图", None))
        self.groupBox_3.setTitle(_translate("gas_design_p2_3_dlg", "钻孔参数", None))
        self.label_15.setText(_translate("gas_design_p2_3_dlg", "钻孔间距", None))
        self.label_17.setText(_translate("gas_design_p2_3_dlg", "钻孔直径", None))
        self.label_21.setText(_translate("gas_design_p2_3_dlg", "斜交钻孔角度", None))
        self.label_22.setText(_translate("gas_design_p2_3_dlg", "钻孔压茬长度", None))
        self.label_19.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(°)</p></body></html>", None))
        self.label_18.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_20.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_23.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.groupBox.setTitle(_translate("gas_design_p2_3_dlg", "煤层参数", None))
        self.label_10.setText(_translate("gas_design_p2_3_dlg", "煤层倾角", None))
        self.label_7.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_9.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(°)</p></body></html>", None))
        self.label_6.setText(_translate("gas_design_p2_3_dlg", "煤层厚度", None))
        self.save.setText(_translate("gas_design_p2_3_dlg", "保 存", None))
        self.dip_graph.setText(_translate("gas_design_p2_3_dlg", "倾 向 剖 面 图", None))
        self.groupBox_2.setTitle(_translate("gas_design_p2_3_dlg", "工作面参数", None))
        self.label_11.setText(_translate("gas_design_p2_3_dlg", "工作面长度", None))
        self.label_13.setText(_translate("gas_design_p2_3_dlg", "顺槽长度", None))
        self.label_14.setText(_translate("gas_design_p2_3_dlg", "巷道宽度", None))
        self.label_12.setText(_translate("gas_design_p2_3_dlg", "巷道高度", None))
        self.label_8.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_16.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_24.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_25.setText(_translate("gas_design_p2_3_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.head_graph.setText(_translate("gas_design_p2_3_dlg", "走 向 剖 面 图", None))
        self.groupBox_4.setTitle(_translate("gas_design_p2_3_dlg", "钻孔类型", None))
        self.pore_type4.setText(_translate("gas_design_p2_3_dlg", "交叉钻孔", None))
        self.pore_type1.setText(_translate("gas_design_p2_3_dlg", "平行钻孔", None))
        self.pore_type3.setText(_translate("gas_design_p2_3_dlg", "扇形钻孔", None))
        self.pore_type2.setText(_translate("gas_design_p2_3_dlg", "斜交钻孔", None))
        self.creat_report.setText(_translate("gas_design_p2_3_dlg", "生成钻孔及报单", None))
        self.lab_Ico.setText(_translate("gas_design_p2_3_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
