# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\gas_drilling_optimize_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_gas_drilling_optimize_dlg(object):
    def setupUi(self, gas_drilling_optimize_dlg):
        gas_drilling_optimize_dlg.setObjectName(_fromUtf8("gas_drilling_optimize_dlg"))
        gas_drilling_optimize_dlg.resize(523, 333)
        self.widget_title = QtGui.QWidget(gas_drilling_optimize_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 521, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 301, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(480, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))
        self.widget_main = QtGui.QWidget(gas_drilling_optimize_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 521, 371))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 501, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.mineName_label_14 = QtGui.QLabel(self.groupBox)
        self.mineName_label_14.setGeometry(QtCore.QRect(10, 30, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_14.setFont(font)
        self.mineName_label_14.setObjectName(_fromUtf8("mineName_label_14"))
        self.lamta = QtGui.QLineEdit(self.groupBox)
        self.lamta.setGeometry(QtCore.QRect(150, 30, 71, 31))
        self.lamta.setObjectName(_fromUtf8("lamta"))
        self.mineName_label_15 = QtGui.QLabel(self.groupBox)
        self.mineName_label_15.setGeometry(QtCore.QRect(10, 70, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_15.setFont(font)
        self.mineName_label_15.setObjectName(_fromUtf8("mineName_label_15"))
        self.p0 = QtGui.QLineEdit(self.groupBox)
        self.p0.setGeometry(QtCore.QRect(150, 70, 71, 31))
        self.p0.setObjectName(_fromUtf8("p0"))
        self.r0 = QtGui.QLineEdit(self.groupBox)
        self.r0.setGeometry(QtCore.QRect(150, 110, 71, 31))
        self.r0.setObjectName(_fromUtf8("r0"))
        self.mineName_label_16 = QtGui.QLabel(self.groupBox)
        self.mineName_label_16.setGeometry(QtCore.QRect(10, 110, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_16.setFont(font)
        self.mineName_label_16.setObjectName(_fromUtf8("mineName_label_16"))
        self.mineName_label_17 = QtGui.QLabel(self.groupBox)
        self.mineName_label_17.setGeometry(QtCore.QRect(290, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_17.setFont(font)
        self.mineName_label_17.setObjectName(_fromUtf8("mineName_label_17"))
        self.alpha = QtGui.QLineEdit(self.groupBox)
        self.alpha.setGeometry(QtCore.QRect(380, 30, 71, 31))
        self.alpha.setObjectName(_fromUtf8("alpha"))
        self.mineName_label_18 = QtGui.QLabel(self.groupBox)
        self.mineName_label_18.setGeometry(QtCore.QRect(230, 70, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_18.setFont(font)
        self.mineName_label_18.setObjectName(_fromUtf8("mineName_label_18"))
        self.mineName_label_19 = QtGui.QLabel(self.groupBox)
        self.mineName_label_19.setGeometry(QtCore.QRect(230, 110, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_19.setFont(font)
        self.mineName_label_19.setObjectName(_fromUtf8("mineName_label_19"))
        self.mineName_label_24 = QtGui.QLabel(self.groupBox)
        self.mineName_label_24.setGeometry(QtCore.QRect(460, 70, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_24.setFont(font)
        self.mineName_label_24.setObjectName(_fromUtf8("mineName_label_24"))
        self.mineName_label_25 = QtGui.QLabel(self.groupBox)
        self.mineName_label_25.setGeometry(QtCore.QRect(290, 70, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_25.setFont(font)
        self.mineName_label_25.setObjectName(_fromUtf8("mineName_label_25"))
        self.h = QtGui.QLineEdit(self.groupBox)
        self.h.setGeometry(QtCore.QRect(380, 70, 71, 31))
        self.h.setObjectName(_fromUtf8("h"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 501, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.mineName_label_22 = QtGui.QLabel(self.groupBox_2)
        self.mineName_label_22.setGeometry(QtCore.QRect(440, 30, 41, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_22.setFont(font)
        self.mineName_label_22.setObjectName(_fromUtf8("mineName_label_22"))
        self.R1 = QtGui.QLineEdit(self.groupBox_2)
        self.R1.setGeometry(QtCore.QRect(360, 30, 71, 31))
        self.R1.setObjectName(_fromUtf8("R1"))
        self.mineName_label_23 = QtGui.QLabel(self.groupBox_2)
        self.mineName_label_23.setGeometry(QtCore.QRect(270, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_23.setFont(font)
        self.mineName_label_23.setObjectName(_fromUtf8("mineName_label_23"))
        self.analyse = QtGui.QPushButton(self.groupBox_2)
        self.analyse.setGeometry(QtCore.QRect(380, 70, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.analyse.setFont(font)
        self.analyse.setObjectName(_fromUtf8("analyse"))
        self.mineName_label_27 = QtGui.QLabel(self.groupBox_2)
        self.mineName_label_27.setGeometry(QtCore.QRect(190, 80, 41, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_27.setFont(font)
        self.mineName_label_27.setObjectName(_fromUtf8("mineName_label_27"))
        self.eta = QtGui.QLineEdit(self.groupBox_2)
        self.eta.setGeometry(QtCore.QRect(110, 80, 71, 31))
        self.eta.setObjectName(_fromUtf8("eta"))
        self.cacl = QtGui.QPushButton(self.groupBox_2)
        self.cacl.setGeometry(QtCore.QRect(270, 70, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cacl.setFont(font)
        self.cacl.setObjectName(_fromUtf8("cacl"))
        self.mineName_label_26 = QtGui.QLabel(self.groupBox_2)
        self.mineName_label_26.setGeometry(QtCore.QRect(20, 80, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_26.setFont(font)
        self.mineName_label_26.setObjectName(_fromUtf8("mineName_label_26"))
        self.mineName_label_9 = QtGui.QLabel(self.groupBox_2)
        self.mineName_label_9.setGeometry(QtCore.QRect(190, 30, 41, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_9.setFont(font)
        self.mineName_label_9.setObjectName(_fromUtf8("mineName_label_9"))
        self.mineName_label_12 = QtGui.QLabel(self.groupBox_2)
        self.mineName_label_12.setGeometry(QtCore.QRect(20, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_12.setFont(font)
        self.mineName_label_12.setObjectName(_fromUtf8("mineName_label_12"))
        self.t0 = QtGui.QLineEdit(self.groupBox_2)
        self.t0.setGeometry(QtCore.QRect(110, 30, 71, 31))
        self.t0.setObjectName(_fromUtf8("t0"))
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.widget_main.raise_()
        self.widget_title.raise_()

        self.retranslateUi(gas_drilling_optimize_dlg)
        QtCore.QMetaObject.connectSlotsByName(gas_drilling_optimize_dlg)

    def retranslateUi(self, gas_drilling_optimize_dlg):
        gas_drilling_optimize_dlg.setWindowTitle(_translate("gas_drilling_optimize_dlg", "Form", None))
        self.lab_Ico.setText(_translate("gas_drilling_optimize_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.groupBox.setTitle(_translate("gas_drilling_optimize_dlg", "输入参数", None))
        self.mineName_label_14.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>煤层透气性系数λ</p></body></html>", None))
        self.mineName_label_15.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>初始煤层气压力p<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))
        self.p0.setText(_translate("gas_drilling_optimize_dlg", "1", None))
        self.r0.setText(_translate("gas_drilling_optimize_dlg", "50", None))
        self.mineName_label_16.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>抽采孔半径r<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))
        self.mineName_label_17.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>衰减系数α</p></body></html>", None))
        self.mineName_label_18.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>(MPa)</p></body></html>", None))
        self.mineName_label_19.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>(mm)</p></body></html>", None))
        self.mineName_label_24.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>(m)</p></body></html>", None))
        self.mineName_label_25.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>煤层厚度h</p></body></html>", None))
        self.groupBox_2.setTitle(_translate("gas_drilling_optimize_dlg", "输出结果", None))
        self.mineName_label_22.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>(mm)</p></body></html>", None))
        self.mineName_label_23.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>孔间距R<span style=\" vertical-align:sub;\">1</span></p></body></html>", None))
        self.analyse.setText(_translate("gas_drilling_optimize_dlg", "分析", None))
        self.mineName_label_27.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>(%)</p></body></html>", None))
        self.cacl.setText(_translate("gas_drilling_optimize_dlg", "计算", None))
        self.mineName_label_26.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>抽采率η</p></body></html>", None))
        self.mineName_label_9.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>(d)</p></body></html>", None))
        self.mineName_label_12.setText(_translate("gas_drilling_optimize_dlg", "<html><head/><body><p>抽采时间T<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))

