# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\gas_design_p1_2_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_gas_design_p1_2_dlg(object):
    def setupUi(self, gas_design_p1_2_dlg):
        gas_design_p1_2_dlg.setObjectName(_fromUtf8("gas_design_p1_2_dlg"))
        gas_design_p1_2_dlg.resize(439, 392)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gas_design_p1_2_dlg.setWindowIcon(icon)
        self.plane_graph = QtGui.QPushButton(gas_design_p1_2_dlg)
        self.plane_graph.setGeometry(QtCore.QRect(320, 40, 101, 51))
        self.plane_graph.setObjectName(_fromUtf8("plane_graph"))
        self.dip_graph = QtGui.QPushButton(gas_design_p1_2_dlg)
        self.dip_graph.setGeometry(QtCore.QRect(320, 200, 101, 51))
        self.dip_graph.setObjectName(_fromUtf8("dip_graph"))
        self.groupBox = QtGui.QGroupBox(gas_design_p1_2_dlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 281, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.dip_angle = QtGui.QLineEdit(self.groupBox)
        self.dip_angle.setGeometry(QtCore.QRect(200, 20, 41, 20))
        self.dip_angle.setObjectName(_fromUtf8("dip_angle"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(140, 20, 51, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.thick = QtGui.QLineEdit(self.groupBox)
        self.thick.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.thick.setObjectName(_fromUtf8("thick"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(120, 20, 16, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(250, 20, 12, 14))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.save = QtGui.QPushButton(gas_design_p1_2_dlg)
        self.save.setGeometry(QtCore.QRect(320, 280, 101, 51))
        self.save.setObjectName(_fromUtf8("save"))
        self.groupBox_2 = QtGui.QGroupBox(gas_design_p1_2_dlg)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 281, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Lm = QtGui.QLineEdit(self.groupBox_2)
        self.Lm.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.Lm.setObjectName(_fromUtf8("Lm"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.h = QtGui.QLineEdit(self.groupBox_2)
        self.h.setGeometry(QtCore.QRect(210, 50, 41, 20))
        self.h.setObjectName(_fromUtf8("h"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(140, 50, 61, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.w = QtGui.QLineEdit(self.groupBox_2)
        self.w.setGeometry(QtCore.QRect(70, 50, 41, 20))
        self.w.setObjectName(_fromUtf8("w"))
        self.groupBox_3 = QtGui.QGroupBox(gas_design_p1_2_dlg)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 281, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.Gbp = QtGui.QLineEdit(self.groupBox_3)
        self.Gbp.setGeometry(QtCore.QRect(220, 20, 51, 20))
        self.Gbp.setObjectName(_fromUtf8("Gbp"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(150, 20, 61, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.Dp = QtGui.QLineEdit(self.groupBox_3)
        self.Dp.setGeometry(QtCore.QRect(80, 20, 41, 20))
        self.Dp.setObjectName(_fromUtf8("Dp"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 51, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(20, 80, 111, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.L_stripe = QtGui.QLineEdit(self.groupBox_3)
        self.L_stripe.setGeometry(QtCore.QRect(130, 80, 51, 20))
        self.L_stripe.setObjectName(_fromUtf8("L_stripe"))
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.leading_dist = QtGui.QLineEdit(self.groupBox_3)
        self.leading_dist.setGeometry(QtCore.QRect(90, 50, 41, 20))
        self.leading_dist.setObjectName(_fromUtf8("leading_dist"))
        self.groupBox_4 = QtGui.QGroupBox(gas_design_p1_2_dlg)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 170, 281, 81))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.bottom = QtGui.QLineEdit(self.groupBox_4)
        self.bottom.setGeometry(QtCore.QRect(150, 20, 41, 20))
        self.bottom.setObjectName(_fromUtf8("bottom"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(120, 20, 31, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.top = QtGui.QLineEdit(self.groupBox_4)
        self.top.setGeometry(QtCore.QRect(60, 20, 41, 20))
        self.top.setObjectName(_fromUtf8("top"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 51, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.right = QtGui.QLineEdit(self.groupBox_4)
        self.right.setGeometry(QtCore.QRect(150, 50, 41, 20))
        self.right.setObjectName(_fromUtf8("right"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(20, 50, 51, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(120, 50, 31, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.left = QtGui.QLineEdit(self.groupBox_4)
        self.left.setGeometry(QtCore.QRect(60, 50, 41, 20))
        self.left.setObjectName(_fromUtf8("left"))
        self.help = QtGui.QPushButton(self.groupBox_4)
        self.help.setGeometry(QtCore.QRect(210, 20, 61, 51))
        self.help.setObjectName(_fromUtf8("help"))
        self.head_graph = QtGui.QPushButton(gas_design_p1_2_dlg)
        self.head_graph.setGeometry(QtCore.QRect(320, 120, 101, 51))
        self.head_graph.setObjectName(_fromUtf8("head_graph"))

        self.retranslateUi(gas_design_p1_2_dlg)
        QtCore.QMetaObject.connectSlotsByName(gas_design_p1_2_dlg)
        gas_design_p1_2_dlg.setTabOrder(self.thick, self.dip_angle)
        gas_design_p1_2_dlg.setTabOrder(self.dip_angle, self.Lm)
        gas_design_p1_2_dlg.setTabOrder(self.Lm, self.w)
        gas_design_p1_2_dlg.setTabOrder(self.w, self.h)
        gas_design_p1_2_dlg.setTabOrder(self.h, self.top)
        gas_design_p1_2_dlg.setTabOrder(self.top, self.bottom)
        gas_design_p1_2_dlg.setTabOrder(self.bottom, self.left)
        gas_design_p1_2_dlg.setTabOrder(self.left, self.right)
        gas_design_p1_2_dlg.setTabOrder(self.right, self.help)
        gas_design_p1_2_dlg.setTabOrder(self.help, self.Dp)
        gas_design_p1_2_dlg.setTabOrder(self.Dp, self.Gbp)
        gas_design_p1_2_dlg.setTabOrder(self.Gbp, self.leading_dist)
        gas_design_p1_2_dlg.setTabOrder(self.leading_dist, self.L_stripe)
        gas_design_p1_2_dlg.setTabOrder(self.L_stripe, self.plane_graph)
        gas_design_p1_2_dlg.setTabOrder(self.plane_graph, self.head_graph)
        gas_design_p1_2_dlg.setTabOrder(self.head_graph, self.dip_graph)
        gas_design_p1_2_dlg.setTabOrder(self.dip_graph, self.save)

    def retranslateUi(self, gas_design_p1_2_dlg):
        gas_design_p1_2_dlg.setWindowTitle(_translate("gas_design_p1_2_dlg", "顺层钻孔条带掩护巷道掘进抽采法", None))
        self.plane_graph.setText(_translate("gas_design_p1_2_dlg", "平 面 图", None))
        self.dip_graph.setText(_translate("gas_design_p1_2_dlg", "倾 向 剖 面 图", None))
        self.groupBox.setTitle(_translate("gas_design_p1_2_dlg", ">>煤层参数", None))
        self.label_10.setText(_translate("gas_design_p1_2_dlg", "煤层倾角", None))
        self.label_7.setText(_translate("gas_design_p1_2_dlg", "<html><head/><body><p>m</p></body></html>", None))
        self.label_9.setText(_translate("gas_design_p1_2_dlg", "<html><head/><body><p>°</p></body></html>", None))
        self.label_6.setText(_translate("gas_design_p1_2_dlg", "煤层厚度", None))
        self.save.setText(_translate("gas_design_p1_2_dlg", "保 存", None))
        self.groupBox_2.setTitle(_translate("gas_design_p1_2_dlg", ">>掘进巷道参数", None))
        self.label_13.setText(_translate("gas_design_p1_2_dlg", "掘进长度", None))
        self.label_14.setText(_translate("gas_design_p1_2_dlg", "巷道宽度", None))
        self.label_12.setText(_translate("gas_design_p1_2_dlg", "巷道高度", None))
        self.groupBox_3.setTitle(_translate("gas_design_p1_2_dlg", ">>钻孔参数", None))
        self.label_15.setText(_translate("gas_design_p1_2_dlg", "钻孔底间距", None))
        self.label_17.setText(_translate("gas_design_p1_2_dlg", "钻孔直径", None))
        self.label_21.setText(_translate("gas_design_p1_2_dlg", "钻孔控制的条带长度", None))
        self.label_22.setText(_translate("gas_design_p1_2_dlg", "钻孔超前距", None))
        self.groupBox_4.setTitle(_translate("gas_design_p1_2_dlg", ">>回采巷道控制范围", None))
        self.label_16.setText(_translate("gas_design_p1_2_dlg", "下帮", None))
        self.label_18.setText(_translate("gas_design_p1_2_dlg", "上帮", None))
        self.label_19.setText(_translate("gas_design_p1_2_dlg", "左帮", None))
        self.label_20.setText(_translate("gas_design_p1_2_dlg", "右帮", None))
        self.help.setText(_translate("gas_design_p1_2_dlg", "参考取值", None))
        self.head_graph.setText(_translate("gas_design_p1_2_dlg", "走 向 剖 面 图", None))

import usecad_rc
