# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\gas_design_p1_1_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_gas_design_p1_1_dlg(object):
    def setupUi(self, gas_design_p1_1_dlg):
        gas_design_p1_1_dlg.setObjectName(_fromUtf8("gas_design_p1_1_dlg"))
        gas_design_p1_1_dlg.resize(571, 369)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gas_design_p1_1_dlg.setWindowIcon(icon)
        self.groupBox = QtGui.QGroupBox(gas_design_p1_1_dlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.dip_angle = QtGui.QLineEdit(self.groupBox)
        self.dip_angle.setGeometry(QtCore.QRect(200, 20, 41, 20))
        self.dip_angle.setObjectName(_fromUtf8("dip_angle"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(140, 20, 51, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.thick = QtGui.QLineEdit(self.groupBox)
        self.thick.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.thick.setObjectName(_fromUtf8("thick"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(120, 20, 16, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(250, 20, 12, 14))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox_2 = QtGui.QGroupBox(gas_design_p1_1_dlg)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 271, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.L2 = QtGui.QLineEdit(self.groupBox_2)
        self.L2.setGeometry(QtCore.QRect(210, 20, 41, 20))
        self.L2.setObjectName(_fromUtf8("L2"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(140, 20, 61, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.L1 = QtGui.QLineEdit(self.groupBox_2)
        self.L1.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.L1.setObjectName(_fromUtf8("L1"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.h = QtGui.QLineEdit(self.groupBox_2)
        self.h.setGeometry(QtCore.QRect(210, 50, 41, 20))
        self.h.setObjectName(_fromUtf8("h"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(140, 50, 61, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.w = QtGui.QLineEdit(self.groupBox_2)
        self.w.setGeometry(QtCore.QRect(70, 50, 41, 20))
        self.w.setObjectName(_fromUtf8("w"))
        self.groupBox_3 = QtGui.QGroupBox(gas_design_p1_1_dlg)
        self.groupBox_3.setGeometry(QtCore.QRect(290, 10, 271, 51))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.pore_gap = QtGui.QLineEdit(self.groupBox_3)
        self.pore_gap.setGeometry(QtCore.QRect(210, 20, 51, 20))
        self.pore_gap.setObjectName(_fromUtf8("pore_gap"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(150, 20, 51, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.Dp = QtGui.QLineEdit(self.groupBox_3)
        self.Dp.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.Dp.setObjectName(_fromUtf8("Dp"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.groupBox_4 = QtGui.QGroupBox(gas_design_p1_1_dlg)
        self.groupBox_4.setGeometry(QtCore.QRect(290, 80, 271, 81))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.bottom = QtGui.QLineEdit(self.groupBox_4)
        self.bottom.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.bottom.setObjectName(_fromUtf8("bottom"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(110, 20, 31, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.top = QtGui.QLineEdit(self.groupBox_4)
        self.top.setGeometry(QtCore.QRect(50, 20, 41, 20))
        self.top.setObjectName(_fromUtf8("top"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.right = QtGui.QLineEdit(self.groupBox_4)
        self.right.setGeometry(QtCore.QRect(140, 50, 41, 20))
        self.right.setObjectName(_fromUtf8("right"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(110, 50, 31, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.left = QtGui.QLineEdit(self.groupBox_4)
        self.left.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.left.setObjectName(_fromUtf8("left"))
        self.help = QtGui.QPushButton(self.groupBox_4)
        self.help.setGeometry(QtCore.QRect(200, 20, 61, 51))
        self.help.setObjectName(_fromUtf8("help"))
        self.groupBox_5 = QtGui.QGroupBox(gas_design_p1_1_dlg)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 180, 271, 111))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.Hd = QtGui.QLineEdit(self.groupBox_5)
        self.Hd.setGeometry(QtCore.QRect(210, 20, 41, 20))
        self.Hd.setObjectName(_fromUtf8("Hd"))
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(140, 20, 61, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.Wd = QtGui.QLineEdit(self.groupBox_5)
        self.Wd.setGeometry(QtCore.QRect(80, 20, 41, 20))
        self.Wd.setObjectName(_fromUtf8("Wd"))
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.H_offset = QtGui.QLineEdit(self.groupBox_5)
        self.H_offset.setGeometry(QtCore.QRect(200, 80, 41, 20))
        self.H_offset.setObjectName(_fromUtf8("H_offset"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(10, 80, 181, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.V_offset = QtGui.QLineEdit(self.groupBox_5)
        self.V_offset.setGeometry(QtCore.QRect(130, 50, 41, 20))
        self.V_offset.setObjectName(_fromUtf8("V_offset"))
        self.groupBox_6 = QtGui.QGroupBox(gas_design_p1_1_dlg)
        self.groupBox_6.setGeometry(QtCore.QRect(290, 180, 271, 111))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.Ws = QtGui.QLineEdit(self.groupBox_6)
        self.Ws.setGeometry(QtCore.QRect(200, 30, 51, 20))
        self.Ws.setObjectName(_fromUtf8("Ws"))
        self.label_25 = QtGui.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(140, 30, 61, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.Ls = QtGui.QLineEdit(self.groupBox_6)
        self.Ls.setGeometry(QtCore.QRect(70, 30, 51, 20))
        self.Ls.setObjectName(_fromUtf8("Ls"))
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.site_gap = QtGui.QLineEdit(self.groupBox_6)
        self.site_gap.setGeometry(QtCore.QRect(200, 70, 51, 20))
        self.site_gap.setObjectName(_fromUtf8("site_gap"))
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(10, 70, 51, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.groupBox_6)
        self.label_28.setGeometry(QtCore.QRect(140, 70, 61, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.Hs = QtGui.QLineEdit(self.groupBox_6)
        self.Hs.setGeometry(QtCore.QRect(70, 70, 51, 20))
        self.Hs.setObjectName(_fromUtf8("Hs"))
        self.save = QtGui.QPushButton(gas_design_p1_1_dlg)
        self.save.setGeometry(QtCore.QRect(40, 310, 101, 51))
        self.save.setObjectName(_fromUtf8("save"))
        self.plane_graph = QtGui.QPushButton(gas_design_p1_1_dlg)
        self.plane_graph.setGeometry(QtCore.QRect(170, 310, 101, 51))
        self.plane_graph.setObjectName(_fromUtf8("plane_graph"))
        self.head_graph = QtGui.QPushButton(gas_design_p1_1_dlg)
        self.head_graph.setGeometry(QtCore.QRect(300, 310, 101, 51))
        self.head_graph.setObjectName(_fromUtf8("head_graph"))
        self.dip_graph = QtGui.QPushButton(gas_design_p1_1_dlg)
        self.dip_graph.setGeometry(QtCore.QRect(430, 310, 101, 51))
        self.dip_graph.setObjectName(_fromUtf8("dip_graph"))

        self.retranslateUi(gas_design_p1_1_dlg)
        QtCore.QMetaObject.connectSlotsByName(gas_design_p1_1_dlg)
        gas_design_p1_1_dlg.setTabOrder(self.thick, self.dip_angle)
        gas_design_p1_1_dlg.setTabOrder(self.dip_angle, self.Dp)
        gas_design_p1_1_dlg.setTabOrder(self.Dp, self.pore_gap)
        gas_design_p1_1_dlg.setTabOrder(self.pore_gap, self.L1)
        gas_design_p1_1_dlg.setTabOrder(self.L1, self.L2)
        gas_design_p1_1_dlg.setTabOrder(self.L2, self.top)
        gas_design_p1_1_dlg.setTabOrder(self.top, self.bottom)
        gas_design_p1_1_dlg.setTabOrder(self.bottom, self.w)
        gas_design_p1_1_dlg.setTabOrder(self.w, self.h)
        gas_design_p1_1_dlg.setTabOrder(self.h, self.left)
        gas_design_p1_1_dlg.setTabOrder(self.left, self.right)
        gas_design_p1_1_dlg.setTabOrder(self.right, self.help)
        gas_design_p1_1_dlg.setTabOrder(self.help, self.Wd)
        gas_design_p1_1_dlg.setTabOrder(self.Wd, self.Hd)
        gas_design_p1_1_dlg.setTabOrder(self.Hd, self.V_offset)
        gas_design_p1_1_dlg.setTabOrder(self.V_offset, self.H_offset)
        gas_design_p1_1_dlg.setTabOrder(self.H_offset, self.Ls)
        gas_design_p1_1_dlg.setTabOrder(self.Ls, self.Ws)
        gas_design_p1_1_dlg.setTabOrder(self.Ws, self.Hs)
        gas_design_p1_1_dlg.setTabOrder(self.Hs, self.site_gap)
        gas_design_p1_1_dlg.setTabOrder(self.site_gap, self.save)
        gas_design_p1_1_dlg.setTabOrder(self.save, self.plane_graph)
        gas_design_p1_1_dlg.setTabOrder(self.plane_graph, self.head_graph)
        gas_design_p1_1_dlg.setTabOrder(self.head_graph, self.dip_graph)

    def retranslateUi(self, gas_design_p1_1_dlg):
        gas_design_p1_1_dlg.setWindowTitle(_translate("gas_design_p1_1_dlg", "底板岩巷密集穿层钻孔抽采煤巷条带瓦斯", None))
        self.groupBox.setTitle(_translate("gas_design_p1_1_dlg", ">>煤层参数", None))
        self.label_10.setText(_translate("gas_design_p1_1_dlg", "煤层倾角", None))
        self.label_7.setText(_translate("gas_design_p1_1_dlg", "<html><head/><body><p>m</p></body></html>", None))
        self.label_9.setText(_translate("gas_design_p1_1_dlg", "<html><head/><body><p>°</p></body></html>", None))
        self.label_6.setText(_translate("gas_design_p1_1_dlg", "煤层厚度", None))
        self.groupBox_2.setTitle(_translate("gas_design_p1_1_dlg", ">>工作面参数", None))
        self.label_11.setText(_translate("gas_design_p1_1_dlg", "工作面长度", None))
        self.label_13.setText(_translate("gas_design_p1_1_dlg", "顺槽长度", None))
        self.label_14.setText(_translate("gas_design_p1_1_dlg", "巷道宽度", None))
        self.label_12.setText(_translate("gas_design_p1_1_dlg", "巷道高度", None))
        self.groupBox_3.setTitle(_translate("gas_design_p1_1_dlg", ">>钻孔参数", None))
        self.label_15.setText(_translate("gas_design_p1_1_dlg", "钻孔间距", None))
        self.label_17.setText(_translate("gas_design_p1_1_dlg", "钻孔直径", None))
        self.groupBox_4.setTitle(_translate("gas_design_p1_1_dlg", ">>回采巷道控制范围", None))
        self.label_16.setText(_translate("gas_design_p1_1_dlg", "下帮", None))
        self.label_18.setText(_translate("gas_design_p1_1_dlg", "上帮", None))
        self.label_19.setText(_translate("gas_design_p1_1_dlg", "左帮", None))
        self.label_20.setText(_translate("gas_design_p1_1_dlg", "右帮", None))
        self.help.setText(_translate("gas_design_p1_1_dlg", "参考取值", None))
        self.groupBox_5.setTitle(_translate("gas_design_p1_1_dlg", ">>底板巷参数", None))
        self.label_21.setText(_translate("gas_design_p1_1_dlg", "底板巷高度", None))
        self.label_22.setText(_translate("gas_design_p1_1_dlg", "底板巷宽度", None))
        self.label_23.setText(_translate("gas_design_p1_1_dlg", "底板巷与工作面垂距", None))
        self.label_24.setText(_translate("gas_design_p1_1_dlg", "底板巷与工作面风巷水平投影距离", None))
        self.groupBox_6.setTitle(_translate("gas_design_p1_1_dlg", ">>钻场参数", None))
        self.label_25.setText(_translate("gas_design_p1_1_dlg", "钻场宽度", None))
        self.label_26.setText(_translate("gas_design_p1_1_dlg", "钻场长度", None))
        self.label_27.setText(_translate("gas_design_p1_1_dlg", "钻场高度", None))
        self.label_28.setText(_translate("gas_design_p1_1_dlg", "钻场间距", None))
        self.save.setText(_translate("gas_design_p1_1_dlg", "保 存", None))
        self.plane_graph.setText(_translate("gas_design_p1_1_dlg", "平 面 图", None))
        self.head_graph.setText(_translate("gas_design_p1_1_dlg", "走 向 剖 面 图", None))
        self.dip_graph.setText(_translate("gas_design_p1_1_dlg", "倾 向 剖 面 图", None))

import usecad_rc
