# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\gas_drilling_radius_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_gas_drilling_radius_dlg(object):
    def setupUi(self, gas_drilling_radius_dlg):
        gas_drilling_radius_dlg.setObjectName(_fromUtf8("gas_drilling_radius_dlg"))
        gas_drilling_radius_dlg.resize(801, 420)
        font = QtGui.QFont()
        font.setPointSize(12)
        gas_drilling_radius_dlg.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gas_drilling_radius_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(gas_drilling_radius_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 801, 391))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.cacl = QtGui.QPushButton(self.widget_main)
        self.cacl.setGeometry(QtCore.QRect(510, 340, 101, 41))
        self.cacl.setObjectName(_fromUtf8("cacl"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 60, 331, 111))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gas_w0 = QtGui.QLineEdit(self.groupBox_2)
        self.gas_w0.setGeometry(QtCore.QRect(170, 30, 61, 25))
        self.gas_w0.setObjectName(_fromUtf8("gas_w0"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 151, 25))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.hw = QtGui.QLineEdit(self.groupBox_2)
        self.hw.setGeometry(QtCore.QRect(80, 70, 61, 25))
        self.hw.setObjectName(_fromUtf8("hw"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 51, 25))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(150, 70, 31, 25))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(240, 30, 51, 25))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(650, 340, 101, 41))
        self.save.setObjectName(_fromUtf8("save"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(460, 20, 71, 25))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_3.setGeometry(QtCore.QRect(460, 180, 331, 151))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gas_wc3 = QtGui.QLineEdit(self.groupBox_3)
        self.gas_wc3.setGeometry(QtCore.QRect(210, 110, 61, 25))
        self.gas_wc3.setObjectName(_fromUtf8("gas_wc3"))
        self.eta = QtGui.QLineEdit(self.groupBox_3)
        self.eta.setGeometry(QtCore.QRect(80, 70, 61, 25))
        self.eta.setObjectName(_fromUtf8("eta"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 141, 25))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 70, 71, 25))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 110, 201, 25))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.qm = QtGui.QLineEdit(self.groupBox_3)
        self.qm.setGeometry(QtCore.QRect(150, 30, 61, 25))
        self.qm.setObjectName(_fromUtf8("qm"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(220, 30, 41, 25))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(150, 70, 31, 25))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(280, 110, 51, 25))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.coal = QtGui.QComboBox(self.widget_main)
        self.coal.setGeometry(QtCore.QRect(540, 20, 231, 25))
        self.coal.setObjectName(_fromUtf8("coal"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 441, 311))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.qsum = QtGui.QLineEdit(self.groupBox)
        self.qsum.setGeometry(QtCore.QRect(300, 270, 61, 25))
        self.qsum.setObjectName(_fromUtf8("qsum"))
        self.r = QtGui.QLineEdit(self.groupBox)
        self.r.setGeometry(QtCore.QRect(110, 30, 61, 25))
        self.r.setObjectName(_fromUtf8("r"))
        self.k1 = QtGui.QLineEdit(self.groupBox)
        self.k1.setGeometry(QtCore.QRect(340, 70, 61, 25))
        self.k1.setObjectName(_fromUtf8("k1"))
        self.mineName_label_14 = QtGui.QLabel(self.groupBox)
        self.mineName_label_14.setGeometry(QtCore.QRect(20, 150, 181, 25))
        self.mineName_label_14.setObjectName(_fromUtf8("mineName_label_14"))
        self.t = QtGui.QLineEdit(self.groupBox)
        self.t.setGeometry(QtCore.QRect(170, 230, 61, 25))
        self.t.setObjectName(_fromUtf8("t"))
        self.mineName_label_9 = QtGui.QLabel(self.groupBox)
        self.mineName_label_9.setGeometry(QtCore.QRect(20, 70, 311, 25))
        self.mineName_label_9.setObjectName(_fromUtf8("mineName_label_9"))
        self.mineName_label_8 = QtGui.QLabel(self.groupBox)
        self.mineName_label_8.setGeometry(QtCore.QRect(230, 30, 101, 25))
        self.mineName_label_8.setObjectName(_fromUtf8("mineName_label_8"))
        self.l = QtGui.QLineEdit(self.groupBox)
        self.l.setGeometry(QtCore.QRect(330, 30, 61, 25))
        self.l.setObjectName(_fromUtf8("l"))
        self.mineName_label_11 = QtGui.QLabel(self.groupBox)
        self.mineName_label_11.setGeometry(QtCore.QRect(20, 190, 211, 25))
        self.mineName_label_11.setObjectName(_fromUtf8("mineName_label_11"))
        self.rho = QtGui.QLineEdit(self.groupBox)
        self.rho.setGeometry(QtCore.QRect(210, 110, 61, 25))
        self.rho.setObjectName(_fromUtf8("rho"))
        self.mineName_label_7 = QtGui.QLabel(self.groupBox)
        self.mineName_label_7.setGeometry(QtCore.QRect(20, 30, 81, 25))
        self.mineName_label_7.setObjectName(_fromUtf8("mineName_label_7"))
        self.q0 = QtGui.QLineEdit(self.groupBox)
        self.q0.setGeometry(QtCore.QRect(210, 150, 61, 25))
        self.q0.setObjectName(_fromUtf8("q0"))
        self.mineName_label_12 = QtGui.QLabel(self.groupBox)
        self.mineName_label_12.setGeometry(QtCore.QRect(20, 230, 141, 25))
        self.mineName_label_12.setObjectName(_fromUtf8("mineName_label_12"))
        self.mineName_label_13 = QtGui.QLabel(self.groupBox)
        self.mineName_label_13.setGeometry(QtCore.QRect(20, 270, 271, 25))
        self.mineName_label_13.setObjectName(_fromUtf8("mineName_label_13"))
        self.mineName_label_10 = QtGui.QLabel(self.groupBox)
        self.mineName_label_10.setGeometry(QtCore.QRect(20, 110, 181, 25))
        self.mineName_label_10.setObjectName(_fromUtf8("mineName_label_10"))
        self.a = QtGui.QLineEdit(self.groupBox)
        self.a.setGeometry(QtCore.QRect(240, 190, 61, 25))
        self.a.setObjectName(_fromUtf8("a"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 31, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(400, 30, 31, 25))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(410, 70, 31, 25))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(280, 110, 51, 25))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(280, 150, 71, 25))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(310, 190, 51, 25))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(240, 230, 31, 25))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(370, 270, 41, 25))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.mineName_label_15 = QtGui.QLabel(self.widget_main)
        self.mineName_label_15.setGeometry(QtCore.QRect(10, 350, 471, 31))
        self.mineName_label_15.setObjectName(_fromUtf8("mineName_label_15"))
        self.widget_title = QtGui.QWidget(gas_drilling_radius_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 801, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 711, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(760, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(gas_drilling_radius_dlg)
        QtCore.QMetaObject.connectSlotsByName(gas_drilling_radius_dlg)
        gas_drilling_radius_dlg.setTabOrder(self.coal, self.r)
        gas_drilling_radius_dlg.setTabOrder(self.r, self.l)
        gas_drilling_radius_dlg.setTabOrder(self.l, self.k1)
        gas_drilling_radius_dlg.setTabOrder(self.k1, self.rho)
        gas_drilling_radius_dlg.setTabOrder(self.rho, self.q0)
        gas_drilling_radius_dlg.setTabOrder(self.q0, self.a)
        gas_drilling_radius_dlg.setTabOrder(self.a, self.t)
        gas_drilling_radius_dlg.setTabOrder(self.t, self.qsum)
        gas_drilling_radius_dlg.setTabOrder(self.qsum, self.gas_w0)
        gas_drilling_radius_dlg.setTabOrder(self.gas_w0, self.hw)
        gas_drilling_radius_dlg.setTabOrder(self.hw, self.qm)
        gas_drilling_radius_dlg.setTabOrder(self.qm, self.eta)
        gas_drilling_radius_dlg.setTabOrder(self.eta, self.gas_wc3)
        gas_drilling_radius_dlg.setTabOrder(self.gas_wc3, self.cacl)
        gas_drilling_radius_dlg.setTabOrder(self.cacl, self.save)

    def retranslateUi(self, gas_drilling_radius_dlg):
        gas_drilling_radius_dlg.setWindowTitle(_translate("gas_drilling_radius_dlg", "瓦斯抽采半径计算", None))
        self.cacl.setText(_translate("gas_drilling_radius_dlg", "计 算", None))
        self.groupBox_2.setTitle(_translate("gas_drilling_radius_dlg", "煤层参数", None))
        self.label_10.setText(_translate("gas_drilling_radius_dlg", "煤层原始瓦斯含量W", None))
        self.label_11.setText(_translate("gas_drilling_radius_dlg", "采高h", None))
        self.label_2.setText(_translate("gas_drilling_radius_dlg", "(m)", None))
        self.label_16.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>(m<span style=\" vertical-align:super;\">3</span>/t)</p></body></html>", None))
        self.save.setText(_translate("gas_drilling_radius_dlg", "保 存", None))
        self.label.setText(_translate("gas_drilling_radius_dlg", "煤层列表", None))
        self.groupBox_3.setTitle(_translate("gas_drilling_radius_dlg", "计算结果", None))
        self.label_12.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>吨煤瓦斯抽采量Q<span style=\" vertical-align:sub;\">m</span></p></body></html>", None))
        self.label_13.setText(_translate("gas_drilling_radius_dlg", "抽采率η", None))
        self.label_14.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>抽采后煤层残存瓦斯含量W<span style=\" vertical-align:sub;\">c</span></p></body></html>", None))
        self.label_17.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>(m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.label_18.setText(_translate("gas_drilling_radius_dlg", "(%)", None))
        self.label_19.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>(m<span style=\" vertical-align:super;\">3</span>/t)</p></body></html>", None))
        self.groupBox.setTitle(_translate("gas_drilling_radius_dlg", "钻孔抽采参数", None))
        self.mineName_label_14.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>钻孔初始瓦斯抽采流量q<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))
        self.mineName_label_9.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>抽采负压后，较自然瓦斯涌出量的增大值K<span style=\" vertical-align:sub;\">1</span></p></body></html>", None))
        self.mineName_label_8.setText(_translate("gas_drilling_radius_dlg", "抽采孔孔长L", None))
        self.mineName_label_11.setText(_translate("gas_drilling_radius_dlg", "钻孔瓦斯抽采流量衰减系数α", None))
        self.mineName_label_7.setText(_translate("gas_drilling_radius_dlg", "抽采半径R", None))
        self.mineName_label_12.setText(_translate("gas_drilling_radius_dlg", "钻孔抽采瓦斯时间t", None))
        self.mineName_label_13.setText(_translate("gas_drilling_radius_dlg", "抽采时间内，钻孔的累计瓦斯抽采量Q", None))
        self.mineName_label_10.setText(_translate("gas_drilling_radius_dlg", "抽采范围内煤的视密度ρ", None))
        self.label_3.setText(_translate("gas_drilling_radius_dlg", "(m)", None))
        self.label_4.setText(_translate("gas_drilling_radius_dlg", "(m)", None))
        self.label_5.setText(_translate("gas_drilling_radius_dlg", "(%)", None))
        self.label_6.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>(m<span style=\" vertical-align:super;\">3</span>/t)</p></body></html>", None))
        self.label_7.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>(m<span style=\" vertical-align:super;\">3</span>/min)</p></body></html>", None))
        self.label_8.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>(d<span style=\" vertical-align:super;\">-1</span>)</p></body></html>", None))
        self.label_9.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>(d)</p></body></html>", None))
        self.label_15.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p>(m<span style=\" vertical-align:super;\">3</span>)</p></body></html>", None))
        self.mineName_label_15.setText(_translate("gas_drilling_radius_dlg", "<html><head/><body><p><span style=\" font-size:10pt; color:#00ffff;\">根据规定要求:抽采率η应大于等于0.3；抽采后煤层残存瓦斯含量Wc应小于等于8</span></p></body></html>", None))
        self.lab_Ico.setText(_translate("gas_drilling_radius_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
