# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\high_drilling_design_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_high_drilling_design_dlg(object):
    def setupUi(self, high_drilling_design_dlg):
        high_drilling_design_dlg.setObjectName(_fromUtf8("high_drilling_design_dlg"))
        high_drilling_design_dlg.resize(680, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        high_drilling_design_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(high_drilling_design_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 681, 451))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.abc = QtGui.QTableWidget(self.widget_main)
        self.abc.setGeometry(QtCore.QRect(40, 240, 301, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.abc.setFont(font)
        self.abc.setObjectName(_fromUtf8("abc"))
        self.abc.setColumnCount(3)
        self.abc.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.abc.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.abc.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.abc.setHorizontalHeaderItem(2, item)
        self.label_8 = QtGui.QLabel(self.widget_main)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.bcd = QtGui.QTableWidget(self.widget_main)
        self.bcd.setGeometry(QtCore.QRect(350, 240, 301, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bcd.setFont(font)
        self.bcd.setObjectName(_fromUtf8("bcd"))
        self.bcd.setColumnCount(3)
        self.bcd.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.bcd.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.bcd.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.bcd.setHorizontalHeaderItem(2, item)
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(530, 20, 130, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.drill_pore = QtGui.QPushButton(self.widget_main)
        self.drill_pore.setGeometry(QtCore.QRect(400, 20, 120, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drill_pore.setFont(font)
        self.drill_pore.setObjectName(_fromUtf8("drill_pore"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(30, 180, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_14 = QtGui.QLabel(self.widget_main)
        self.label_14.setGeometry(QtCore.QRect(360, 210, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 641, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.l2 = QtGui.QLineEdit(self.groupBox)
        self.l2.setGeometry(QtCore.QRect(490, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2.setFont(font)
        self.l2.setObjectName(_fromUtf8("l2"))
        self.lg = QtGui.QLineEdit(self.groupBox)
        self.lg.setGeometry(QtCore.QRect(180, 70, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lg.setFont(font)
        self.lg.setObjectName(_fromUtf8("lg"))
        self.l1 = QtGui.QLineEdit(self.groupBox)
        self.l1.setGeometry(QtCore.QRect(180, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1.setFont(font)
        self.l1.setObjectName(_fromUtf8("l1"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(330, 30, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(250, 30, 41, 25))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(560, 30, 41, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(250, 70, 41, 25))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_13 = QtGui.QLabel(self.widget_main)
        self.label_13.setGeometry(QtCore.QRect(50, 210, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.drill_site = QtGui.QPushButton(self.widget_main)
        self.drill_site.setGeometry(QtCore.QRect(270, 20, 120, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drill_site.setFont(font)
        self.drill_site.setObjectName(_fromUtf8("drill_site"))
        self.work_surf = QtGui.QComboBox(self.widget_main)
        self.work_surf.setGeometry(QtCore.QRect(120, 20, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.work_surf.setFont(font)
        self.work_surf.setObjectName(_fromUtf8("work_surf"))
        self.widget_title = QtGui.QWidget(high_drilling_design_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 681, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 591, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(640, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(high_drilling_design_dlg)
        QtCore.QMetaObject.connectSlotsByName(high_drilling_design_dlg)
        high_drilling_design_dlg.setTabOrder(self.work_surf, self.l1)
        high_drilling_design_dlg.setTabOrder(self.l1, self.l2)
        high_drilling_design_dlg.setTabOrder(self.l2, self.lg)
        high_drilling_design_dlg.setTabOrder(self.lg, self.abc)
        high_drilling_design_dlg.setTabOrder(self.abc, self.bcd)
        high_drilling_design_dlg.setTabOrder(self.bcd, self.drill_site)
        high_drilling_design_dlg.setTabOrder(self.drill_site, self.drill_pore)
        high_drilling_design_dlg.setTabOrder(self.drill_pore, self.save)

    def retranslateUi(self, high_drilling_design_dlg):
        high_drilling_design_dlg.setWindowTitle(_translate("high_drilling_design_dlg", "高位抽采钻场钻孔设计", None))
        item = self.abc.horizontalHeaderItem(0)
        item.setText(_translate("high_drilling_design_dlg", "序号", None))
        item = self.abc.horizontalHeaderItem(1)
        item.setText(_translate("high_drilling_design_dlg", "钻孔长度", None))
        item = self.abc.horizontalHeaderItem(2)
        item.setText(_translate("high_drilling_design_dlg", "钻孔角度", None))
        self.label_8.setText(_translate("high_drilling_design_dlg", "工作面列表", None))
        item = self.bcd.horizontalHeaderItem(0)
        item.setText(_translate("high_drilling_design_dlg", "序号", None))
        item = self.bcd.horizontalHeaderItem(1)
        item.setText(_translate("high_drilling_design_dlg", "钻孔长度", None))
        item = self.bcd.horizontalHeaderItem(2)
        item.setText(_translate("high_drilling_design_dlg", "钻孔角度", None))
        self.save.setText(_translate("high_drilling_design_dlg", "保 存", None))
        self.drill_pore.setText(_translate("high_drilling_design_dlg", "钻 孔 设 计", None))
        self.label.setText(_translate("high_drilling_design_dlg", "钻孔布设范围", None))
        self.label_14.setText(_translate("high_drilling_design_dlg", "BCD范围内钻孔参数", None))
        self.groupBox.setTitle(_translate("high_drilling_design_dlg", "钻场布设范围", None))
        self.label_12.setText(_translate("high_drilling_design_dlg", "各钻场的间距Lg", None))
        self.label_10.setText(_translate("high_drilling_design_dlg", "初次垮落循环步距L1", None))
        self.label_11.setText(_translate("high_drilling_design_dlg", "周期垮落循环步距L2", None))
        self.label_2.setText(_translate("high_drilling_design_dlg", "(m)", None))
        self.label_3.setText(_translate("high_drilling_design_dlg", "(m)", None))
        self.label_4.setText(_translate("high_drilling_design_dlg", "(m)", None))
        self.label_13.setText(_translate("high_drilling_design_dlg", "ABC范围内钻孔参数", None))
        self.drill_site.setText(_translate("high_drilling_design_dlg", "钻 场 设 计", None))
        self.lab_Ico.setText(_translate("high_drilling_design_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
