# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\high_drilling_site_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_high_drilling_site_dlg(object):
    def setupUi(self, high_drilling_site_dlg):
        high_drilling_site_dlg.setObjectName(_fromUtf8("high_drilling_site_dlg"))
        high_drilling_site_dlg.resize(491, 301)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        high_drilling_site_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(high_drilling_site_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 491, 271))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.label_10 = QtGui.QLabel(self.widget_main)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 351, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(190, 230, 91, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(450, 180, 54, 25))
        self.label.setObjectName(_fromUtf8("label"))
        self.hn = QtGui.QLineEdit(self.widget_main)
        self.hn.setGeometry(QtCore.QRect(380, 20, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hn.setFont(font)
        self.hn.setObjectName(_fromUtf8("hn"))
        self.q = QtGui.QLineEdit(self.widget_main)
        self.q.setGeometry(QtCore.QRect(230, 100, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.q.setFont(font)
        self.q.setObjectName(_fromUtf8("q"))
        self.label_12 = QtGui.QLabel(self.widget_main)
        self.label_12.setGeometry(QtCore.QRect(20, 100, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_3 = QtGui.QLabel(self.widget_main)
        self.label_3.setGeometry(QtCore.QRect(450, 20, 54, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_13 = QtGui.QLabel(self.widget_main)
        self.label_13.setGeometry(QtCore.QRect(20, 180, 351, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.hs = QtGui.QLineEdit(self.widget_main)
        self.hs.setGeometry(QtCore.QRect(380, 180, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hs.setFont(font)
        self.hs.setObjectName(_fromUtf8("hs"))
        self.rtn = QtGui.QLineEdit(self.widget_main)
        self.rtn.setGeometry(QtCore.QRect(230, 140, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rtn.setFont(font)
        self.rtn.setObjectName(_fromUtf8("rtn"))
        self.Rtn = QtGui.QLabel(self.widget_main)
        self.Rtn.setGeometry(QtCore.QRect(20, 140, 211, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Rtn.setFont(font)
        self.Rtn.setObjectName(_fromUtf8("Rtn"))
        self.theta = QtGui.QLineEdit(self.widget_main)
        self.theta.setGeometry(QtCore.QRect(380, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.theta.setFont(font)
        self.theta.setObjectName(_fromUtf8("theta"))
        self.label_11 = QtGui.QLabel(self.widget_main)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 321, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_2 = QtGui.QLabel(self.widget_main)
        self.label_2.setGeometry(QtCore.QRect(450, 60, 54, 25))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.widget_title = QtGui.QWidget(high_drilling_site_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 491, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 401, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(450, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(high_drilling_site_dlg)
        QtCore.QMetaObject.connectSlotsByName(high_drilling_site_dlg)
        high_drilling_site_dlg.setTabOrder(self.hn, self.theta)
        high_drilling_site_dlg.setTabOrder(self.theta, self.q)
        high_drilling_site_dlg.setTabOrder(self.q, self.rtn)
        high_drilling_site_dlg.setTabOrder(self.rtn, self.hs)
        high_drilling_site_dlg.setTabOrder(self.hs, self.save)

    def retranslateUi(self, high_drilling_site_dlg):
        high_drilling_site_dlg.setWindowTitle(_translate("high_drilling_site_dlg", "高位抽采钻场范围计算", None))
        self.label_10.setText(_translate("high_drilling_site_dlg", "垮落带范围内自上而下最上一个关键层n的厚度hn", None))
        self.save.setText(_translate("high_drilling_site_dlg", "保 存", None))
        self.label.setText(_translate("high_drilling_site_dlg", "(m)", None))
        self.label_12.setText(_translate("high_drilling_site_dlg", "第n个关键层的作用载荷q", None))
        self.label_3.setText(_translate("high_drilling_site_dlg", "(m)", None))
        self.label_13.setText(_translate("high_drilling_site_dlg", "自煤层到第n个关键层之间的岩层累计厚度∑hi", None))
        self.Rtn.setText(_translate("high_drilling_site_dlg", "第n个关键层的抗拉强度Rtn", None))
        self.label_11.setText(_translate("high_drilling_site_dlg", "∑h范围内顶板岩层断裂面与层面的夹角θ", None))
        self.label_2.setText(_translate("high_drilling_site_dlg", "(°)", None))
        self.lab_Ico.setText(_translate("high_drilling_site_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
