# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\high_drilling_tunnel_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_high_drilling_tunnel_dlg(object):
    def setupUi(self, high_drilling_tunnel_dlg):
        high_drilling_tunnel_dlg.setObjectName(_fromUtf8("high_drilling_tunnel_dlg"))
        high_drilling_tunnel_dlg.resize(380, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        high_drilling_tunnel_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(high_drilling_tunnel_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 381, 271))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.label_9 = QtGui.QLabel(self.widget_main)
        self.label_9.setGeometry(QtCore.QRect(20, 60, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_12 = QtGui.QLabel(self.widget_main)
        self.label_12.setGeometry(QtCore.QRect(20, 140, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_10 = QtGui.QLabel(self.widget_main)
        self.label_10.setGeometry(QtCore.QRect(180, 60, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(270, 180, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_11 = QtGui.QLabel(self.widget_main)
        self.label_11.setGeometry(QtCore.QRect(20, 100, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(190, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.hw = QtGui.QLineEdit(self.widget_main)
        self.hw.setGeometry(QtCore.QRect(70, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hw.setFont(font)
        self.hw.setObjectName(_fromUtf8("hw"))
        self.dip_angle = QtGui.QLineEdit(self.widget_main)
        self.dip_angle.setGeometry(QtCore.QRect(270, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dip_angle.setFont(font)
        self.dip_angle.setObjectName(_fromUtf8("dip_angle"))
        self.hz_max = QtGui.QLineEdit(self.widget_main)
        self.hz_max.setGeometry(QtCore.QRect(300, 180, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hz_max.setFont(font)
        self.hz_max.setObjectName(_fromUtf8("hz_max"))
        self.cacl = QtGui.QPushButton(self.widget_main)
        self.cacl.setGeometry(QtCore.QRect(100, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cacl.setFont(font)
        self.cacl.setObjectName(_fromUtf8("cacl"))
        self.label_8 = QtGui.QLabel(self.widget_main)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.hz_min = QtGui.QLineEdit(self.widget_main)
        self.hz_min.setGeometry(QtCore.QRect(200, 180, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hz_min.setFont(font)
        self.hz_min.setObjectName(_fromUtf8("hz_min"))
        self.work_surf = QtGui.QComboBox(self.widget_main)
        self.work_surf.setGeometry(QtCore.QRect(120, 20, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.work_surf.setFont(font)
        self.work_surf.setObjectName(_fromUtf8("work_surf"))
        self.label_2 = QtGui.QLabel(self.widget_main)
        self.label_2.setGeometry(QtCore.QRect(140, 60, 54, 25))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.czk = QtGui.QLineEdit(self.widget_main)
        self.czk.setGeometry(QtCore.QRect(220, 100, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.czk.setFont(font)
        self.czk.setObjectName(_fromUtf8("czk"))
        self.rock = QtGui.QComboBox(self.widget_main)
        self.rock.setGeometry(QtCore.QRect(110, 140, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rock.setFont(font)
        self.rock.setObjectName(_fromUtf8("rock"))
        self.rock.addItem(_fromUtf8(""))
        self.rock.addItem(_fromUtf8(""))
        self.rock.addItem(_fromUtf8(""))
        self.rock.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.widget_main)
        self.label_3.setGeometry(QtCore.QRect(340, 60, 54, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_13 = QtGui.QLabel(self.widget_main)
        self.label_13.setGeometry(QtCore.QRect(20, 180, 181, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.widget_title = QtGui.QWidget(high_drilling_tunnel_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 381, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 291, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(340, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(high_drilling_tunnel_dlg)
        QtCore.QMetaObject.connectSlotsByName(high_drilling_tunnel_dlg)

    def retranslateUi(self, high_drilling_tunnel_dlg):
        high_drilling_tunnel_dlg.setWindowTitle(_translate("high_drilling_tunnel_dlg", "高抽巷合理布设层位计算", None))
        self.label_9.setText(_translate("high_drilling_tunnel_dlg", "采高h", None))
        self.label_12.setText(_translate("high_drilling_tunnel_dlg", "岩性选择", None))
        self.label_10.setText(_translate("high_drilling_tunnel_dlg", "煤层倾角α", None))
        self.label.setText(_translate("high_drilling_tunnel_dlg", "至", None))
        self.label_11.setText(_translate("high_drilling_tunnel_dlg", "冒落岩石的平均碎胀系数k", None))
        self.save.setText(_translate("high_drilling_tunnel_dlg", "保 存", None))
        self.cacl.setText(_translate("high_drilling_tunnel_dlg", "计 算", None))
        self.label_8.setText(_translate("high_drilling_tunnel_dlg", "工作面列表", None))
        self.label_2.setText(_translate("high_drilling_tunnel_dlg", "(m)", None))
        self.rock.setItemText(0, _translate("high_drilling_tunnel_dlg", "坚硬岩石", None))
        self.rock.setItemText(1, _translate("high_drilling_tunnel_dlg", "中硬岩石", None))
        self.rock.setItemText(2, _translate("high_drilling_tunnel_dlg", "软弱岩石", None))
        self.rock.setItemText(3, _translate("high_drilling_tunnel_dlg", "极软弱岩石", None))
        self.label_3.setText(_translate("high_drilling_tunnel_dlg", "(°)", None))
        self.label_13.setText(_translate("high_drilling_tunnel_dlg", "高抽巷层位高度Hz范围", None))
        self.lab_Ico.setText(_translate("high_drilling_tunnel_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
