# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\mine_gas_reserves_predict_dlg2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mine_gas_reserves_predict_dlg2(object):
    def setupUi(self, mine_gas_reserves_predict_dlg2):
        mine_gas_reserves_predict_dlg2.setObjectName(_fromUtf8("mine_gas_reserves_predict_dlg2"))
        mine_gas_reserves_predict_dlg2.resize(320, 311)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mine_gas_reserves_predict_dlg2.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(mine_gas_reserves_predict_dlg2)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 321, 281))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.pump_k2 = QtGui.QLineEdit(self.widget_main)
        self.pump_k2.setGeometry(QtCore.QRect(240, 20, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pump_k2.setFont(font)
        self.pump_k2.setObjectName(_fromUtf8("pump_k2"))
        self.cacl = QtGui.QPushButton(self.widget_main)
        self.cacl.setGeometry(QtCore.QRect(80, 240, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cacl.setFont(font)
        self.cacl.setObjectName(_fromUtf8("cacl"))
        self.gas_wc2 = QtGui.QLineEdit(self.widget_main)
        self.gas_wc2.setGeometry(QtCore.QRect(240, 140, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gas_wc2.setFont(font)
        self.gas_wc2.setObjectName(_fromUtf8("gas_wc2"))
        self.label_6 = QtGui.QLabel(self.widget_main)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pump_k3 = QtGui.QLineEdit(self.widget_main)
        self.pump_k3.setGeometry(QtCore.QRect(240, 50, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pump_k3.setFont(font)
        self.pump_k3.setObjectName(_fromUtf8("pump_k3"))
        self.label_3 = QtGui.QLabel(self.widget_main)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(20, 20, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pump_k = QtGui.QLineEdit(self.widget_main)
        self.pump_k.setGeometry(QtCore.QRect(240, 170, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pump_k.setFont(font)
        self.pump_k.setObjectName(_fromUtf8("pump_k"))
        self.label_7 = QtGui.QLabel(self.widget_main)
        self.label_7.setGeometry(QtCore.QRect(20, 200, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pump_k4 = QtGui.QLineEdit(self.widget_main)
        self.pump_k4.setGeometry(QtCore.QRect(240, 80, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pump_k4.setFont(font)
        self.pump_k4.setObjectName(_fromUtf8("pump_k4"))
        self.label_4 = QtGui.QLabel(self.widget_main)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pump_k1 = QtGui.QLineEdit(self.widget_main)
        self.pump_k1.setGeometry(QtCore.QRect(240, 200, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pump_k1.setFont(font)
        self.pump_k1.setObjectName(_fromUtf8("pump_k1"))
        self.ok = QtGui.QPushButton(self.widget_main)
        self.ok.setGeometry(QtCore.QRect(160, 240, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ok.setFont(font)
        self.ok.setObjectName(_fromUtf8("ok"))
        self.gas_w0 = QtGui.QLineEdit(self.widget_main)
        self.gas_w0.setGeometry(QtCore.QRect(240, 110, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gas_w0.setFont(font)
        self.gas_w0.setObjectName(_fromUtf8("gas_w0"))
        self.label_5 = QtGui.QLabel(self.widget_main)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(self.widget_main)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.widget_title = QtGui.QWidget(mine_gas_reserves_predict_dlg2)
        self.widget_title.setGeometry(QtCore.QRect(-10, 0, 331, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(10, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 241, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(290, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(mine_gas_reserves_predict_dlg2)
        QtCore.QMetaObject.connectSlotsByName(mine_gas_reserves_predict_dlg2)

    def retranslateUi(self, mine_gas_reserves_predict_dlg2):
        mine_gas_reserves_predict_dlg2.setWindowTitle(_translate("mine_gas_reserves_predict_dlg2", "矿井可抽瓦斯量计算", None))
        self.cacl.setText(_translate("mine_gas_reserves_predict_dlg2", "计 算", None))
        self.label_6.setText(_translate("mine_gas_reserves_predict_dlg2", "可抽系数K", None))
        self.label_3.setText(_translate("mine_gas_reserves_predict_dlg2", "煤层瓦斯排放率K4", None))
        self.label.setText(_translate("mine_gas_reserves_predict_dlg2", "负压抽采作用系数K2", None))
        self.label_7.setText(_translate("mine_gas_reserves_predict_dlg2", "瓦斯涌出程度系数K1", None))
        self.label_4.setText(_translate("mine_gas_reserves_predict_dlg2", "煤层原始瓦斯含量My", None))
        self.ok.setText(_translate("mine_gas_reserves_predict_dlg2", "确 定", None))
        self.label_5.setText(_translate("mine_gas_reserves_predict_dlg2", "运到地面煤的残余瓦斯含量Mc", None))
        self.label_2.setText(_translate("mine_gas_reserves_predict_dlg2", "矿井瓦斯抽采率K3", None))
        self.lab_Ico.setText(_translate("mine_gas_reserves_predict_dlg2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
