# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\mine_gas_flow_predict_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mine_gas_flow_predict_dlg(object):
    def setupUi(self, mine_gas_flow_predict_dlg):
        mine_gas_flow_predict_dlg.setObjectName(_fromUtf8("mine_gas_flow_predict_dlg"))
        mine_gas_flow_predict_dlg.resize(371, 420)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mine_gas_flow_predict_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(mine_gas_flow_predict_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 371, 391))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.label_2 = QtGui.QLabel(self.widget_main)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 241, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 300, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.qr = QtGui.QLineEdit(self.groupBox_2)
        self.qr.setGeometry(QtCore.QRect(40, 30, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qr.setFont(font)
        self.qr.setObjectName(_fromUtf8("qr"))
        self.predic_cacl = QtGui.QPushButton(self.groupBox_2)
        self.predic_cacl.setGeometry(QtCore.QRect(140, 30, 25, 25))
        self.predic_cacl.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/udpate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.predic_cacl.setIcon(icon1)
        self.predic_cacl.setFlat(True)
        self.predic_cacl.setObjectName(_fromUtf8("predic_cacl"))
        self.k2_gas = QtGui.QLineEdit(self.widget_main)
        self.k2_gas.setGeometry(QtCore.QRect(260, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.k2_gas.setFont(font)
        self.k2_gas.setObjectName(_fromUtf8("k2_gas"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 331, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.assign = QtGui.QPushButton(self.groupBox)
        self.assign.setGeometry(QtCore.QRect(240, 70, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.assign.setFont(font)
        self.assign.setObjectName(_fromUtf8("assign"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.coal = QtGui.QComboBox(self.groupBox)
        self.coal.setGeometry(QtCore.QRect(110, 70, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.coal.setFont(font)
        self.coal.setObjectName(_fromUtf8("coal"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.work_area = QtGui.QComboBox(self.groupBox)
        self.work_area.setGeometry(QtCore.QRect(110, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.work_area.setFont(font)
        self.work_area.setObjectName(_fromUtf8("work_area"))
        self.work_area_qr = QtGui.QLineEdit(self.groupBox)
        self.work_area_qr.setGeometry(QtCore.QRect(160, 150, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.work_area_qr.setFont(font)
        self.work_area_qr.setObjectName(_fromUtf8("work_area_qr"))
        self.design_work_area = QtGui.QPushButton(self.groupBox)
        self.design_work_area.setGeometry(QtCore.QRect(240, 30, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.design_work_area.setFont(font)
        self.design_work_area.setObjectName(_fromUtf8("design_work_area"))
        self.work_area_a = QtGui.QLineEdit(self.groupBox)
        self.work_area_a.setGeometry(QtCore.QRect(160, 110, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.work_area_a.setFont(font)
        self.work_area_a.setObjectName(_fromUtf8("work_area_a"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 150, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.work_area_cacl = QtGui.QPushButton(self.groupBox)
        self.work_area_cacl.setGeometry(QtCore.QRect(230, 150, 25, 25))
        self.work_area_cacl.setText(_fromUtf8(""))
        self.work_area_cacl.setIcon(icon1)
        self.work_area_cacl.setFlat(True)
        self.work_area_cacl.setObjectName(_fromUtf8("work_area_cacl"))
        self.k1_gas = QtGui.QLineEdit(self.widget_main)
        self.k1_gas.setGeometry(QtCore.QRect(260, 20, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.k1_gas.setFont(font)
        self.k1_gas.setObjectName(_fromUtf8("k1_gas"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(260, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.k1_cacl = QtGui.QPushButton(self.widget_main)
        self.k1_cacl.setGeometry(QtCore.QRect(330, 20, 20, 25))
        self.k1_cacl.setText(_fromUtf8(""))
        self.k1_cacl.setIcon(icon1)
        self.k1_cacl.setFlat(True)
        self.k1_cacl.setObjectName(_fromUtf8("k1_cacl"))
        self.k2_cacl = QtGui.QPushButton(self.widget_main)
        self.k2_cacl.setGeometry(QtCore.QRect(330, 60, 20, 25))
        self.k2_cacl.setText(_fromUtf8(""))
        self.k2_cacl.setIcon(icon1)
        self.k2_cacl.setFlat(True)
        self.k2_cacl.setObjectName(_fromUtf8("k2_cacl"))
        self.widget_title = QtGui.QWidget(mine_gas_flow_predict_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 371, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 281, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(330, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(mine_gas_flow_predict_dlg)
        QtCore.QMetaObject.connectSlotsByName(mine_gas_flow_predict_dlg)

    def retranslateUi(self, mine_gas_flow_predict_dlg):
        mine_gas_flow_predict_dlg.setWindowTitle(_translate("mine_gas_flow_predict_dlg", "矿井相对瓦斯涌出量预测", None))
        self.label_2.setText(_translate("mine_gas_flow_predict_dlg", "已采采区采空区瓦斯涌出系数K\'\'", None))
        self.label.setText(_translate("mine_gas_flow_predict_dlg", "生产采区采空区瓦斯涌出系数K\'", None))
        self.groupBox_2.setTitle(_translate("mine_gas_flow_predict_dlg", "矿井相对瓦斯涌出量预测结果", None))
        self.groupBox.setTitle(_translate("mine_gas_flow_predict_dlg", "生产采区参数", None))
        self.assign.setText(_translate("mine_gas_flow_predict_dlg", "布 置", None))
        self.label_4.setText(_translate("mine_gas_flow_predict_dlg", "开采煤层", None))
        self.label_5.setText(_translate("mine_gas_flow_predict_dlg", "平均日产量", None))
        self.design_work_area.setText(_translate("mine_gas_flow_predict_dlg", "设 计", None))
        self.label_3.setText(_translate("mine_gas_flow_predict_dlg", "生产采区", None))
        self.label_6.setText(_translate("mine_gas_flow_predict_dlg", "相对瓦斯涌出量", None))
        self.save.setText(_translate("mine_gas_flow_predict_dlg", "保 存", None))
        self.lab_Ico.setText(_translate("mine_gas_flow_predict_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
