# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\mine_gas_flow_predict_design_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mine_gas_flow_predict_design_dlg(object):
    def setupUi(self, mine_gas_flow_predict_design_dlg):
        mine_gas_flow_predict_design_dlg.setObjectName(_fromUtf8("mine_gas_flow_predict_design_dlg"))
        mine_gas_flow_predict_design_dlg.resize(290, 349)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mine_gas_flow_predict_design_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(mine_gas_flow_predict_design_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 291, 321))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(110, 280, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 251, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.work_surf_a = QtGui.QLineEdit(self.groupBox)
        self.work_surf_a.setGeometry(QtCore.QRect(120, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.work_surf_a.setFont(font)
        self.work_surf_a.setObjectName(_fromUtf8("work_surf_a"))
        self.work_surf_qr = QtGui.QLineEdit(self.groupBox)
        self.work_surf_qr.setGeometry(QtCore.QRect(150, 90, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.work_surf_qr.setFont(font)
        self.work_surf_qr.setObjectName(_fromUtf8("work_surf_qr"))
        self.work_surf = QtGui.QComboBox(self.groupBox)
        self.work_surf.setGeometry(QtCore.QRect(120, 30, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.work_surf.setFont(font)
        self.work_surf.setObjectName(_fromUtf8("work_surf"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 160, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.drilling_surf_qa = QtGui.QLineEdit(self.groupBox_2)
        self.drilling_surf_qa.setGeometry(QtCore.QRect(150, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drilling_surf_qa.setFont(font)
        self.drilling_surf_qa.setObjectName(_fromUtf8("drilling_surf_qa"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.drilling_surf = QtGui.QComboBox(self.groupBox_2)
        self.drilling_surf.setGeometry(QtCore.QRect(120, 30, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drilling_surf.setFont(font)
        self.drilling_surf.setObjectName(_fromUtf8("drilling_surf"))
        self.widget_title = QtGui.QWidget(mine_gas_flow_predict_design_dlg)
        self.widget_title.setGeometry(QtCore.QRect(-10, 0, 301, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 211, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(260, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(mine_gas_flow_predict_design_dlg)
        QtCore.QMetaObject.connectSlotsByName(mine_gas_flow_predict_design_dlg)

    def retranslateUi(self, mine_gas_flow_predict_design_dlg):
        mine_gas_flow_predict_design_dlg.setWindowTitle(_translate("mine_gas_flow_predict_design_dlg", "工作面和掘进面瓦斯涌出量相关参数及设计", None))
        self.save.setText(_translate("mine_gas_flow_predict_design_dlg", "保 存", None))
        self.groupBox.setTitle(_translate("mine_gas_flow_predict_design_dlg", "工作面瓦斯参数", None))
        self.label_6.setText(_translate("mine_gas_flow_predict_design_dlg", "相对瓦斯涌出量", None))
        self.label_5.setText(_translate("mine_gas_flow_predict_design_dlg", "平均日产量", None))
        self.label_4.setText(_translate("mine_gas_flow_predict_design_dlg", "工作面列表", None))
        self.groupBox_2.setTitle(_translate("mine_gas_flow_predict_design_dlg", "掘进面瓦斯参数", None))
        self.label_8.setText(_translate("mine_gas_flow_predict_design_dlg", "掘进面列表", None))
        self.label_7.setText(_translate("mine_gas_flow_predict_design_dlg", "绝对瓦斯涌出量", None))
        self.lab_Ico.setText(_translate("mine_gas_flow_predict_design_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
