# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\pore_flow_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pore_flow_dlg(object):
    def setupUi(self, pore_flow_dlg):
        pore_flow_dlg.setObjectName(_fromUtf8("pore_flow_dlg"))
        pore_flow_dlg.resize(370, 460)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pore_flow_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(pore_flow_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 371, 431))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.mineName_label_17 = QtGui.QLabel(self.widget_main)
        self.mineName_label_17.setGeometry(QtCore.QRect(20, 300, 171, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_17.setFont(font)
        self.mineName_label_17.setObjectName(_fromUtf8("mineName_label_17"))
        self.k = QtGui.QLineEdit(self.widget_main)
        self.k.setGeometry(QtCore.QRect(210, 140, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.k.setFont(font)
        self.k.setObjectName(_fromUtf8("k"))
        self.delta_p_cacl = QtGui.QPushButton(self.widget_main)
        self.delta_p_cacl.setGeometry(QtCore.QRect(290, 220, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delta_p_cacl.setFont(font)
        self.delta_p_cacl.setObjectName(_fromUtf8("delta_p_cacl"))
        self.b_cacl = QtGui.QPushButton(self.widget_main)
        self.b_cacl.setGeometry(QtCore.QRect(290, 180, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.b_cacl.setFont(font)
        self.b_cacl.setObjectName(_fromUtf8("b_cacl"))
        self.q_hun = QtGui.QLineEdit(self.widget_main)
        self.q_hun.setGeometry(QtCore.QRect(210, 300, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.q_hun.setFont(font)
        self.q_hun.setObjectName(_fromUtf8("q_hun"))
        self.x = QtGui.QLineEdit(self.widget_main)
        self.x.setGeometry(QtCore.QRect(210, 100, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x.setFont(font)
        self.x.setObjectName(_fromUtf8("x"))
        self.k_cacl = QtGui.QPushButton(self.widget_main)
        self.k_cacl.setGeometry(QtCore.QRect(290, 140, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.k_cacl.setFont(font)
        self.k_cacl.setObjectName(_fromUtf8("k_cacl"))
        self.dh = QtGui.QLineEdit(self.widget_main)
        self.dh.setGeometry(QtCore.QRect(210, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dh.setFont(font)
        self.dh.setObjectName(_fromUtf8("dh"))
        self.cacl = QtGui.QPushButton(self.widget_main)
        self.cacl.setGeometry(QtCore.QRect(100, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cacl.setFont(font)
        self.cacl.setObjectName(_fromUtf8("cacl"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(200, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.mineName_label_11 = QtGui.QLabel(self.widget_main)
        self.mineName_label_11.setGeometry(QtCore.QRect(20, 60, 181, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_11.setFont(font)
        self.mineName_label_11.setObjectName(_fromUtf8("mineName_label_11"))
        self.mineName_label_13 = QtGui.QLabel(self.widget_main)
        self.mineName_label_13.setGeometry(QtCore.QRect(20, 140, 181, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_13.setFont(font)
        self.mineName_label_13.setObjectName(_fromUtf8("mineName_label_13"))
        self.mineName_label_10 = QtGui.QLabel(self.widget_main)
        self.mineName_label_10.setGeometry(QtCore.QRect(20, 20, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_10.setFont(font)
        self.mineName_label_10.setObjectName(_fromUtf8("mineName_label_10"))
        self.b = QtGui.QLineEdit(self.widget_main)
        self.b.setGeometry(QtCore.QRect(210, 180, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.b.setFont(font)
        self.b.setObjectName(_fromUtf8("b"))
        self.delta_p = QtGui.QLineEdit(self.widget_main)
        self.delta_p.setGeometry(QtCore.QRect(210, 220, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delta_p.setFont(font)
        self.delta_p.setObjectName(_fromUtf8("delta_p"))
        self.mineName_label_18 = QtGui.QLabel(self.widget_main)
        self.mineName_label_18.setGeometry(QtCore.QRect(20, 340, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_18.setFont(font)
        self.mineName_label_18.setObjectName(_fromUtf8("mineName_label_18"))
        self.delta_t = QtGui.QLineEdit(self.widget_main)
        self.delta_t.setGeometry(QtCore.QRect(210, 260, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delta_t.setFont(font)
        self.delta_t.setObjectName(_fromUtf8("delta_t"))
        self.mineName_label_12 = QtGui.QLabel(self.widget_main)
        self.mineName_label_12.setGeometry(QtCore.QRect(20, 100, 171, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_12.setFont(font)
        self.mineName_label_12.setObjectName(_fromUtf8("mineName_label_12"))
        self.t = QtGui.QLineEdit(self.widget_main)
        self.t.setGeometry(QtCore.QRect(210, 20, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t.setFont(font)
        self.t.setObjectName(_fromUtf8("t"))
        self.mineName_label_15 = QtGui.QLabel(self.widget_main)
        self.mineName_label_15.setGeometry(QtCore.QRect(20, 220, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_15.setFont(font)
        self.mineName_label_15.setObjectName(_fromUtf8("mineName_label_15"))
        self.mineName_label_14 = QtGui.QLabel(self.widget_main)
        self.mineName_label_14.setGeometry(QtCore.QRect(20, 180, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_14.setFont(font)
        self.mineName_label_14.setObjectName(_fromUtf8("mineName_label_14"))
        self.mineName_label_16 = QtGui.QLabel(self.widget_main)
        self.mineName_label_16.setGeometry(QtCore.QRect(20, 260, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mineName_label_16.setFont(font)
        self.mineName_label_16.setObjectName(_fromUtf8("mineName_label_16"))
        self.q_chun = QtGui.QLineEdit(self.widget_main)
        self.q_chun.setGeometry(QtCore.QRect(210, 340, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.q_chun.setFont(font)
        self.q_chun.setObjectName(_fromUtf8("q_chun"))
        self.delta_t_cacl = QtGui.QPushButton(self.widget_main)
        self.delta_t_cacl.setGeometry(QtCore.QRect(290, 260, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delta_t_cacl.setFont(font)
        self.delta_t_cacl.setObjectName(_fromUtf8("delta_t_cacl"))
        self.widget_title = QtGui.QWidget(pore_flow_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 371, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 281, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(330, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(pore_flow_dlg)
        QtCore.QMetaObject.connectSlotsByName(pore_flow_dlg)
        pore_flow_dlg.setTabOrder(self.t, self.dh)
        pore_flow_dlg.setTabOrder(self.dh, self.x)
        pore_flow_dlg.setTabOrder(self.x, self.k)
        pore_flow_dlg.setTabOrder(self.k, self.k_cacl)
        pore_flow_dlg.setTabOrder(self.k_cacl, self.b)
        pore_flow_dlg.setTabOrder(self.b, self.b_cacl)
        pore_flow_dlg.setTabOrder(self.b_cacl, self.delta_p)
        pore_flow_dlg.setTabOrder(self.delta_p, self.delta_p_cacl)
        pore_flow_dlg.setTabOrder(self.delta_p_cacl, self.delta_t)
        pore_flow_dlg.setTabOrder(self.delta_t, self.delta_t_cacl)
        pore_flow_dlg.setTabOrder(self.delta_t_cacl, self.q_hun)
        pore_flow_dlg.setTabOrder(self.q_hun, self.q_chun)
        pore_flow_dlg.setTabOrder(self.q_chun, self.cacl)
        pore_flow_dlg.setTabOrder(self.cacl, self.save)

    def retranslateUi(self, pore_flow_dlg):
        pore_flow_dlg.setWindowTitle(_translate("pore_flow_dlg", "孔板流量计算", None))
        self.mineName_label_17.setText(_translate("pore_flow_dlg", "<html><head/><body><p>抽放的瓦斯混合量Q<span style=\" vertical-align:sub;\">混</span></p></body></html>", None))
        self.delta_p_cacl.setText(_translate("pore_flow_dlg", "计 算", None))
        self.b_cacl.setText(_translate("pore_flow_dlg", "计 算", None))
        self.k_cacl.setText(_translate("pore_flow_dlg", "计 算", None))
        self.cacl.setText(_translate("pore_flow_dlg", "计 算", None))
        self.save.setText(_translate("pore_flow_dlg", "保 存", None))
        self.mineName_label_11.setText(_translate("pore_flow_dlg", "孔板前后端所测压差Δh", None))
        self.mineName_label_13.setText(_translate("pore_flow_dlg", "实际孔板流量特性系数K", None))
        self.mineName_label_10.setText(_translate("pore_flow_dlg", "瓦斯管内测点温度t", None))
        self.mineName_label_18.setText(_translate("pore_flow_dlg", "<html><head/><body><p>抽放的瓦斯纯量Q<span style=\" vertical-align:sub;\">纯</span></p></body></html>", None))
        self.mineName_label_12.setText(_translate("pore_flow_dlg", "混合气体中瓦斯浓度X", None))
        self.mineName_label_15.setText(_translate("pore_flow_dlg", "气压校正系数δp", None))
        self.mineName_label_14.setText(_translate("pore_flow_dlg", "瓦斯浓度校正系数b", None))
        self.mineName_label_16.setText(_translate("pore_flow_dlg", "温度校正系数δT", None))
        self.delta_t_cacl.setText(_translate("pore_flow_dlg", "计 算", None))
        self.lab_Ico.setText(_translate("pore_flow_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
