# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\sample_manage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_sample_manage(object):
    def setupUi(self, sample_manage):
        sample_manage.setObjectName(_fromUtf8("sample_manage"))
        sample_manage.setEnabled(True)
        sample_manage.resize(660, 651)
        sample_manage.setSizeIncrement(QtCore.QSize(490, 566))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sample_manage.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(sample_manage)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 661, 621))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 621, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.topo_geo = QtGui.QComboBox(self.groupBox)
        self.topo_geo.setGeometry(QtCore.QRect(130, 30, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.topo_geo.setFont(font)
        self.topo_geo.setObjectName(_fromUtf8("topo_geo"))
        self.topo_geo.addItem(_fromUtf8(""))
        self.topo_geo.addItem(_fromUtf8(""))
        self.topo_geo.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.hydr_geo = QtGui.QComboBox(self.groupBox)
        self.hydr_geo.setGeometry(QtCore.QRect(350, 30, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hydr_geo.setFont(font)
        self.hydr_geo.setObjectName(_fromUtf8("hydr_geo"))
        self.hydr_geo.addItem(_fromUtf8(""))
        self.hydr_geo.addItem(_fromUtf8(""))
        self.hydr_geo.addItem(_fromUtf8(""))
        self.hydr_geo.addItem(_fromUtf8(""))
        self.ground_cond = QtGui.QCheckBox(self.groupBox)
        self.ground_cond.setGeometry(QtCore.QRect(20, 70, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ground_cond.setFont(font)
        self.ground_cond.setObjectName(_fromUtf8("ground_cond"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 510, 621, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tech_mode = QtGui.QPushButton(self.groupBox_3)
        self.tech_mode.setGeometry(QtCore.QRect(140, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tech_mode.setFont(font)
        self.tech_mode.setObjectName(_fromUtf8("tech_mode"))
        self.technology = QtGui.QPushButton(self.groupBox_3)
        self.technology.setGeometry(QtCore.QRect(330, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.technology.setFont(font)
        self.technology.setObjectName(_fromUtf8("technology"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(500, 20, 75, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.region = QtGui.QComboBox(self.widget_main)
        self.region.setGeometry(QtCore.QRect(140, 20, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.region.setFont(font)
        self.region.setObjectName(_fromUtf8("region"))
        self.region.addItem(_fromUtf8(""))
        self.region.addItem(_fromUtf8(""))
        self.region.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 621, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.coal = QtGui.QComboBox(self.groupBox_2)
        self.coal.setGeometry(QtCore.QRect(100, 30, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.coal.setFont(font)
        self.coal.setObjectName(_fromUtf8("coal"))
        self.minable = QtGui.QCheckBox(self.groupBox_2)
        self.minable.setGeometry(QtCore.QRect(390, 30, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.minable.setFont(font)
        self.minable.setObjectName(_fromUtf8("minable"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(340, 70, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.thick = QtGui.QLineEdit(self.groupBox_2)
        self.thick.setGeometry(QtCore.QRect(410, 70, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.thick.setFont(font)
        self.thick.setObjectName(_fromUtf8("thick"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(480, 70, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(510, 70, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.f_value = QtGui.QLineEdit(self.groupBox_2)
        self.f_value.setGeometry(QtCore.QRect(540, 70, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.f_value.setFont(font)
        self.f_value.setObjectName(_fromUtf8("f_value"))
        self.dip_angle = QtGui.QLineEdit(self.groupBox_2)
        self.dip_angle.setGeometry(QtCore.QRect(90, 70, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dip_angle.setFont(font)
        self.dip_angle.setObjectName(_fromUtf8("dip_angle"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(160, 70, 41, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.hw = QtGui.QLineEdit(self.groupBox_2)
        self.hw.setGeometry(QtCore.QRect(240, 70, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hw.setFont(font)
        self.hw.setObjectName(_fromUtf8("hw"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(200, 70, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(310, 70, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.rank = QtGui.QComboBox(self.groupBox_2)
        self.rank.setGeometry(QtCore.QRect(260, 30, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rank.setFont(font)
        self.rank.setObjectName(_fromUtf8("rank"))
        self.rank.addItem(_fromUtf8(""))
        self.rank.addItem(_fromUtf8(""))
        self.rank.addItem(_fromUtf8(""))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(210, 30, 41, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.permeability_k = QtGui.QLineEdit(self.groupBox_2)
        self.permeability_k.setGeometry(QtCore.QRect(420, 110, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.permeability_k.setFont(font)
        self.permeability_k.setObjectName(_fromUtf8("permeability_k"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(360, 110, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.pressure = QtGui.QLineEdit(self.groupBox_2)
        self.pressure.setGeometry(QtCore.QRect(90, 110, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pressure.setFont(font)
        self.pressure.setObjectName(_fromUtf8("pressure"))
        self.gas_content = QtGui.QLineEdit(self.groupBox_2)
        self.gas_content.setGeometry(QtCore.QRect(260, 110, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gas_content.setFont(font)
        self.gas_content.setObjectName(_fromUtf8("gas_content"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(200, 110, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(20, 110, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(160, 110, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(330, 110, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.res_abundance = QtGui.QComboBox(self.groupBox_2)
        self.res_abundance.setGeometry(QtCore.QRect(150, 150, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.res_abundance.setFont(font)
        self.res_abundance.setObjectName(_fromUtf8("res_abundance"))
        self.res_abundance.addItem(_fromUtf8(""))
        self.res_abundance.addItem(_fromUtf8(""))
        self.res_abundance.addItem(_fromUtf8(""))
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(20, 150, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.complexity = QtGui.QComboBox(self.groupBox_2)
        self.complexity.setGeometry(QtCore.QRect(410, 150, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.complexity.setFont(font)
        self.complexity.setObjectName(_fromUtf8("complexity"))
        self.complexity.addItem(_fromUtf8(""))
        self.complexity.addItem(_fromUtf8(""))
        self.complexity.addItem(_fromUtf8(""))
        self.complexity.addItem(_fromUtf8(""))
        self.label_34 = QtGui.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(290, 150, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.mine_index = QtGui.QLineEdit(self.groupBox_2)
        self.mine_index.setGeometry(QtCore.QRect(120, 190, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mine_index.setFont(font)
        self.mine_index.setObjectName(_fromUtf8("mine_index"))
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(20, 190, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.mine_index_cacl = QtGui.QPushButton(self.groupBox_2)
        self.mine_index_cacl.setGeometry(QtCore.QRect(190, 190, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mine_index_cacl.setFont(font)
        self.mine_index_cacl.setObjectName(_fromUtf8("mine_index_cacl"))
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(270, 190, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.var_coeff_cacl = QtGui.QPushButton(self.groupBox_2)
        self.var_coeff_cacl.setGeometry(QtCore.QRect(460, 190, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.var_coeff_cacl.setFont(font)
        self.var_coeff_cacl.setObjectName(_fromUtf8("var_coeff_cacl"))
        self.var_coeff = QtGui.QLineEdit(self.groupBox_2)
        self.var_coeff.setGeometry(QtCore.QRect(390, 190, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.var_coeff.setFont(font)
        self.var_coeff.setObjectName(_fromUtf8("var_coeff"))
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(20, 230, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.czh_cacl = QtGui.QPushButton(self.groupBox_2)
        self.czh_cacl.setGeometry(QtCore.QRect(230, 230, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.czh_cacl.setFont(font)
        self.czh_cacl.setObjectName(_fromUtf8("czh_cacl"))
        self.stability_cacl = QtGui.QPushButton(self.groupBox_2)
        self.stability_cacl.setGeometry(QtCore.QRect(520, 230, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stability_cacl.setFont(font)
        self.stability_cacl.setObjectName(_fromUtf8("stability_cacl"))
        self.caving_zone_height = QtGui.QLineEdit(self.groupBox_2)
        self.caving_zone_height.setGeometry(QtCore.QRect(120, 230, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.caving_zone_height.setFont(font)
        self.caving_zone_height.setObjectName(_fromUtf8("caving_zone_height"))
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(310, 230, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.stability = QtGui.QComboBox(self.groupBox_2)
        self.stability.setGeometry(QtCore.QRect(410, 230, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stability.setFont(font)
        self.stability.setObjectName(_fromUtf8("stability"))
        self.stability.addItem(_fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.stability.addItem(_fromUtf8(""))
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(190, 230, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(20, 270, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.influence_factor = QtGui.QLineEdit(self.groupBox_2)
        self.influence_factor.setEnabled(True)
        self.influence_factor.setGeometry(QtCore.QRect(370, 270, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.influence_factor.setFont(font)
        self.influence_factor.setObjectName(_fromUtf8("influence_factor"))
        self.influence_factor_cacl = QtGui.QPushButton(self.groupBox_2)
        self.influence_factor_cacl.setGeometry(QtCore.QRect(460, 270, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.influence_factor_cacl.setFont(font)
        self.influence_factor_cacl.setObjectName(_fromUtf8("influence_factor_cacl"))
        self.layer_gap = QtGui.QLineEdit(self.groupBox_2)
        self.layer_gap.setGeometry(QtCore.QRect(160, 270, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layer_gap.setFont(font)
        self.layer_gap.setObjectName(_fromUtf8("layer_gap"))
        self.label_41 = QtGui.QLabel(self.groupBox_2)
        self.label_41.setGeometry(QtCore.QRect(270, 270, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.groupBox_2)
        self.label_42.setGeometry(QtCore.QRect(230, 270, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.widget_title = QtGui.QWidget(sample_manage)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 661, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 571, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(620, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(sample_manage)
        QtCore.QMetaObject.connectSlotsByName(sample_manage)

    def retranslateUi(self, sample_manage):
        sample_manage.setWindowTitle(_translate("sample_manage", "示范矿区技术库管理", None))
        self.groupBox.setTitle(_translate("sample_manage", "基础参数", None))
        self.label_3.setText(_translate("sample_manage", "地形地貌特征", None))
        self.topo_geo.setItemText(0, _translate("sample_manage", "简单", None))
        self.topo_geo.setItemText(1, _translate("sample_manage", "中等", None))
        self.topo_geo.setItemText(2, _translate("sample_manage", "复杂", None))
        self.label_4.setText(_translate("sample_manage", "水文地质条件", None))
        self.hydr_geo.setItemText(0, _translate("sample_manage", "简单", None))
        self.hydr_geo.setItemText(1, _translate("sample_manage", "中等", None))
        self.hydr_geo.setItemText(2, _translate("sample_manage", "复杂", None))
        self.hydr_geo.setItemText(3, _translate("sample_manage", "极复杂", None))
        self.ground_cond.setText(_translate("sample_manage", "是否具备地面井开发条件", None))
        self.groupBox_3.setTitle(_translate("sample_manage", "抽采技术参数", None))
        self.tech_mode.setText(_translate("sample_manage", "抽采技术模式参数", None))
        self.technology.setText(_translate("sample_manage", "推荐抽采技术参数", None))
        self.label.setText(_translate("sample_manage", "示范矿区技术库管理:", None))
        self.save.setText(_translate("sample_manage", "保存", None))
        self.region.setItemText(0, _translate("sample_manage", "晋城", None))
        self.region.setItemText(1, _translate("sample_manage", "两淮", None))
        self.region.setItemText(2, _translate("sample_manage", "松藻", None))
        self.groupBox_2.setTitle(_translate("sample_manage", "煤层参数", None))
        self.label_5.setText(_translate("sample_manage", "煤层列表", None))
        self.minable.setText(_translate("sample_manage", "可采煤层", None))
        self.label_6.setText(_translate("sample_manage", "煤层厚度", None))
        self.label_7.setText(_translate("sample_manage", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_8.setText(_translate("sample_manage", "<html><head/><body><p>f值</p></body></html>", None))
        self.label_9.setText(_translate("sample_manage", "<html><head/><body><p>(°)</p></body></html>", None))
        self.label_10.setText(_translate("sample_manage", "煤层倾角", None))
        self.label_11.setText(_translate("sample_manage", "采高", None))
        self.label_12.setText(_translate("sample_manage", "<html><head/><body><p>(m)</p></body></html>", None))
        self.rank.setItemText(0, _translate("sample_manage", "褐煤", None))
        self.rank.setItemText(1, _translate("sample_manage", "烟煤", None))
        self.rank.setItemText(2, _translate("sample_manage", "无烟煤", None))
        self.label_13.setText(_translate("sample_manage", "煤阶", None))
        self.label_14.setText(_translate("sample_manage", "<html><head/><body><p>渗透率</p></body></html>", None))
        self.label_16.setText(_translate("sample_manage", "气含量", None))
        self.label_17.setText(_translate("sample_manage", "储层压力", None))
        self.label_18.setText(_translate("sample_manage", "<html><head/><body><p>(Pa)</p></body></html>", None))
        self.label_15.setText(_translate("sample_manage", "<html><head/><body><p>(%)</p></body></html>", None))
        self.res_abundance.setItemText(0, _translate("sample_manage", "低(<3.0)", None))
        self.res_abundance.setItemText(1, _translate("sample_manage", "中(0.5~3.0)", None))
        self.res_abundance.setItemText(2, _translate("sample_manage", "高(>3.0)", None))
        self.label_33.setText(_translate("sample_manage", "煤层气储量丰度", None))
        self.complexity.setItemText(0, _translate("sample_manage", "简单", None))
        self.complexity.setItemText(1, _translate("sample_manage", "中等", None))
        self.complexity.setItemText(2, _translate("sample_manage", "复杂", None))
        self.complexity.setItemText(3, _translate("sample_manage", "极复杂", None))
        self.label_34.setText(_translate("sample_manage", "构造复杂程度", None))
        self.label_35.setText(_translate("sample_manage", "可采性指数", None))
        self.mine_index_cacl.setText(_translate("sample_manage", "计算", None))
        self.label_36.setText(_translate("sample_manage", "煤厚变异系数", None))
        self.var_coeff_cacl.setText(_translate("sample_manage", "计算", None))
        self.label_37.setText(_translate("sample_manage", "冒落带高度", None))
        self.czh_cacl.setText(_translate("sample_manage", "计算", None))
        self.stability_cacl.setText(_translate("sample_manage", "计算", None))
        self.label_38.setText(_translate("sample_manage", "煤层稳定性", None))
        self.stability.setItemText(0, _translate("sample_manage", "稳定煤层", None))
        self.stability.setItemText(1, _translate("sample_manage", "较稳定煤层", None))
        self.stability.setItemText(2, _translate("sample_manage", "不稳定煤层", None))
        self.stability.setItemText(3, _translate("sample_manage", "极不稳定煤层", None))
        self.label_39.setText(_translate("sample_manage", "<html><head/><body><p>(m)</p></body></html>", None))
        self.label_40.setText(_translate("sample_manage", "与上覆煤层层间距", None))
        self.influence_factor_cacl.setText(_translate("sample_manage", "计算", None))
        self.label_41.setText(_translate("sample_manage", "采动影响倍数", None))
        self.label_42.setText(_translate("sample_manage", "<html><head/><body><p>(m)</p></body></html>", None))
        self.lab_Ico.setText(_translate("sample_manage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
