# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\tech_mode_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tech_mode_dlg(object):
    def setupUi(self, tech_mode_dlg):
        tech_mode_dlg.setObjectName(_fromUtf8("tech_mode_dlg"))
        tech_mode_dlg.resize(350, 460)
        tech_mode_dlg.setSizeIncrement(QtCore.QSize(291, 362))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tech_mode_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(tech_mode_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 351, 431))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 311, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 30, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.c1_yes = QtGui.QRadioButton(self.groupBox_2)
        self.c1_yes.setGeometry(QtCore.QRect(20, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.c1_yes.setFont(font)
        self.c1_yes.setAutoRepeatDelay(300)
        self.c1_yes.setObjectName(_fromUtf8("c1_yes"))
        self.c1_no = QtGui.QRadioButton(self.groupBox_2)
        self.c1_no.setGeometry(QtCore.QRect(160, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.c1_no.setFont(font)
        self.c1_no.setChecked(True)
        self.c1_no.setObjectName(_fromUtf8("c1_no"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 110, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.c2_no = QtGui.QRadioButton(self.groupBox_3)
        self.c2_no.setGeometry(QtCore.QRect(160, 30, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.c2_no.setFont(font)
        self.c2_no.setChecked(True)
        self.c2_no.setObjectName(_fromUtf8("c2_no"))
        self.c2_yes = QtGui.QRadioButton(self.groupBox_3)
        self.c2_yes.setGeometry(QtCore.QRect(20, 30, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.c2_yes.setFont(font)
        self.c2_yes.setObjectName(_fromUtf8("c2_yes"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 190, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.c3_yes = QtGui.QRadioButton(self.groupBox_4)
        self.c3_yes.setGeometry(QtCore.QRect(20, 30, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.c3_yes.setFont(font)
        self.c3_yes.setObjectName(_fromUtf8("c3_yes"))
        self.c3_no = QtGui.QRadioButton(self.groupBox_4)
        self.c3_no.setGeometry(QtCore.QRect(160, 30, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.c3_no.setFont(font)
        self.c3_no.setChecked(True)
        self.c3_no.setObjectName(_fromUtf8("c3_no"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(130, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.region = QtGui.QGroupBox(self.widget_main)
        self.region.setGeometry(QtCore.QRect(20, 20, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.region.setFont(font)
        self.region.setObjectName(_fromUtf8("region"))
        self.tech_mode = QtGui.QComboBox(self.region)
        self.tech_mode.setGeometry(QtCore.QRect(30, 30, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tech_mode.setFont(font)
        self.tech_mode.setObjectName(_fromUtf8("tech_mode"))
        self.widget_title = QtGui.QWidget(tech_mode_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 351, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 261, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(310, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(tech_mode_dlg)
        QtCore.QMetaObject.connectSlotsByName(tech_mode_dlg)

    def retranslateUi(self, tech_mode_dlg):
        tech_mode_dlg.setWindowTitle(_translate("tech_mode_dlg", "煤层气（瓦斯）抽采技术模式参数", None))
        self.groupBox.setTitle(_translate("tech_mode_dlg", "适用条件", None))
        self.groupBox_2.setTitle(_translate("tech_mode_dlg", "渗透率", None))
        self.c1_yes.setText(_translate("tech_mode_dlg", "中高渗>5mD", None))
        self.c1_no.setText(_translate("tech_mode_dlg", "低渗<=5mD", None))
        self.groupBox_3.setTitle(_translate("tech_mode_dlg", "是否具体有保护层开采条件", None))
        self.c2_no.setText(_translate("tech_mode_dlg", "不具备", None))
        self.c2_yes.setText(_translate("tech_mode_dlg", "具备", None))
        self.groupBox_4.setTitle(_translate("tech_mode_dlg", "是否近距离煤层群", None))
        self.c3_yes.setText(_translate("tech_mode_dlg", "近距离煤层群", None))
        self.c3_no.setText(_translate("tech_mode_dlg", "中远距离煤层群", None))
        self.save.setText(_translate("tech_mode_dlg", "保存", None))
        self.region.setTitle(_translate("tech_mode_dlg", "xx矿区抽采技术模式", None))
        self.lab_Ico.setText(_translate("tech_mode_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
