# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\technology_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_technologyDlg(object):
    def setupUi(self, technologyDlg):
        technologyDlg.setObjectName(_fromUtf8("technologyDlg"))
        technologyDlg.resize(421, 352)
        technologyDlg.setSizeIncrement(QtCore.QSize(381, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        technologyDlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(technologyDlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 421, 321))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.video = QtGui.QLineEdit(self.widget_main)
        self.video.setGeometry(QtCore.QRect(100, 280, 181, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.video.setFont(font)
        self.video.setObjectName(_fromUtf8("video"))
        self.doc_select = QtGui.QPushButton(self.widget_main)
        self.doc_select.setGeometry(QtCore.QRect(290, 240, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doc_select.setFont(font)
        self.doc_select.setObjectName(_fromUtf8("doc_select"))
        self.region = QtGui.QLabel(self.widget_main)
        self.region.setGeometry(QtCore.QRect(30, 20, 181, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.region.setFont(font)
        self.region.setObjectName(_fromUtf8("region"))
        self.doc = QtGui.QLineEdit(self.widget_main)
        self.doc.setGeometry(QtCore.QRect(100, 240, 181, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doc.setFont(font)
        self.doc.setObjectName(_fromUtf8("doc"))
        self.doc_read = QtGui.QPushButton(self.widget_main)
        self.doc_read.setGeometry(QtCore.QRect(350, 240, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doc_read.setFont(font)
        self.doc_read.setObjectName(_fromUtf8("doc_read"))
        self.is_key = QtGui.QCheckBox(self.widget_main)
        self.is_key.setGeometry(QtCore.QRect(200, 20, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.is_key.setFont(font)
        self.is_key.setObjectName(_fromUtf8("is_key"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(20, 240, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(310, 20, 75, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.video_select = QtGui.QPushButton(self.widget_main)
        self.video_select.setGeometry(QtCore.QRect(290, 280, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.video_select.setFont(font)
        self.video_select.setObjectName(_fromUtf8("video_select"))
        self.video_play = QtGui.QPushButton(self.widget_main)
        self.video_play.setGeometry(QtCore.QRect(350, 280, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.video_play.setFont(font)
        self.video_play.setObjectName(_fromUtf8("video_play"))
        self.label_2 = QtGui.QLabel(self.widget_main)
        self.label_2.setGeometry(QtCore.QRect(20, 280, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.technology_list = QtGui.QListWidget(self.widget_main)
        self.technology_list.setGeometry(QtCore.QRect(20, 50, 381, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.technology_list.setFont(font)
        self.technology_list.setObjectName(_fromUtf8("technology_list"))
        item = QtGui.QListWidgetItem()
        self.technology_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.technology_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.technology_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.technology_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.technology_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.technology_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.technology_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.technology_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.technology_list.addItem(item)
        self.widget_title = QtGui.QWidget(technologyDlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 421, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 331, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(380, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(technologyDlg)
        QtCore.QMetaObject.connectSlotsByName(technologyDlg)

    def retranslateUi(self, technologyDlg):
        technologyDlg.setWindowTitle(_translate("technologyDlg", "推荐煤层气（瓦斯）抽采技术", None))
        self.doc_select.setText(_translate("technologyDlg", "选择", None))
        self.region.setText(_translate("technologyDlg", "xx矿区推荐抽采技术", None))
        self.doc_read.setText(_translate("technologyDlg", "查看", None))
        self.is_key.setText(_translate("technologyDlg", "关键技术", None))
        self.label.setText(_translate("technologyDlg", "技术文档", None))
        self.save.setText(_translate("technologyDlg", "保存", None))
        self.video_select.setText(_translate("technologyDlg", "选择", None))
        self.video_play.setText(_translate("technologyDlg", "播放", None))
        self.label_2.setText(_translate("technologyDlg", "技术视频", None))
        __sortingEnabled = self.technology_list.isSortingEnabled()
        self.technology_list.setSortingEnabled(False)
        item = self.technology_list.item(0)
        item.setText(_translate("technologyDlg", "专用瓦斯抽采巷穿层钻孔预抽煤层气技术", None))
        item = self.technology_list.item(1)
        item.setText(_translate("technologyDlg", "本煤层顺层钻孔抽采煤层气技术", None))
        item = self.technology_list.item(2)
        item.setText(_translate("technologyDlg", "专用瓦斯抽采巷穿层抽采卸压煤层气技术", None))
        item = self.technology_list.item(3)
        item.setText(_translate("technologyDlg", "石门揭煤穿层钻孔压裂高效抽采技术", None))
        item = self.technology_list.item(4)
        item.setText(_translate("technologyDlg", "采空区煤层气抽采技术", None))
        item = self.technology_list.item(5)
        item.setText(_translate("technologyDlg", "高压水力压裂增透抽采技术", None))
        item = self.technology_list.item(6)
        item.setText(_translate("technologyDlg", "松软突出煤层顺层孔连续套管护孔技术", None))
        item = self.technology_list.item(7)
        item.setText(_translate("technologyDlg", "高压水力压裂增透抽采技术", None))
        item = self.technology_list.item(8)
        item.setText(_translate("technologyDlg", "松软突出煤层顺层孔连续套管护孔技术", None))
        self.technology_list.setSortingEnabled(__sortingEnabled)
        self.lab_Ico.setText(_translate("technologyDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
