# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\tws_gas_flow_predict_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tws_gas_flow_predict_dlg(object):
    def setupUi(self, tws_gas_flow_predict_dlg):
        tws_gas_flow_predict_dlg.setObjectName(_fromUtf8("tws_gas_flow_predict_dlg"))
        tws_gas_flow_predict_dlg.resize(372, 501)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tws_gas_flow_predict_dlg.setWindowIcon(icon)
        self.drilling_surf = QtGui.QComboBox(tws_gas_flow_predict_dlg)
        self.drilling_surf.setGeometry(QtCore.QRect(80, 10, 281, 22))
        self.drilling_surf.setObjectName(_fromUtf8("drilling_surf"))
        self.label_8 = QtGui.QLabel(tws_gas_flow_predict_dlg)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.groupBox = QtGui.QGroupBox(tws_gas_flow_predict_dlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 351, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.wc_cacl = QtGui.QPushButton(self.groupBox)
        self.wc_cacl.setGeometry(QtCore.QRect(280, 80, 51, 21))
        self.wc_cacl.setObjectName(_fromUtf8("wc_cacl"))
        self.gas_wc2 = QtGui.QLineEdit(self.groupBox)
        self.gas_wc2.setGeometry(QtCore.QRect(190, 80, 61, 20))
        self.gas_wc2.setObjectName(_fromUtf8("gas_wc2"))
        self.gas_w0 = QtGui.QLineEdit(self.groupBox)
        self.gas_w0.setGeometry(QtCore.QRect(130, 50, 51, 20))
        self.gas_w0.setObjectName(_fromUtf8("gas_w0"))
        self.vr = QtGui.QLineEdit(self.groupBox)
        self.vr.setGeometry(QtCore.QRect(120, 20, 61, 20))
        self.vr.setObjectName(_fromUtf8("vr"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 111, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.rho = QtGui.QLineEdit(self.groupBox)
        self.rho.setGeometry(QtCore.QRect(270, 20, 61, 20))
        self.rho.setObjectName(_fromUtf8("rho"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(210, 20, 61, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 80, 171, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.groupBox_2 = QtGui.QGroupBox(tws_gas_flow_predict_dlg)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 351, 121))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 90, 81, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.l = QtGui.QLineEdit(self.groupBox_2)
        self.l.setGeometry(QtCore.QRect(110, 90, 41, 20))
        self.l.setObjectName(_fromUtf8("l"))
        self.v = QtGui.QLineEdit(self.groupBox_2)
        self.v.setGeometry(QtCore.QRect(130, 60, 51, 20))
        self.v.setObjectName(_fromUtf8("v"))
        self.d = QtGui.QLineEdit(self.groupBox_2)
        self.d.setGeometry(QtCore.QRect(210, 30, 61, 20))
        self.d.setObjectName(_fromUtf8("d"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.s = QtGui.QLineEdit(self.groupBox_2)
        self.s.setGeometry(QtCore.QRect(260, 90, 51, 20))
        self.s.setObjectName(_fromUtf8("s"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 191, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(160, 90, 91, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(20, 30, 191, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.groupBox_3 = QtGui.QGroupBox(tws_gas_flow_predict_dlg)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 310, 351, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(20, 50, 211, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.q0 = QtGui.QLineEdit(self.groupBox_3)
        self.q0.setGeometry(QtCore.QRect(230, 20, 61, 20))
        self.q0.setObjectName(_fromUtf8("q0"))
        self.q3 = QtGui.QLineEdit(self.groupBox_3)
        self.q3.setGeometry(QtCore.QRect(230, 50, 61, 20))
        self.q3.setObjectName(_fromUtf8("q3"))
        self.q4 = QtGui.QLineEdit(self.groupBox_3)
        self.q4.setGeometry(QtCore.QRect(230, 80, 61, 20))
        self.q4.setObjectName(_fromUtf8("q4"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 191, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(20, 110, 151, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.qa = QtGui.QLineEdit(self.groupBox_3)
        self.qa.setGeometry(QtCore.QRect(230, 110, 61, 20))
        self.qa.setObjectName(_fromUtf8("qa"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(20, 80, 181, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.cacl = QtGui.QPushButton(tws_gas_flow_predict_dlg)
        self.cacl.setGeometry(QtCore.QRect(70, 460, 71, 31))
        self.cacl.setObjectName(_fromUtf8("cacl"))
        self.save = QtGui.QPushButton(tws_gas_flow_predict_dlg)
        self.save.setGeometry(QtCore.QRect(230, 460, 81, 31))
        self.save.setObjectName(_fromUtf8("save"))

        self.retranslateUi(tws_gas_flow_predict_dlg)
        QtCore.QMetaObject.connectSlotsByName(tws_gas_flow_predict_dlg)
        tws_gas_flow_predict_dlg.setTabOrder(self.drilling_surf, self.vr)
        tws_gas_flow_predict_dlg.setTabOrder(self.vr, self.rho)
        tws_gas_flow_predict_dlg.setTabOrder(self.rho, self.gas_w0)
        tws_gas_flow_predict_dlg.setTabOrder(self.gas_w0, self.gas_wc2)
        tws_gas_flow_predict_dlg.setTabOrder(self.gas_wc2, self.wc_cacl)
        tws_gas_flow_predict_dlg.setTabOrder(self.wc_cacl, self.d)
        tws_gas_flow_predict_dlg.setTabOrder(self.d, self.v)
        tws_gas_flow_predict_dlg.setTabOrder(self.v, self.l)
        tws_gas_flow_predict_dlg.setTabOrder(self.l, self.s)
        tws_gas_flow_predict_dlg.setTabOrder(self.s, self.q0)
        tws_gas_flow_predict_dlg.setTabOrder(self.q0, self.q3)
        tws_gas_flow_predict_dlg.setTabOrder(self.q3, self.q4)
        tws_gas_flow_predict_dlg.setTabOrder(self.q4, self.qa)
        tws_gas_flow_predict_dlg.setTabOrder(self.qa, self.cacl)
        tws_gas_flow_predict_dlg.setTabOrder(self.cacl, self.save)

    def retranslateUi(self, tws_gas_flow_predict_dlg):
        tws_gas_flow_predict_dlg.setWindowTitle(_translate("tws_gas_flow_predict_dlg", "掘进工作面瓦斯涌出量", None))
        self.label_8.setText(_translate("tws_gas_flow_predict_dlg", "掘进面列表", None))
        self.groupBox.setTitle(_translate("tws_gas_flow_predict_dlg", "煤层参数", None))
        self.wc_cacl.setText(_translate("tws_gas_flow_predict_dlg", "计 算", None))
        self.label_7.setText(_translate("tws_gas_flow_predict_dlg", "煤层原始瓦斯含量W0", None))
        self.label_5.setText(_translate("tws_gas_flow_predict_dlg", "煤中挥发分含量Vr", None))
        self.label_6.setText(_translate("tws_gas_flow_predict_dlg", "煤的密度γ", None))
        self.label_9.setText(_translate("tws_gas_flow_predict_dlg", "运出矿井后煤的残存瓦斯含量Wc", None))
        self.groupBox_2.setTitle(_translate("tws_gas_flow_predict_dlg", "掘进面参数", None))
        self.label_13.setText(_translate("tws_gas_flow_predict_dlg", "掘进巷道长度L", None))
        self.label_10.setText(_translate("tws_gas_flow_predict_dlg", "巷道平均掘进速度V", None))
        self.label_11.setText(_translate("tws_gas_flow_predict_dlg", "巷道断面内暴露煤壁面的周边长度D", None))
        self.label_12.setText(_translate("tws_gas_flow_predict_dlg", "掘进巷道断面积S", None))
        self.label_14.setText(_translate("tws_gas_flow_predict_dlg", "巷道平均掘进速度V", None))
        self.label_15.setText(_translate("tws_gas_flow_predict_dlg", "巷道断面内暴露煤壁面的周边长度D", None))
        self.groupBox_3.setTitle(_translate("tws_gas_flow_predict_dlg", "瓦斯涌出量预测结果", None))
        self.label_19.setText(_translate("tws_gas_flow_predict_dlg", "掘进工作面巷道煤壁绝对瓦斯涌出量q3", None))
        self.label_17.setText(_translate("tws_gas_flow_predict_dlg", "掘进工作面巷道煤壁瓦斯涌出强度q0", None))
        self.label_18.setText(_translate("tws_gas_flow_predict_dlg", "掘进工作面绝对瓦斯涌出量", None))
        self.label_16.setText(_translate("tws_gas_flow_predict_dlg", "掘进工作面落煤绝对瓦斯涌出量q4", None))
        self.cacl.setText(_translate("tws_gas_flow_predict_dlg", "计 算", None))
        self.save.setText(_translate("tws_gas_flow_predict_dlg", "保 存", None))

import usecad_rc
