# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\tws_gas_flow_predict_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tws_gas_flow_predict_dlg(object):
    def setupUi(self, tws_gas_flow_predict_dlg):
        tws_gas_flow_predict_dlg.setObjectName(_fromUtf8("tws_gas_flow_predict_dlg"))
        tws_gas_flow_predict_dlg.resize(511, 589)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tws_gas_flow_predict_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(tws_gas_flow_predict_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 511, 561))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 471, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 90, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.l = QtGui.QLineEdit(self.groupBox_2)
        self.l.setGeometry(QtCore.QRect(140, 90, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l.setFont(font)
        self.l.setObjectName(_fromUtf8("l"))
        self.v = QtGui.QLineEdit(self.groupBox_2)
        self.v.setGeometry(QtCore.QRect(180, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.v.setFont(font)
        self.v.setObjectName(_fromUtf8("v"))
        self.d = QtGui.QLineEdit(self.groupBox_2)
        self.d.setGeometry(QtCore.QRect(290, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.d.setFont(font)
        self.d.setObjectName(_fromUtf8("d"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.s = QtGui.QLineEdit(self.groupBox_2)
        self.s.setGeometry(QtCore.QRect(380, 90, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.s.setFont(font)
        self.s.setObjectName(_fromUtf8("s"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(240, 90, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 60, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(20, 30, 271, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 471, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gas_wc2 = QtGui.QLineEdit(self.groupBox)
        self.gas_wc2.setGeometry(QtCore.QRect(260, 90, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gas_wc2.setFont(font)
        self.gas_wc2.setObjectName(_fromUtf8("gas_wc2"))
        self.gas_w0 = QtGui.QLineEdit(self.groupBox)
        self.gas_w0.setGeometry(QtCore.QRect(180, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gas_w0.setFont(font)
        self.gas_w0.setObjectName(_fromUtf8("gas_w0"))
        self.vr = QtGui.QLineEdit(self.groupBox)
        self.vr.setGeometry(QtCore.QRect(170, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vr.setFont(font)
        self.vr.setObjectName(_fromUtf8("vr"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.rho = QtGui.QLineEdit(self.groupBox)
        self.rho.setGeometry(QtCore.QRect(360, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rho.setFont(font)
        self.rho.setObjectName(_fromUtf8("rho"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(270, 30, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.wc_cacl = QtGui.QPushButton(self.groupBox)
        self.wc_cacl.setGeometry(QtCore.QRect(330, 90, 25, 25))
        self.wc_cacl.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/udpate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wc_cacl.setIcon(icon1)
        self.wc_cacl.setFlat(True)
        self.wc_cacl.setObjectName(_fromUtf8("wc_cacl"))
        self.cacl = QtGui.QPushButton(self.widget_main)
        self.cacl.setGeometry(QtCore.QRect(160, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cacl.setFont(font)
        self.cacl.setObjectName(_fromUtf8("cacl"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 330, 471, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(20, 60, 291, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.q0 = QtGui.QLineEdit(self.groupBox_3)
        self.q0.setGeometry(QtCore.QRect(310, 30, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.q0.setFont(font)
        self.q0.setObjectName(_fromUtf8("q0"))
        self.q3 = QtGui.QLineEdit(self.groupBox_3)
        self.q3.setGeometry(QtCore.QRect(310, 60, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.q3.setFont(font)
        self.q3.setObjectName(_fromUtf8("q3"))
        self.q4 = QtGui.QLineEdit(self.groupBox_3)
        self.q4.setGeometry(QtCore.QRect(310, 90, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.q4.setFont(font)
        self.q4.setObjectName(_fromUtf8("q4"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(20, 30, 281, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(20, 120, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.qa = QtGui.QLineEdit(self.groupBox_3)
        self.qa.setGeometry(QtCore.QRect(310, 120, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qa.setFont(font)
        self.qa.setObjectName(_fromUtf8("qa"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(20, 90, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.drilling_surf = QtGui.QComboBox(self.widget_main)
        self.drilling_surf.setGeometry(QtCore.QRect(120, 20, 281, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.drilling_surf.setFont(font)
        self.drilling_surf.setObjectName(_fromUtf8("drilling_surf"))
        self.label_8 = QtGui.QLabel(self.widget_main)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(260, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.widget_title = QtGui.QWidget(tws_gas_flow_predict_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 511, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 421, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(470, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(tws_gas_flow_predict_dlg)
        QtCore.QMetaObject.connectSlotsByName(tws_gas_flow_predict_dlg)
        tws_gas_flow_predict_dlg.setTabOrder(self.drilling_surf, self.vr)
        tws_gas_flow_predict_dlg.setTabOrder(self.vr, self.rho)
        tws_gas_flow_predict_dlg.setTabOrder(self.rho, self.gas_w0)
        tws_gas_flow_predict_dlg.setTabOrder(self.gas_w0, self.gas_wc2)
        tws_gas_flow_predict_dlg.setTabOrder(self.gas_wc2, self.d)
        tws_gas_flow_predict_dlg.setTabOrder(self.d, self.v)
        tws_gas_flow_predict_dlg.setTabOrder(self.v, self.l)
        tws_gas_flow_predict_dlg.setTabOrder(self.l, self.s)
        tws_gas_flow_predict_dlg.setTabOrder(self.s, self.q0)
        tws_gas_flow_predict_dlg.setTabOrder(self.q0, self.q3)
        tws_gas_flow_predict_dlg.setTabOrder(self.q3, self.q4)
        tws_gas_flow_predict_dlg.setTabOrder(self.q4, self.qa)
        tws_gas_flow_predict_dlg.setTabOrder(self.qa, self.cacl)
        tws_gas_flow_predict_dlg.setTabOrder(self.cacl, self.save)

    def retranslateUi(self, tws_gas_flow_predict_dlg):
        tws_gas_flow_predict_dlg.setWindowTitle(_translate("tws_gas_flow_predict_dlg", "掘进工作面瓦斯涌出量", None))
        self.groupBox_2.setTitle(_translate("tws_gas_flow_predict_dlg", "掘进面参数", None))
        self.label_13.setText(_translate("tws_gas_flow_predict_dlg", "掘进巷道长度L", None))
        self.label_10.setText(_translate("tws_gas_flow_predict_dlg", "巷道平均掘进速度V", None))
        self.label_11.setText(_translate("tws_gas_flow_predict_dlg", "巷道断面内暴露煤壁面的周边长度D", None))
        self.label_12.setText(_translate("tws_gas_flow_predict_dlg", "掘进巷道断面积S", None))
        self.label_14.setText(_translate("tws_gas_flow_predict_dlg", "巷道平均掘进速度V", None))
        self.label_15.setText(_translate("tws_gas_flow_predict_dlg", "巷道断面内暴露煤壁面的周边长度D", None))
        self.groupBox.setTitle(_translate("tws_gas_flow_predict_dlg", "煤层参数", None))
        self.label_7.setText(_translate("tws_gas_flow_predict_dlg", "煤层原始瓦斯含量W0", None))
        self.label_5.setText(_translate("tws_gas_flow_predict_dlg", "煤中挥发分含量Vr", None))
        self.label_6.setText(_translate("tws_gas_flow_predict_dlg", "煤的密度γ", None))
        self.label_9.setText(_translate("tws_gas_flow_predict_dlg", "运出矿井后煤的残存瓦斯含量Wc", None))
        self.cacl.setText(_translate("tws_gas_flow_predict_dlg", "计 算", None))
        self.groupBox_3.setTitle(_translate("tws_gas_flow_predict_dlg", "瓦斯涌出量预测结果", None))
        self.label_19.setText(_translate("tws_gas_flow_predict_dlg", "掘进工作面巷道煤壁绝对瓦斯涌出量q3", None))
        self.label_17.setText(_translate("tws_gas_flow_predict_dlg", "掘进工作面巷道煤壁瓦斯涌出强度q0", None))
        self.label_18.setText(_translate("tws_gas_flow_predict_dlg", "掘进工作面绝对瓦斯涌出量", None))
        self.label_16.setText(_translate("tws_gas_flow_predict_dlg", "掘进工作面落煤绝对瓦斯涌出量q4", None))
        self.label_8.setText(_translate("tws_gas_flow_predict_dlg", "掘进面列表", None))
        self.save.setText(_translate("tws_gas_flow_predict_dlg", "保 存", None))
        self.lab_Ico.setText(_translate("tws_gas_flow_predict_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
