# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\ws_gas_flow_predict_work_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ws_gas_flow_predict_work_dlg(object):
    def setupUi(self, ws_gas_flow_predict_work_dlg):
        ws_gas_flow_predict_work_dlg.setObjectName(_fromUtf8("ws_gas_flow_predict_work_dlg"))
        ws_gas_flow_predict_work_dlg.resize(420, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ws_gas_flow_predict_work_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(ws_gas_flow_predict_work_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 421, 331))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.label_7 = QtGui.QLabel(self.widget_main)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 211, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(20, 80, 411, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gas_wc2 = QtGui.QLineEdit(self.widget_main)
        self.gas_wc2.setGeometry(QtCore.QRect(260, 240, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gas_wc2.setFont(font)
        self.gas_wc2.setObjectName(_fromUtf8("gas_wc2"))
        self.label_8 = QtGui.QLabel(self.widget_main)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 231, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.k3_cacl = QtGui.QPushButton(self.widget_main)
        self.k3_cacl.setGeometry(QtCore.QRect(110, 110, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.k3_cacl.setFont(font)
        self.k3_cacl.setObjectName(_fromUtf8("k3_cacl"))
        self.kf = QtGui.QLineEdit(self.widget_main)
        self.kf.setGeometry(QtCore.QRect(20, 170, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kf.setFont(font)
        self.kf.setObjectName(_fromUtf8("kf"))
        self.label_2 = QtGui.QLabel(self.widget_main)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 391, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.k1 = QtGui.QLineEdit(self.widget_main)
        self.k1.setGeometry(QtCore.QRect(230, 20, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.k1.setFont(font)
        self.k1.setObjectName(_fromUtf8("k1"))
        self.gas_w0 = QtGui.QLineEdit(self.widget_main)
        self.gas_w0.setGeometry(QtCore.QRect(180, 210, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gas_w0.setFont(font)
        self.gas_w0.setObjectName(_fromUtf8("gas_w0"))
        self.label_6 = QtGui.QLabel(self.widget_main)
        self.label_6.setGeometry(QtCore.QRect(20, 210, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.k3 = QtGui.QLineEdit(self.widget_main)
        self.k3.setGeometry(QtCore.QRect(20, 110, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.k3.setFont(font)
        self.k3.setObjectName(_fromUtf8("k3"))
        self.kf_cacl = QtGui.QPushButton(self.widget_main)
        self.kf_cacl.setGeometry(QtCore.QRect(110, 170, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kf_cacl.setFont(font)
        self.kf_cacl.setObjectName(_fromUtf8("kf_cacl"))
        self.k2 = QtGui.QLineEdit(self.widget_main)
        self.k2.setGeometry(QtCore.QRect(230, 50, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.k2.setFont(font)
        self.k2.setObjectName(_fromUtf8("k2"))
        self.label_5 = QtGui.QLabel(self.widget_main)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 211, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(160, 280, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.widget_title = QtGui.QWidget(ws_gas_flow_predict_work_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 421, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 331, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(380, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(ws_gas_flow_predict_work_dlg)
        QtCore.QMetaObject.connectSlotsByName(ws_gas_flow_predict_work_dlg)

    def retranslateUi(self, ws_gas_flow_predict_work_dlg):
        ws_gas_flow_predict_work_dlg.setWindowTitle(_translate("ws_gas_flow_predict_work_dlg", "开采层相对瓦斯涌出量q1计算", None))
        self.label_7.setText(_translate("ws_gas_flow_predict_work_dlg", "工作面丢煤瓦斯涌出系数K2", None))
        self.label.setText(_translate("ws_gas_flow_predict_work_dlg", "采区内准备巷道预排瓦斯对开采层瓦斯涌出影响系数K3", None))
        self.label_8.setText(_translate("ws_gas_flow_predict_work_dlg", "运出矿井后煤的残存瓦斯含量Wc", None))
        self.k3_cacl.setText(_translate("ws_gas_flow_predict_work_dlg", "参 考 取 值", None))
        self.label_2.setText(_translate("ws_gas_flow_predict_work_dlg", "取决于煤层分层数量和顺序的分层瓦斯涌出系数Kf", None))
        self.label_6.setText(_translate("ws_gas_flow_predict_work_dlg", "煤层原始瓦斯含量W0", None))
        self.kf_cacl.setText(_translate("ws_gas_flow_predict_work_dlg", "参 考 取 值", None))
        self.label_5.setText(_translate("ws_gas_flow_predict_work_dlg", "工作面围岩瓦斯涌出系数K1", None))
        self.save.setText(_translate("ws_gas_flow_predict_work_dlg", "保 存", None))
        self.lab_Ico.setText(_translate("ws_gas_flow_predict_work_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
