# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles\ws_gas_flow_predict_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ws_gas_flow_predict_dlg(object):
    def setupUi(self, ws_gas_flow_predict_dlg):
        ws_gas_flow_predict_dlg.setObjectName(_fromUtf8("ws_gas_flow_predict_dlg"))
        ws_gas_flow_predict_dlg.resize(450, 380)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ws_gas_flow_predict_dlg.setWindowIcon(icon)
        self.widget_main = QtGui.QWidget(ws_gas_flow_predict_dlg)
        self.widget_main.setGeometry(QtCore.QRect(0, 30, 451, 351))
        self.widget_main.setObjectName(_fromUtf8("widget_main"))
        self.label_3 = QtGui.QLabel(self.widget_main)
        self.label_3.setGeometry(QtCore.QRect(410, 140, 54, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_9 = QtGui.QLabel(self.widget_main)
        self.label_9.setGeometry(QtCore.QRect(240, 170, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.save = QtGui.QPushButton(self.widget_main)
        self.save.setGeometry(QtCore.QRect(330, 280, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName(_fromUtf8("save"))
        self.label_8 = QtGui.QLabel(self.widget_main)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_11 = QtGui.QLabel(self.widget_main)
        self.label_11.setGeometry(QtCore.QRect(30, 200, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_6 = QtGui.QLabel(self.widget_main)
        self.label_6.setGeometry(QtCore.QRect(240, 140, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.hw = QtGui.QLineEdit(self.widget_main)
        self.hw.setGeometry(QtCore.QRect(340, 170, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hw.setFont(font)
        self.hw.setObjectName(_fromUtf8("hw"))
        self.thick = QtGui.QLineEdit(self.widget_main)
        self.thick.setGeometry(QtCore.QRect(130, 140, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.thick.setFont(font)
        self.thick.setObjectName(_fromUtf8("thick"))
        self.label_2 = QtGui.QLabel(self.widget_main)
        self.label_2.setGeometry(QtCore.QRect(200, 170, 54, 25))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(self.widget_main)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.qr1 = QtGui.QLineEdit(self.widget_main)
        self.qr1.setGeometry(QtCore.QRect(220, 200, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qr1.setFont(font)
        self.qr1.setObjectName(_fromUtf8("qr1"))
        self.groupBox = QtGui.QGroupBox(self.widget_main)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 411, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.method_thick = QtGui.QRadioButton(self.groupBox)
        self.method_thick.setGeometry(QtCore.QRect(240, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.method_thick.setFont(font)
        self.method_thick.setObjectName(_fromUtf8("method_thick"))
        self.method_thin = QtGui.QRadioButton(self.groupBox)
        self.method_thin.setGeometry(QtCore.QRect(20, 30, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.method_thin.setFont(font)
        self.method_thin.setChecked(True)
        self.method_thin.setObjectName(_fromUtf8("method_thin"))
        self.label_4 = QtGui.QLabel(self.widget_main)
        self.label_4.setGeometry(QtCore.QRect(410, 170, 54, 25))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.widget_main)
        self.label.setGeometry(QtCore.QRect(200, 140, 54, 25))
        self.label.setObjectName(_fromUtf8("label"))
        self.l1 = QtGui.QLineEdit(self.widget_main)
        self.l1.setGeometry(QtCore.QRect(130, 170, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1.setFont(font)
        self.l1.setObjectName(_fromUtf8("l1"))
        self.label_10 = QtGui.QLabel(self.widget_main)
        self.label_10.setGeometry(QtCore.QRect(30, 230, 191, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_7 = QtGui.QLabel(self.widget_main)
        self.label_7.setGeometry(QtCore.QRect(30, 170, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.qr2 = QtGui.QLineEdit(self.widget_main)
        self.qr2.setGeometry(QtCore.QRect(220, 230, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qr2.setFont(font)
        self.qr2.setObjectName(_fromUtf8("qr2"))
        self.work_surf = QtGui.QComboBox(self.widget_main)
        self.work_surf.setGeometry(QtCore.QRect(120, 20, 231, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.work_surf.setFont(font)
        self.work_surf.setObjectName(_fromUtf8("work_surf"))
        self.ws_thick = QtGui.QLineEdit(self.widget_main)
        self.ws_thick.setGeometry(QtCore.QRect(340, 140, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ws_thick.setFont(font)
        self.ws_thick.setObjectName(_fromUtf8("ws_thick"))
        self.groupBox_2 = QtGui.QGroupBox(self.widget_main)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 260, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.qr = QtGui.QLineEdit(self.groupBox_2)
        self.qr.setGeometry(QtCore.QRect(40, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qr.setFont(font)
        self.qr.setObjectName(_fromUtf8("qr"))
        self.qr_cacl = QtGui.QPushButton(self.groupBox_2)
        self.qr_cacl.setGeometry(QtCore.QRect(160, 30, 25, 25))
        self.qr_cacl.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/udpate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.qr_cacl.setIcon(icon1)
        self.qr_cacl.setFlat(True)
        self.qr_cacl.setObjectName(_fromUtf8("qr_cacl"))
        self.q1_cacl = QtGui.QPushButton(self.widget_main)
        self.q1_cacl.setGeometry(QtCore.QRect(290, 200, 25, 25))
        self.q1_cacl.setText(_fromUtf8(""))
        self.q1_cacl.setIcon(icon1)
        self.q1_cacl.setFlat(True)
        self.q1_cacl.setObjectName(_fromUtf8("q1_cacl"))
        self.q2_cacl = QtGui.QPushButton(self.widget_main)
        self.q2_cacl.setGeometry(QtCore.QRect(290, 230, 25, 25))
        self.q2_cacl.setText(_fromUtf8(""))
        self.q2_cacl.setIcon(icon1)
        self.q2_cacl.setFlat(True)
        self.q2_cacl.setObjectName(_fromUtf8("q2_cacl"))
        self.widget_title = QtGui.QWidget(ws_gas_flow_predict_dlg)
        self.widget_title.setGeometry(QtCore.QRect(0, 0, 451, 31))
        self.widget_title.setObjectName(_fromUtf8("widget_title"))
        self.lab_Ico = QtGui.QLabel(self.widget_title)
        self.lab_Ico.setGeometry(QtCore.QRect(0, 0, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Ico.sizePolicy().hasHeightForWidth())
        self.lab_Ico.setSizePolicy(sizePolicy)
        self.lab_Ico.setMinimumSize(QtCore.QSize(30, 0))
        self.lab_Ico.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Ico.setObjectName(_fromUtf8("lab_Ico"))
        self.lab_Title = QtGui.QLabel(self.widget_title)
        self.lab_Title.setGeometry(QtCore.QRect(40, 0, 361, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_Title.sizePolicy().hasHeightForWidth())
        self.lab_Title.setSizePolicy(sizePolicy)
        self.lab_Title.setStyleSheet(_fromUtf8("font: 10pt \"微软雅黑\";"))
        self.lab_Title.setText(_fromUtf8(""))
        self.lab_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_Title.setObjectName(_fromUtf8("lab_Title"))
        self.btnMenu_Close = QtGui.QPushButton(self.widget_title)
        self.btnMenu_Close.setGeometry(QtCore.QRect(410, 0, 41, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMenu_Close.setFont(font)
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText(_fromUtf8(""))
        self.btnMenu_Close.setIconSize(QtCore.QSize(32, 32))
        self.btnMenu_Close.setFlat(True)
        self.btnMenu_Close.setObjectName(_fromUtf8("btnMenu_Close"))

        self.retranslateUi(ws_gas_flow_predict_dlg)
        QtCore.QMetaObject.connectSlotsByName(ws_gas_flow_predict_dlg)

    def retranslateUi(self, ws_gas_flow_predict_dlg):
        ws_gas_flow_predict_dlg.setWindowTitle(_translate("ws_gas_flow_predict_dlg", "回采工作面瓦斯涌出量预测", None))
        self.label_3.setText(_translate("ws_gas_flow_predict_dlg", "(m)", None))
        self.label_9.setText(_translate("ws_gas_flow_predict_dlg", "工作面采高", None))
        self.save.setText(_translate("ws_gas_flow_predict_dlg", "保 存", None))
        self.label_8.setText(_translate("ws_gas_flow_predict_dlg", "工作面列表", None))
        self.label_11.setText(_translate("ws_gas_flow_predict_dlg", "开采层相对瓦斯涌出量q1", None))
        self.label_6.setText(_translate("ws_gas_flow_predict_dlg", "开采层厚度", None))
        self.label_2.setText(_translate("ws_gas_flow_predict_dlg", "(m)", None))
        self.label_5.setText(_translate("ws_gas_flow_predict_dlg", "煤层厚度", None))
        self.groupBox.setTitle(_translate("ws_gas_flow_predict_dlg", "开采分层情况", None))
        self.method_thick.setText(_translate("ws_gas_flow_predict_dlg", "分层开采(厚煤层)", None))
        self.method_thin.setText(_translate("ws_gas_flow_predict_dlg", "不分层开采(薄及中厚煤层)", None))
        self.label_4.setText(_translate("ws_gas_flow_predict_dlg", "(m)", None))
        self.label.setText(_translate("ws_gas_flow_predict_dlg", "(m)", None))
        self.label_10.setText(_translate("ws_gas_flow_predict_dlg", "邻近层相对瓦斯涌出量q2", None))
        self.label_7.setText(_translate("ws_gas_flow_predict_dlg", "工作面长度", None))
        self.groupBox_2.setTitle(_translate("ws_gas_flow_predict_dlg", "回采工作面相对瓦斯涌出量预测结果", None))
        self.lab_Ico.setText(_translate("ws_gas_flow_predict_dlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))

import usecad_rc
