
namespace cpp cbm
namespace php cbm
namespace py cbm

struct Account {
	1: i32 id,
	2: string username,
	3: string password,
	4: string comment,
}

struct AdjLayer {
	1: i32 id,
	2: i32 work_surf_id,
	3: i32 coal_id,
	4: string name,
	5: i32 num,
	6: double h,
	7: double hp,
	8: i32 in_cz,
	9: string comment,
}

struct Coal {
	1: i32 id,
	2: i32 mine_id,
	3: string name,
	4: i32 minable,
	5: double thick,
	6: double hw,
	7: double qa,
	8: double qr,
	9: double fore_qr,
	10: double fore_qa,
	11: i32 rank,
	12: i32 quality,
	13: double pressure,
	14: double gas_content,
	15: double f_value,
	16: i32 res_abundance,
	17: i32 complexity,
	18: double mine_index,
	19: double var_coeff,
	20: i32 stability,
	21: double dip_angle,
	22: double czh,
	23: double czk,
	24: double czw,
	25: double hw_sum,
	26: i32 rock,
	27: double hhh,
	28: double layer_gap,
	29: double influence_factor,
	30: double res_a1,
	31: double gas_x1,
	32: double res_a2,
	33: double gas_x2,
	34: double pump_wc,
	35: double pump_k,
	36: double pump_k2,
	37: double pump_k3,
	38: double pump_k4,
	39: double pump_k1,
	40: string pore_datas,
	41: double rho,
	42: double vr,
	43: double gas_w0,
	44: double gas_wc2,
	45: double gas_wc3,
	46: double gas_eta,
	47: double q0,
	48: i32 eval_method,
	49: double q0_alpha,
	50: double qt_alpha,
	51: double t_alpha,
	52: double q_lambda,
	53: double r_lambda,
	54: double p0_lambda,
	55: double p1_lambda,
	56: double t_lambda,
	57: double a_lambda,
	58: double p1_k,
	59: double p2_k,
	60: double gas_q,
	61: double core_height,
	62: double core_area,
	63: double gas_viscosity,
	64: double decay_alpha,
	65: double permeability_lambda,
	66: double permeability_k,
	67: i32 eval_difficult,
	68: string comment,
	69: double relative_layer_gap,
	70: i32 is_protectable,
}

struct Complexity {
	1: i32 id,
	2: string name,
	3: string details,
	4: string comment,
}

struct DesignDrillingSurfTechnology {
	1: i32 id,
	2: i32 design_technology_id,
	3: string name,
	4: string comment,
	5: double v_offset,
	6: double h_offset,
	7: double dp,
	8: double gp,
	9: double leading_dist,
	10: double gbp,
	11: double l_stripe,
	12: double ls,
	13: double ws,
	14: double hs,
	15: double gs,
	16: double wd,
	17: double hd,
	18: double l1,
	19: double l2,
	20: double w,
	21: double h,
	22: double top_side,
	23: double bottom_side,
	24: double left_side,
	25: double right_side,
	26: double lm,
	27: double close_length,
}

struct DesignEvalUnit {
	1: i32 id,
	2: i32 design_eval_unit_partition_id,
	3: string name,
	4: string comment,
	5: i32 num,
	6: double l,
	7: i32 t,
	8: double gap,
}

struct DesignEvalUnitPartition {
	1: i32 id,
	2: i32 work_surf_id,
	3: string name,
	4: string comment,
	5: double l2,
	6: double l1,
	7: double w,
	8: double h,
	9: double l,
	10: double r,
	11: double t,
	12: double v,
}

struct DesignGoafPore {
	1: i32 id,
	2: i32 design_goaf_technology_id,
	3: string name,
	4: double h_offset,
	5: double v_offset,
	6: string comment,
}

struct DesignGoafTechnology {
	1: i32 id,
	2: i32 design_technology_id,
	3: string name,
	4: string comment,
	5: double pore_stubble,
	6: double dp,
	7: double gs,
	8: double ls,
	9: double ws,
	10: double hs,
	11: double gp,
	12: i32 pore_num,
	13: double top_dist,
	14: string h_offset,
	15: string y_offset,
	16: double l1,
	17: double l2,
	18: double w,
	19: double h,
	20: double close_length,
}

struct DesignPore {
	1: i32 id,
	2: i32 design_eval_unit_id,
	3: i32 design_site_id,
	4: string name,
	5: double d,
	6: double x1,
	7: double y1,
	8: double z1,
	9: double x2,
	10: double y2,
	11: double z2,
	12: double length,
	13: double angle1,
	14: double angle2,
	15: string comment,
	16: i32 t,
}

struct DesignSite {
	1: i32 id,
	2: i32 design_technology_id,
	3: string name,
	4: double w,
	5: double h,
	6: double x,
	7: double y,
	8: double z,
	9: string comment,
}

struct DesignTechnology {
	1: i32 id,
	2: i32 coal_id,
	3: string name,
	4: i32 region,
	5: string comment,
}

struct DesignTunnelControlPoint {
	1: i32 id,
	2: i32 design_eval_unit_partition_id,
	3: string name,
	4: string comment,
	5: double x,
	6: double y,
	7: double z,
}

struct DesignWorkSurfControlPoint {
	1: i32 id,
	2: i32 design_eval_unit_partition_id,
	3: string name,
	4: string comment,
	5: double x,
	6: double y,
	7: double z,
}

struct DesignWorkSurfTechnology {
	1: i32 id,
	2: i32 design_technology_id,
	3: string name,
	4: string comment,
	5: double top_side,
	6: double bottom_side,
	7: double right_side,
	8: double l1,
	9: double w,
	10: double h,
	11: double l2,
	12: double left_side,
	13: double v_offset,
	14: double h_offset,
	15: double p_offset,
	16: double wd,
	17: double hd,
	18: double lm,
	19: double ws,
	20: double ls,
	21: double gs,
	22: double hs,
	23: double dp,
	24: double gp,
	25: i32 single_rock_tunnel,
	26: double d_offset,
	27: double pore_stubble,
	28: double pore_angle,
	29: i32 pore_type,
	30: double close_length,
}

struct DrillingRadiusParam {
	1: i32 id,
	2: i32 coal_id,
	3: string name,
	4: double r,
	5: double l,
	6: double k1,
	7: double rho,
	8: double q0,
	9: double a,
	10: double t,
	11: double qm,
	12: double qsum,
	13: double eta,
	14: double r0,
	15: double p0,
	16: double r1,
	17: double p1,
}

struct DrillingSurf {
	1: i32 id,
	2: i32 work_area_id,
	3: i32 tunnel_id,
	4: string name,
	5: double qr,
	6: double qa,
	7: double fore_qr,
	8: double fore_qa,
	9: double q4,
	10: string comment,
}

struct HighDrillingPore {
	1: i32 id,
	2: i32 high_drilling_pore_param_id,
	3: i32 num,
	4: double length,
	5: double angle,
	6: i32 pore_type,
	7: string comment,
}

struct HighDrillingPoreParam {
	1: i32 id,
	2: i32 work_surf_id,
	3: string name,
	4: double lk,
	5: double lc,
	6: double lw,
	7: i32 n1,
	8: i32 n2,
	9: double beta,
	10: double ld,
	11: string comment,
}

struct HighDrillingSiteParam {
	1: i32 id,
	2: i32 work_surf_id,
	3: string name,
	4: double l1,
	5: double l2,
	6: double lg,
	7: double hn,
	8: double theta,
	9: double q,
	10: double rtn,
	11: double hs,
	12: string comment,
}

struct HighDrillingTunnel {
	1: i32 id,
	2: i32 work_surf_id,
	3: string name,
	4: double k,
	5: i32 rock,
	6: double hz_min,
	7: double hz_max,
	8: string comment,
}

struct HydrGeo {
	1: i32 id,
	2: string name,
	3: i32 x1,
	4: i32 x2,
	5: i32 x3,
	6: double x4,
	7: double x5,
	8: double x6,
	9: double x7,
	10: string x8,
}

struct Mine {
	1: i32 id,
	2: i32 tech_mode_id,
	3: i32 mine_region_id,
	4: i32 account_id,
	5: string name,
	6: string province,
	7: string city,
	8: double capacity,
	9: i32 topo_geo,
	10: i32 hydr_geo,
	11: i32 ground_condition,
	12: double qr,
	13: double qa,
	14: double fore_qr,
	15: double fore_qa,
	16: double gas_k1,
	17: double gas_k2,
	18: string stereo_schem_diagram,
	19: double rock_gas_k2,
	20: double reserve_w1,
	21: double reserve_w2,
	22: double reserve_w3,
	23: double gas_w0,
	24: double gas_wc2,
	25: double pump_k2,
	26: double pump_k3,
	27: double pump_k4,
	28: double pump_k1,
	29: double pump_k,
	30: double pump_wc,
	31: double reserve_gas,
	32: string comment,
	33: i32 protect_layer_condition,
}

struct MineBase {
	1: i32 id,
	2: string name,
	3: string comment,
}

struct MineRegion {
	1: i32 id,
	2: i32 mine_base_id,
	3: string name,
	4: string comment,
}

struct PoreFlow {
	1: i32 id,
	2: string name,
	3: double t,
	4: double a0,
	5: double d,
	6: double d1,
	7: double m,
	8: double k,
	9: double delta_t,
	10: double x,
	11: double p_test,
	12: double p_cur,
	13: double b,
	14: double pt,
	15: double delta_p,
	16: double dh,
	17: double q_hun,
	18: double q_chun,
}

struct PoreSize {
	1: i32 id,
	2: string name,
	3: double q,
	4: double v,
	5: double d,
	6: double p,
	7: double sigma,
	8: double delta,
	9: string comment,
}

struct ResAbundance {
	1: i32 id,
	2: string name,
	3: double min_abundance,
	4: double max_abundance,
}

struct Rock {
	1: i32 id,
	2: string name,
	3: double a,
	4: double b,
	5: double c,
	6: string comment,
}

struct SysInfo {
	1: i32 id,
	2: i32 account_id,
	3: string last_login_time,
	4: string comment,
}

struct TechMode {
	1: i32 id,
	2: i32 mine_region_id,
	3: string name,
	4: i32 mode_type,
	5: i32 c1,
	6: i32 c2,
	7: i32 c3,
	8: string comment,
}

struct Technology {
	1: i32 id,
	2: i32 mine_region_id,
	3: string name,
	4: i32 iskey,
	5: string doc,
	6: string video,
	7: string comment,
}

struct TopoGeo {
	1: i32 id,
	2: string name,
	3: string feature,
	4: string comment,
}

struct Tunnel {
	1: i32 id,
	2: string name,
	3: double b,
	4: double h,
	5: double l,
	6: double s,
	7: double d,
	8: double wh,
	9: double v,
	10: double q3,
	11: double q0,
	12: string comment,
	13: i32 tunnel_type,
	14: double top_side,
	15: double bottom_side,
	16: double left_side,
	17: double right_side,
	18: double x1,
	19: double y1,
	20: double z1,
	21: double x2,
	22: double y2,
	23: double z2,
}

struct WorkArea {
	1: i32 id,
	2: i32 coal_id,
	3: string name,
	4: i32 mode,
	5: double a,
	6: double qr,
	7: double qa,
	8: double fore_qr,
	9: double fore_qa,
	10: string comment,
}

struct WorkSurf {
	1: i32 id,
	2: i32 work_area_id,
	3: i32 tunnel_id,
	4: string name,
	5: double a,
	6: double qr,
	7: double qa,
	8: double fore_qr,
	9: double fore_qa,
	10: double l1,
	11: double l2,
	12: i32 layerable,
	13: double k1,
	14: double k2,
	15: double k3,
	16: double kf,
	17: i32 method,
	18: double last_t,
	19: double qr1,
	20: double qr2,
	21: string comment,
}

/*
DrillingSurfGasFlow函数返回多个参数
因此再定义一个struct作为返回参数
*/
struct DrillingSurfGasFlowResult {
	1:double q0,
	2:double q3,
	3:double q4,
	4:double qa
}
service CbmService {

//service SQLService {
	//Account 类型的CRUD操作
	i32 AddAccount(1:Account account),
	bool DeleteAccount(1:i32 id),
	bool UpdateAccount(1:Account account),
	Account GetAccountById(1:i32 id),
	Account GetAccountByForeignKey(1:string fkey, 2:i32 id),
	i32 GetAccountIdByForeignKey(1:string fkey, 2:i32 id),
	list<Account> GetAccountList(),
	list<i32> GetAccountIds(),
	list<string> GetAccountNames(),
	void AddMoreAccount(1:list<Account> objs),
	void DeleteMoreAccount(1:list<i32> obj_ids),
	Account GetAccountByFields(1:map<string, string> fields),
	Account GetAccountByField1(1:string field, 2:string value),
	Account GetAccountByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Account> GetAccountListByFields(1:map<string, string> fields),
	list<Account> GetAccountListByField1(1:string field, 2:string value),
	list<Account> GetAccountListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetAccountIdByFields(1:map<string, string> fields),
	i32 GetAccountIdByField1(1:string field, 2:string value),
	i32 GetAccountIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetAccountIdListByFields(1:map<string, string> fields),
	list<i32> GetAccountIdListByField1(1:string field, 2:string value),
	list<i32> GetAccountIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Account> GetAccountListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetAccountIdListByForeignKey(1:string fkey, 2:i32 id),

	//AdjLayer 类型的CRUD操作
	i32 AddAdjLayer(1:AdjLayer adj_layer),
	bool DeleteAdjLayer(1:i32 id),
	bool UpdateAdjLayer(1:AdjLayer adj_layer),
	AdjLayer GetAdjLayerById(1:i32 id),
	AdjLayer GetAdjLayerByForeignKey(1:string fkey, 2:i32 id),
	i32 GetAdjLayerIdByForeignKey(1:string fkey, 2:i32 id),
	list<AdjLayer> GetAdjLayerList(),
	list<i32> GetAdjLayerIds(),
	list<string> GetAdjLayerNames(),
	void AddMoreAdjLayer(1:list<AdjLayer> objs),
	void DeleteMoreAdjLayer(1:list<i32> obj_ids),
	AdjLayer GetAdjLayerByFields(1:map<string, string> fields),
	AdjLayer GetAdjLayerByField1(1:string field, 2:string value),
	AdjLayer GetAdjLayerByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<AdjLayer> GetAdjLayerListByFields(1:map<string, string> fields),
	list<AdjLayer> GetAdjLayerListByField1(1:string field, 2:string value),
	list<AdjLayer> GetAdjLayerListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetAdjLayerIdByFields(1:map<string, string> fields),
	i32 GetAdjLayerIdByField1(1:string field, 2:string value),
	i32 GetAdjLayerIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetAdjLayerIdListByFields(1:map<string, string> fields),
	list<i32> GetAdjLayerIdListByField1(1:string field, 2:string value),
	list<i32> GetAdjLayerIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<AdjLayer> GetAdjLayerListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetAdjLayerIdListByForeignKey(1:string fkey, 2:i32 id),

	//Coal 类型的CRUD操作
	i32 AddCoal(1:Coal coal),
	bool DeleteCoal(1:i32 id),
	bool UpdateCoal(1:Coal coal),
	Coal GetCoalById(1:i32 id),
	Coal GetCoalByForeignKey(1:string fkey, 2:i32 id),
	i32 GetCoalIdByForeignKey(1:string fkey, 2:i32 id),
	list<Coal> GetCoalList(),
	list<i32> GetCoalIds(),
	list<string> GetCoalNames(),
	void AddMoreCoal(1:list<Coal> objs),
	void DeleteMoreCoal(1:list<i32> obj_ids),
	Coal GetCoalByFields(1:map<string, string> fields),
	Coal GetCoalByField1(1:string field, 2:string value),
	Coal GetCoalByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Coal> GetCoalListByFields(1:map<string, string> fields),
	list<Coal> GetCoalListByField1(1:string field, 2:string value),
	list<Coal> GetCoalListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetCoalIdByFields(1:map<string, string> fields),
	i32 GetCoalIdByField1(1:string field, 2:string value),
	i32 GetCoalIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetCoalIdListByFields(1:map<string, string> fields),
	list<i32> GetCoalIdListByField1(1:string field, 2:string value),
	list<i32> GetCoalIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Coal> GetCoalListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetCoalIdListByForeignKey(1:string fkey, 2:i32 id),

	//Complexity 类型的CRUD操作
	i32 AddComplexity(1:Complexity complexity),
	bool DeleteComplexity(1:i32 id),
	bool UpdateComplexity(1:Complexity complexity),
	Complexity GetComplexityById(1:i32 id),
	Complexity GetComplexityByForeignKey(1:string fkey, 2:i32 id),
	i32 GetComplexityIdByForeignKey(1:string fkey, 2:i32 id),
	list<Complexity> GetComplexityList(),
	list<i32> GetComplexityIds(),
	list<string> GetComplexityNames(),
	void AddMoreComplexity(1:list<Complexity> objs),
	void DeleteMoreComplexity(1:list<i32> obj_ids),
	Complexity GetComplexityByFields(1:map<string, string> fields),
	Complexity GetComplexityByField1(1:string field, 2:string value),
	Complexity GetComplexityByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Complexity> GetComplexityListByFields(1:map<string, string> fields),
	list<Complexity> GetComplexityListByField1(1:string field, 2:string value),
	list<Complexity> GetComplexityListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetComplexityIdByFields(1:map<string, string> fields),
	i32 GetComplexityIdByField1(1:string field, 2:string value),
	i32 GetComplexityIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetComplexityIdListByFields(1:map<string, string> fields),
	list<i32> GetComplexityIdListByField1(1:string field, 2:string value),
	list<i32> GetComplexityIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Complexity> GetComplexityListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetComplexityIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignDrillingSurfTechnology 类型的CRUD操作
	i32 AddDesignDrillingSurfTechnology(1:DesignDrillingSurfTechnology design_drilling_surf_technology),
	bool DeleteDesignDrillingSurfTechnology(1:i32 id),
	bool UpdateDesignDrillingSurfTechnology(1:DesignDrillingSurfTechnology design_drilling_surf_technology),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyById(1:i32 id),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignDrillingSurfTechnologyIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignDrillingSurfTechnology> GetDesignDrillingSurfTechnologyList(),
	list<i32> GetDesignDrillingSurfTechnologyIds(),
	list<string> GetDesignDrillingSurfTechnologyNames(),
	void AddMoreDesignDrillingSurfTechnology(1:list<DesignDrillingSurfTechnology> objs),
	void DeleteMoreDesignDrillingSurfTechnology(1:list<i32> obj_ids),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyByFields(1:map<string, string> fields),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyByField1(1:string field, 2:string value),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignDrillingSurfTechnology> GetDesignDrillingSurfTechnologyListByFields(1:map<string, string> fields),
	list<DesignDrillingSurfTechnology> GetDesignDrillingSurfTechnologyListByField1(1:string field, 2:string value),
	list<DesignDrillingSurfTechnology> GetDesignDrillingSurfTechnologyListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignDrillingSurfTechnologyIdByFields(1:map<string, string> fields),
	i32 GetDesignDrillingSurfTechnologyIdByField1(1:string field, 2:string value),
	i32 GetDesignDrillingSurfTechnologyIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignDrillingSurfTechnologyIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignDrillingSurfTechnologyIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignDrillingSurfTechnologyIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignDrillingSurfTechnology> GetDesignDrillingSurfTechnologyListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignDrillingSurfTechnologyIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignEvalUnit 类型的CRUD操作
	i32 AddDesignEvalUnit(1:DesignEvalUnit design_eval_unit),
	bool DeleteDesignEvalUnit(1:i32 id),
	bool UpdateDesignEvalUnit(1:DesignEvalUnit design_eval_unit),
	DesignEvalUnit GetDesignEvalUnitById(1:i32 id),
	DesignEvalUnit GetDesignEvalUnitByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignEvalUnitIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignEvalUnit> GetDesignEvalUnitList(),
	list<i32> GetDesignEvalUnitIds(),
	list<string> GetDesignEvalUnitNames(),
	void AddMoreDesignEvalUnit(1:list<DesignEvalUnit> objs),
	void DeleteMoreDesignEvalUnit(1:list<i32> obj_ids),
	DesignEvalUnit GetDesignEvalUnitByFields(1:map<string, string> fields),
	DesignEvalUnit GetDesignEvalUnitByField1(1:string field, 2:string value),
	DesignEvalUnit GetDesignEvalUnitByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignEvalUnit> GetDesignEvalUnitListByFields(1:map<string, string> fields),
	list<DesignEvalUnit> GetDesignEvalUnitListByField1(1:string field, 2:string value),
	list<DesignEvalUnit> GetDesignEvalUnitListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignEvalUnitIdByFields(1:map<string, string> fields),
	i32 GetDesignEvalUnitIdByField1(1:string field, 2:string value),
	i32 GetDesignEvalUnitIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignEvalUnitIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignEvalUnitIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignEvalUnitIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignEvalUnit> GetDesignEvalUnitListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignEvalUnitIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignEvalUnitPartition 类型的CRUD操作
	i32 AddDesignEvalUnitPartition(1:DesignEvalUnitPartition design_eval_unit_partition),
	bool DeleteDesignEvalUnitPartition(1:i32 id),
	bool UpdateDesignEvalUnitPartition(1:DesignEvalUnitPartition design_eval_unit_partition),
	DesignEvalUnitPartition GetDesignEvalUnitPartitionById(1:i32 id),
	DesignEvalUnitPartition GetDesignEvalUnitPartitionByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignEvalUnitPartitionIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignEvalUnitPartition> GetDesignEvalUnitPartitionList(),
	list<i32> GetDesignEvalUnitPartitionIds(),
	list<string> GetDesignEvalUnitPartitionNames(),
	void AddMoreDesignEvalUnitPartition(1:list<DesignEvalUnitPartition> objs),
	void DeleteMoreDesignEvalUnitPartition(1:list<i32> obj_ids),
	DesignEvalUnitPartition GetDesignEvalUnitPartitionByFields(1:map<string, string> fields),
	DesignEvalUnitPartition GetDesignEvalUnitPartitionByField1(1:string field, 2:string value),
	DesignEvalUnitPartition GetDesignEvalUnitPartitionByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignEvalUnitPartition> GetDesignEvalUnitPartitionListByFields(1:map<string, string> fields),
	list<DesignEvalUnitPartition> GetDesignEvalUnitPartitionListByField1(1:string field, 2:string value),
	list<DesignEvalUnitPartition> GetDesignEvalUnitPartitionListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignEvalUnitPartitionIdByFields(1:map<string, string> fields),
	i32 GetDesignEvalUnitPartitionIdByField1(1:string field, 2:string value),
	i32 GetDesignEvalUnitPartitionIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignEvalUnitPartitionIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignEvalUnitPartitionIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignEvalUnitPartitionIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignEvalUnitPartition> GetDesignEvalUnitPartitionListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignEvalUnitPartitionIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignGoafPore 类型的CRUD操作
	i32 AddDesignGoafPore(1:DesignGoafPore design_goaf_pore),
	bool DeleteDesignGoafPore(1:i32 id),
	bool UpdateDesignGoafPore(1:DesignGoafPore design_goaf_pore),
	DesignGoafPore GetDesignGoafPoreById(1:i32 id),
	DesignGoafPore GetDesignGoafPoreByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignGoafPoreIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignGoafPore> GetDesignGoafPoreList(),
	list<i32> GetDesignGoafPoreIds(),
	list<string> GetDesignGoafPoreNames(),
	void AddMoreDesignGoafPore(1:list<DesignGoafPore> objs),
	void DeleteMoreDesignGoafPore(1:list<i32> obj_ids),
	DesignGoafPore GetDesignGoafPoreByFields(1:map<string, string> fields),
	DesignGoafPore GetDesignGoafPoreByField1(1:string field, 2:string value),
	DesignGoafPore GetDesignGoafPoreByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignGoafPore> GetDesignGoafPoreListByFields(1:map<string, string> fields),
	list<DesignGoafPore> GetDesignGoafPoreListByField1(1:string field, 2:string value),
	list<DesignGoafPore> GetDesignGoafPoreListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignGoafPoreIdByFields(1:map<string, string> fields),
	i32 GetDesignGoafPoreIdByField1(1:string field, 2:string value),
	i32 GetDesignGoafPoreIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignGoafPoreIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignGoafPoreIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignGoafPoreIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignGoafPore> GetDesignGoafPoreListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignGoafPoreIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignGoafTechnology 类型的CRUD操作
	i32 AddDesignGoafTechnology(1:DesignGoafTechnology design_goaf_technology),
	bool DeleteDesignGoafTechnology(1:i32 id),
	bool UpdateDesignGoafTechnology(1:DesignGoafTechnology design_goaf_technology),
	DesignGoafTechnology GetDesignGoafTechnologyById(1:i32 id),
	DesignGoafTechnology GetDesignGoafTechnologyByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignGoafTechnologyIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignGoafTechnology> GetDesignGoafTechnologyList(),
	list<i32> GetDesignGoafTechnologyIds(),
	list<string> GetDesignGoafTechnologyNames(),
	void AddMoreDesignGoafTechnology(1:list<DesignGoafTechnology> objs),
	void DeleteMoreDesignGoafTechnology(1:list<i32> obj_ids),
	DesignGoafTechnology GetDesignGoafTechnologyByFields(1:map<string, string> fields),
	DesignGoafTechnology GetDesignGoafTechnologyByField1(1:string field, 2:string value),
	DesignGoafTechnology GetDesignGoafTechnologyByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignGoafTechnology> GetDesignGoafTechnologyListByFields(1:map<string, string> fields),
	list<DesignGoafTechnology> GetDesignGoafTechnologyListByField1(1:string field, 2:string value),
	list<DesignGoafTechnology> GetDesignGoafTechnologyListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignGoafTechnologyIdByFields(1:map<string, string> fields),
	i32 GetDesignGoafTechnologyIdByField1(1:string field, 2:string value),
	i32 GetDesignGoafTechnologyIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignGoafTechnologyIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignGoafTechnologyIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignGoafTechnologyIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignGoafTechnology> GetDesignGoafTechnologyListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignGoafTechnologyIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignPore 类型的CRUD操作
	i32 AddDesignPore(1:DesignPore design_pore),
	bool DeleteDesignPore(1:i32 id),
	bool UpdateDesignPore(1:DesignPore design_pore),
	DesignPore GetDesignPoreById(1:i32 id),
	DesignPore GetDesignPoreByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignPoreIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignPore> GetDesignPoreList(),
	list<i32> GetDesignPoreIds(),
	list<string> GetDesignPoreNames(),
	void AddMoreDesignPore(1:list<DesignPore> objs),
	void DeleteMoreDesignPore(1:list<i32> obj_ids),
	DesignPore GetDesignPoreByFields(1:map<string, string> fields),
	DesignPore GetDesignPoreByField1(1:string field, 2:string value),
	DesignPore GetDesignPoreByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignPore> GetDesignPoreListByFields(1:map<string, string> fields),
	list<DesignPore> GetDesignPoreListByField1(1:string field, 2:string value),
	list<DesignPore> GetDesignPoreListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignPoreIdByFields(1:map<string, string> fields),
	i32 GetDesignPoreIdByField1(1:string field, 2:string value),
	i32 GetDesignPoreIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignPoreIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignPoreIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignPoreIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignPore> GetDesignPoreListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignPoreIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignSite 类型的CRUD操作
	i32 AddDesignSite(1:DesignSite design_site),
	bool DeleteDesignSite(1:i32 id),
	bool UpdateDesignSite(1:DesignSite design_site),
	DesignSite GetDesignSiteById(1:i32 id),
	DesignSite GetDesignSiteByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignSiteIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignSite> GetDesignSiteList(),
	list<i32> GetDesignSiteIds(),
	list<string> GetDesignSiteNames(),
	void AddMoreDesignSite(1:list<DesignSite> objs),
	void DeleteMoreDesignSite(1:list<i32> obj_ids),
	DesignSite GetDesignSiteByFields(1:map<string, string> fields),
	DesignSite GetDesignSiteByField1(1:string field, 2:string value),
	DesignSite GetDesignSiteByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignSite> GetDesignSiteListByFields(1:map<string, string> fields),
	list<DesignSite> GetDesignSiteListByField1(1:string field, 2:string value),
	list<DesignSite> GetDesignSiteListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignSiteIdByFields(1:map<string, string> fields),
	i32 GetDesignSiteIdByField1(1:string field, 2:string value),
	i32 GetDesignSiteIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignSiteIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignSiteIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignSiteIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignSite> GetDesignSiteListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignSiteIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignTechnology 类型的CRUD操作
	i32 AddDesignTechnology(1:DesignTechnology design_technology),
	bool DeleteDesignTechnology(1:i32 id),
	bool UpdateDesignTechnology(1:DesignTechnology design_technology),
	DesignTechnology GetDesignTechnologyById(1:i32 id),
	DesignTechnology GetDesignTechnologyByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignTechnologyIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignTechnology> GetDesignTechnologyList(),
	list<i32> GetDesignTechnologyIds(),
	list<string> GetDesignTechnologyNames(),
	void AddMoreDesignTechnology(1:list<DesignTechnology> objs),
	void DeleteMoreDesignTechnology(1:list<i32> obj_ids),
	DesignTechnology GetDesignTechnologyByFields(1:map<string, string> fields),
	DesignTechnology GetDesignTechnologyByField1(1:string field, 2:string value),
	DesignTechnology GetDesignTechnologyByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignTechnology> GetDesignTechnologyListByFields(1:map<string, string> fields),
	list<DesignTechnology> GetDesignTechnologyListByField1(1:string field, 2:string value),
	list<DesignTechnology> GetDesignTechnologyListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignTechnologyIdByFields(1:map<string, string> fields),
	i32 GetDesignTechnologyIdByField1(1:string field, 2:string value),
	i32 GetDesignTechnologyIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignTechnologyIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignTechnologyIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignTechnologyIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignTechnology> GetDesignTechnologyListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignTechnologyIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignTunnelControlPoint 类型的CRUD操作
	i32 AddDesignTunnelControlPoint(1:DesignTunnelControlPoint design_tunnel_control_point),
	bool DeleteDesignTunnelControlPoint(1:i32 id),
	bool UpdateDesignTunnelControlPoint(1:DesignTunnelControlPoint design_tunnel_control_point),
	DesignTunnelControlPoint GetDesignTunnelControlPointById(1:i32 id),
	DesignTunnelControlPoint GetDesignTunnelControlPointByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignTunnelControlPointIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignTunnelControlPoint> GetDesignTunnelControlPointList(),
	list<i32> GetDesignTunnelControlPointIds(),
	list<string> GetDesignTunnelControlPointNames(),
	void AddMoreDesignTunnelControlPoint(1:list<DesignTunnelControlPoint> objs),
	void DeleteMoreDesignTunnelControlPoint(1:list<i32> obj_ids),
	DesignTunnelControlPoint GetDesignTunnelControlPointByFields(1:map<string, string> fields),
	DesignTunnelControlPoint GetDesignTunnelControlPointByField1(1:string field, 2:string value),
	DesignTunnelControlPoint GetDesignTunnelControlPointByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignTunnelControlPoint> GetDesignTunnelControlPointListByFields(1:map<string, string> fields),
	list<DesignTunnelControlPoint> GetDesignTunnelControlPointListByField1(1:string field, 2:string value),
	list<DesignTunnelControlPoint> GetDesignTunnelControlPointListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignTunnelControlPointIdByFields(1:map<string, string> fields),
	i32 GetDesignTunnelControlPointIdByField1(1:string field, 2:string value),
	i32 GetDesignTunnelControlPointIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignTunnelControlPointIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignTunnelControlPointIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignTunnelControlPointIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignTunnelControlPoint> GetDesignTunnelControlPointListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignTunnelControlPointIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignWorkSurfControlPoint 类型的CRUD操作
	i32 AddDesignWorkSurfControlPoint(1:DesignWorkSurfControlPoint design_work_surf_control_point),
	bool DeleteDesignWorkSurfControlPoint(1:i32 id),
	bool UpdateDesignWorkSurfControlPoint(1:DesignWorkSurfControlPoint design_work_surf_control_point),
	DesignWorkSurfControlPoint GetDesignWorkSurfControlPointById(1:i32 id),
	DesignWorkSurfControlPoint GetDesignWorkSurfControlPointByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignWorkSurfControlPointIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignWorkSurfControlPoint> GetDesignWorkSurfControlPointList(),
	list<i32> GetDesignWorkSurfControlPointIds(),
	list<string> GetDesignWorkSurfControlPointNames(),
	void AddMoreDesignWorkSurfControlPoint(1:list<DesignWorkSurfControlPoint> objs),
	void DeleteMoreDesignWorkSurfControlPoint(1:list<i32> obj_ids),
	DesignWorkSurfControlPoint GetDesignWorkSurfControlPointByFields(1:map<string, string> fields),
	DesignWorkSurfControlPoint GetDesignWorkSurfControlPointByField1(1:string field, 2:string value),
	DesignWorkSurfControlPoint GetDesignWorkSurfControlPointByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignWorkSurfControlPoint> GetDesignWorkSurfControlPointListByFields(1:map<string, string> fields),
	list<DesignWorkSurfControlPoint> GetDesignWorkSurfControlPointListByField1(1:string field, 2:string value),
	list<DesignWorkSurfControlPoint> GetDesignWorkSurfControlPointListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignWorkSurfControlPointIdByFields(1:map<string, string> fields),
	i32 GetDesignWorkSurfControlPointIdByField1(1:string field, 2:string value),
	i32 GetDesignWorkSurfControlPointIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignWorkSurfControlPointIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignWorkSurfControlPointIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignWorkSurfControlPointIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignWorkSurfControlPoint> GetDesignWorkSurfControlPointListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignWorkSurfControlPointIdListByForeignKey(1:string fkey, 2:i32 id),

	//DesignWorkSurfTechnology 类型的CRUD操作
	i32 AddDesignWorkSurfTechnology(1:DesignWorkSurfTechnology design_work_surf_technology),
	bool DeleteDesignWorkSurfTechnology(1:i32 id),
	bool UpdateDesignWorkSurfTechnology(1:DesignWorkSurfTechnology design_work_surf_technology),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyById(1:i32 id),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDesignWorkSurfTechnologyIdByForeignKey(1:string fkey, 2:i32 id),
	list<DesignWorkSurfTechnology> GetDesignWorkSurfTechnologyList(),
	list<i32> GetDesignWorkSurfTechnologyIds(),
	list<string> GetDesignWorkSurfTechnologyNames(),
	void AddMoreDesignWorkSurfTechnology(1:list<DesignWorkSurfTechnology> objs),
	void DeleteMoreDesignWorkSurfTechnology(1:list<i32> obj_ids),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyByFields(1:map<string, string> fields),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyByField1(1:string field, 2:string value),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignWorkSurfTechnology> GetDesignWorkSurfTechnologyListByFields(1:map<string, string> fields),
	list<DesignWorkSurfTechnology> GetDesignWorkSurfTechnologyListByField1(1:string field, 2:string value),
	list<DesignWorkSurfTechnology> GetDesignWorkSurfTechnologyListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDesignWorkSurfTechnologyIdByFields(1:map<string, string> fields),
	i32 GetDesignWorkSurfTechnologyIdByField1(1:string field, 2:string value),
	i32 GetDesignWorkSurfTechnologyIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDesignWorkSurfTechnologyIdListByFields(1:map<string, string> fields),
	list<i32> GetDesignWorkSurfTechnologyIdListByField1(1:string field, 2:string value),
	list<i32> GetDesignWorkSurfTechnologyIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignWorkSurfTechnology> GetDesignWorkSurfTechnologyListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDesignWorkSurfTechnologyIdListByForeignKey(1:string fkey, 2:i32 id),

	//DrillingRadiusParam 类型的CRUD操作
	i32 AddDrillingRadiusParam(1:DrillingRadiusParam drilling_radius_param),
	bool DeleteDrillingRadiusParam(1:i32 id),
	bool UpdateDrillingRadiusParam(1:DrillingRadiusParam drilling_radius_param),
	DrillingRadiusParam GetDrillingRadiusParamById(1:i32 id),
	DrillingRadiusParam GetDrillingRadiusParamByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDrillingRadiusParamIdByForeignKey(1:string fkey, 2:i32 id),
	list<DrillingRadiusParam> GetDrillingRadiusParamList(),
	list<i32> GetDrillingRadiusParamIds(),
	list<string> GetDrillingRadiusParamNames(),
	void AddMoreDrillingRadiusParam(1:list<DrillingRadiusParam> objs),
	void DeleteMoreDrillingRadiusParam(1:list<i32> obj_ids),
	DrillingRadiusParam GetDrillingRadiusParamByFields(1:map<string, string> fields),
	DrillingRadiusParam GetDrillingRadiusParamByField1(1:string field, 2:string value),
	DrillingRadiusParam GetDrillingRadiusParamByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DrillingRadiusParam> GetDrillingRadiusParamListByFields(1:map<string, string> fields),
	list<DrillingRadiusParam> GetDrillingRadiusParamListByField1(1:string field, 2:string value),
	list<DrillingRadiusParam> GetDrillingRadiusParamListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDrillingRadiusParamIdByFields(1:map<string, string> fields),
	i32 GetDrillingRadiusParamIdByField1(1:string field, 2:string value),
	i32 GetDrillingRadiusParamIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDrillingRadiusParamIdListByFields(1:map<string, string> fields),
	list<i32> GetDrillingRadiusParamIdListByField1(1:string field, 2:string value),
	list<i32> GetDrillingRadiusParamIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DrillingRadiusParam> GetDrillingRadiusParamListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDrillingRadiusParamIdListByForeignKey(1:string fkey, 2:i32 id),

	//DrillingSurf 类型的CRUD操作
	i32 AddDrillingSurf(1:DrillingSurf drilling_surf),
	bool DeleteDrillingSurf(1:i32 id),
	bool UpdateDrillingSurf(1:DrillingSurf drilling_surf),
	DrillingSurf GetDrillingSurfById(1:i32 id),
	DrillingSurf GetDrillingSurfByForeignKey(1:string fkey, 2:i32 id),
	i32 GetDrillingSurfIdByForeignKey(1:string fkey, 2:i32 id),
	list<DrillingSurf> GetDrillingSurfList(),
	list<i32> GetDrillingSurfIds(),
	list<string> GetDrillingSurfNames(),
	void AddMoreDrillingSurf(1:list<DrillingSurf> objs),
	void DeleteMoreDrillingSurf(1:list<i32> obj_ids),
	DrillingSurf GetDrillingSurfByFields(1:map<string, string> fields),
	DrillingSurf GetDrillingSurfByField1(1:string field, 2:string value),
	DrillingSurf GetDrillingSurfByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DrillingSurf> GetDrillingSurfListByFields(1:map<string, string> fields),
	list<DrillingSurf> GetDrillingSurfListByField1(1:string field, 2:string value),
	list<DrillingSurf> GetDrillingSurfListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetDrillingSurfIdByFields(1:map<string, string> fields),
	i32 GetDrillingSurfIdByField1(1:string field, 2:string value),
	i32 GetDrillingSurfIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetDrillingSurfIdListByFields(1:map<string, string> fields),
	list<i32> GetDrillingSurfIdListByField1(1:string field, 2:string value),
	list<i32> GetDrillingSurfIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DrillingSurf> GetDrillingSurfListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetDrillingSurfIdListByForeignKey(1:string fkey, 2:i32 id),

	//HighDrillingPore 类型的CRUD操作
	i32 AddHighDrillingPore(1:HighDrillingPore high_drilling_pore),
	bool DeleteHighDrillingPore(1:i32 id),
	bool UpdateHighDrillingPore(1:HighDrillingPore high_drilling_pore),
	HighDrillingPore GetHighDrillingPoreById(1:i32 id),
	HighDrillingPore GetHighDrillingPoreByForeignKey(1:string fkey, 2:i32 id),
	i32 GetHighDrillingPoreIdByForeignKey(1:string fkey, 2:i32 id),
	list<HighDrillingPore> GetHighDrillingPoreList(),
	list<i32> GetHighDrillingPoreIds(),
	list<string> GetHighDrillingPoreNames(),
	void AddMoreHighDrillingPore(1:list<HighDrillingPore> objs),
	void DeleteMoreHighDrillingPore(1:list<i32> obj_ids),
	HighDrillingPore GetHighDrillingPoreByFields(1:map<string, string> fields),
	HighDrillingPore GetHighDrillingPoreByField1(1:string field, 2:string value),
	HighDrillingPore GetHighDrillingPoreByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingPore> GetHighDrillingPoreListByFields(1:map<string, string> fields),
	list<HighDrillingPore> GetHighDrillingPoreListByField1(1:string field, 2:string value),
	list<HighDrillingPore> GetHighDrillingPoreListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetHighDrillingPoreIdByFields(1:map<string, string> fields),
	i32 GetHighDrillingPoreIdByField1(1:string field, 2:string value),
	i32 GetHighDrillingPoreIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetHighDrillingPoreIdListByFields(1:map<string, string> fields),
	list<i32> GetHighDrillingPoreIdListByField1(1:string field, 2:string value),
	list<i32> GetHighDrillingPoreIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingPore> GetHighDrillingPoreListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetHighDrillingPoreIdListByForeignKey(1:string fkey, 2:i32 id),

	//HighDrillingPoreParam 类型的CRUD操作
	i32 AddHighDrillingPoreParam(1:HighDrillingPoreParam high_drilling_pore_param),
	bool DeleteHighDrillingPoreParam(1:i32 id),
	bool UpdateHighDrillingPoreParam(1:HighDrillingPoreParam high_drilling_pore_param),
	HighDrillingPoreParam GetHighDrillingPoreParamById(1:i32 id),
	HighDrillingPoreParam GetHighDrillingPoreParamByForeignKey(1:string fkey, 2:i32 id),
	i32 GetHighDrillingPoreParamIdByForeignKey(1:string fkey, 2:i32 id),
	list<HighDrillingPoreParam> GetHighDrillingPoreParamList(),
	list<i32> GetHighDrillingPoreParamIds(),
	list<string> GetHighDrillingPoreParamNames(),
	void AddMoreHighDrillingPoreParam(1:list<HighDrillingPoreParam> objs),
	void DeleteMoreHighDrillingPoreParam(1:list<i32> obj_ids),
	HighDrillingPoreParam GetHighDrillingPoreParamByFields(1:map<string, string> fields),
	HighDrillingPoreParam GetHighDrillingPoreParamByField1(1:string field, 2:string value),
	HighDrillingPoreParam GetHighDrillingPoreParamByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingPoreParam> GetHighDrillingPoreParamListByFields(1:map<string, string> fields),
	list<HighDrillingPoreParam> GetHighDrillingPoreParamListByField1(1:string field, 2:string value),
	list<HighDrillingPoreParam> GetHighDrillingPoreParamListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetHighDrillingPoreParamIdByFields(1:map<string, string> fields),
	i32 GetHighDrillingPoreParamIdByField1(1:string field, 2:string value),
	i32 GetHighDrillingPoreParamIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetHighDrillingPoreParamIdListByFields(1:map<string, string> fields),
	list<i32> GetHighDrillingPoreParamIdListByField1(1:string field, 2:string value),
	list<i32> GetHighDrillingPoreParamIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingPoreParam> GetHighDrillingPoreParamListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetHighDrillingPoreParamIdListByForeignKey(1:string fkey, 2:i32 id),

	//HighDrillingSiteParam 类型的CRUD操作
	i32 AddHighDrillingSiteParam(1:HighDrillingSiteParam high_drilling_site_param),
	bool DeleteHighDrillingSiteParam(1:i32 id),
	bool UpdateHighDrillingSiteParam(1:HighDrillingSiteParam high_drilling_site_param),
	HighDrillingSiteParam GetHighDrillingSiteParamById(1:i32 id),
	HighDrillingSiteParam GetHighDrillingSiteParamByForeignKey(1:string fkey, 2:i32 id),
	i32 GetHighDrillingSiteParamIdByForeignKey(1:string fkey, 2:i32 id),
	list<HighDrillingSiteParam> GetHighDrillingSiteParamList(),
	list<i32> GetHighDrillingSiteParamIds(),
	list<string> GetHighDrillingSiteParamNames(),
	void AddMoreHighDrillingSiteParam(1:list<HighDrillingSiteParam> objs),
	void DeleteMoreHighDrillingSiteParam(1:list<i32> obj_ids),
	HighDrillingSiteParam GetHighDrillingSiteParamByFields(1:map<string, string> fields),
	HighDrillingSiteParam GetHighDrillingSiteParamByField1(1:string field, 2:string value),
	HighDrillingSiteParam GetHighDrillingSiteParamByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingSiteParam> GetHighDrillingSiteParamListByFields(1:map<string, string> fields),
	list<HighDrillingSiteParam> GetHighDrillingSiteParamListByField1(1:string field, 2:string value),
	list<HighDrillingSiteParam> GetHighDrillingSiteParamListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetHighDrillingSiteParamIdByFields(1:map<string, string> fields),
	i32 GetHighDrillingSiteParamIdByField1(1:string field, 2:string value),
	i32 GetHighDrillingSiteParamIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetHighDrillingSiteParamIdListByFields(1:map<string, string> fields),
	list<i32> GetHighDrillingSiteParamIdListByField1(1:string field, 2:string value),
	list<i32> GetHighDrillingSiteParamIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingSiteParam> GetHighDrillingSiteParamListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetHighDrillingSiteParamIdListByForeignKey(1:string fkey, 2:i32 id),

	//HighDrillingTunnel 类型的CRUD操作
	i32 AddHighDrillingTunnel(1:HighDrillingTunnel high_drilling_tunnel),
	bool DeleteHighDrillingTunnel(1:i32 id),
	bool UpdateHighDrillingTunnel(1:HighDrillingTunnel high_drilling_tunnel),
	HighDrillingTunnel GetHighDrillingTunnelById(1:i32 id),
	HighDrillingTunnel GetHighDrillingTunnelByForeignKey(1:string fkey, 2:i32 id),
	i32 GetHighDrillingTunnelIdByForeignKey(1:string fkey, 2:i32 id),
	list<HighDrillingTunnel> GetHighDrillingTunnelList(),
	list<i32> GetHighDrillingTunnelIds(),
	list<string> GetHighDrillingTunnelNames(),
	void AddMoreHighDrillingTunnel(1:list<HighDrillingTunnel> objs),
	void DeleteMoreHighDrillingTunnel(1:list<i32> obj_ids),
	HighDrillingTunnel GetHighDrillingTunnelByFields(1:map<string, string> fields),
	HighDrillingTunnel GetHighDrillingTunnelByField1(1:string field, 2:string value),
	HighDrillingTunnel GetHighDrillingTunnelByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingTunnel> GetHighDrillingTunnelListByFields(1:map<string, string> fields),
	list<HighDrillingTunnel> GetHighDrillingTunnelListByField1(1:string field, 2:string value),
	list<HighDrillingTunnel> GetHighDrillingTunnelListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetHighDrillingTunnelIdByFields(1:map<string, string> fields),
	i32 GetHighDrillingTunnelIdByField1(1:string field, 2:string value),
	i32 GetHighDrillingTunnelIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetHighDrillingTunnelIdListByFields(1:map<string, string> fields),
	list<i32> GetHighDrillingTunnelIdListByField1(1:string field, 2:string value),
	list<i32> GetHighDrillingTunnelIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingTunnel> GetHighDrillingTunnelListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetHighDrillingTunnelIdListByForeignKey(1:string fkey, 2:i32 id),

	//HydrGeo 类型的CRUD操作
	i32 AddHydrGeo(1:HydrGeo hydr_geo),
	bool DeleteHydrGeo(1:i32 id),
	bool UpdateHydrGeo(1:HydrGeo hydr_geo),
	HydrGeo GetHydrGeoById(1:i32 id),
	HydrGeo GetHydrGeoByForeignKey(1:string fkey, 2:i32 id),
	i32 GetHydrGeoIdByForeignKey(1:string fkey, 2:i32 id),
	list<HydrGeo> GetHydrGeoList(),
	list<i32> GetHydrGeoIds(),
	list<string> GetHydrGeoNames(),
	void AddMoreHydrGeo(1:list<HydrGeo> objs),
	void DeleteMoreHydrGeo(1:list<i32> obj_ids),
	HydrGeo GetHydrGeoByFields(1:map<string, string> fields),
	HydrGeo GetHydrGeoByField1(1:string field, 2:string value),
	HydrGeo GetHydrGeoByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HydrGeo> GetHydrGeoListByFields(1:map<string, string> fields),
	list<HydrGeo> GetHydrGeoListByField1(1:string field, 2:string value),
	list<HydrGeo> GetHydrGeoListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetHydrGeoIdByFields(1:map<string, string> fields),
	i32 GetHydrGeoIdByField1(1:string field, 2:string value),
	i32 GetHydrGeoIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetHydrGeoIdListByFields(1:map<string, string> fields),
	list<i32> GetHydrGeoIdListByField1(1:string field, 2:string value),
	list<i32> GetHydrGeoIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HydrGeo> GetHydrGeoListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetHydrGeoIdListByForeignKey(1:string fkey, 2:i32 id),

	//Mine 类型的CRUD操作
	i32 AddMine(1:Mine mine),
	bool DeleteMine(1:i32 id),
	bool UpdateMine(1:Mine mine),
	Mine GetMineById(1:i32 id),
	Mine GetMineByForeignKey(1:string fkey, 2:i32 id),
	i32 GetMineIdByForeignKey(1:string fkey, 2:i32 id),
	list<Mine> GetMineList(),
	list<i32> GetMineIds(),
	list<string> GetMineNames(),
	void AddMoreMine(1:list<Mine> objs),
	void DeleteMoreMine(1:list<i32> obj_ids),
	Mine GetMineByFields(1:map<string, string> fields),
	Mine GetMineByField1(1:string field, 2:string value),
	Mine GetMineByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Mine> GetMineListByFields(1:map<string, string> fields),
	list<Mine> GetMineListByField1(1:string field, 2:string value),
	list<Mine> GetMineListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetMineIdByFields(1:map<string, string> fields),
	i32 GetMineIdByField1(1:string field, 2:string value),
	i32 GetMineIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetMineIdListByFields(1:map<string, string> fields),
	list<i32> GetMineIdListByField1(1:string field, 2:string value),
	list<i32> GetMineIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Mine> GetMineListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetMineIdListByForeignKey(1:string fkey, 2:i32 id),

	//MineBase 类型的CRUD操作
	i32 AddMineBase(1:MineBase mine_base),
	bool DeleteMineBase(1:i32 id),
	bool UpdateMineBase(1:MineBase mine_base),
	MineBase GetMineBaseById(1:i32 id),
	MineBase GetMineBaseByForeignKey(1:string fkey, 2:i32 id),
	i32 GetMineBaseIdByForeignKey(1:string fkey, 2:i32 id),
	list<MineBase> GetMineBaseList(),
	list<i32> GetMineBaseIds(),
	list<string> GetMineBaseNames(),
	void AddMoreMineBase(1:list<MineBase> objs),
	void DeleteMoreMineBase(1:list<i32> obj_ids),
	MineBase GetMineBaseByFields(1:map<string, string> fields),
	MineBase GetMineBaseByField1(1:string field, 2:string value),
	MineBase GetMineBaseByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<MineBase> GetMineBaseListByFields(1:map<string, string> fields),
	list<MineBase> GetMineBaseListByField1(1:string field, 2:string value),
	list<MineBase> GetMineBaseListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetMineBaseIdByFields(1:map<string, string> fields),
	i32 GetMineBaseIdByField1(1:string field, 2:string value),
	i32 GetMineBaseIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetMineBaseIdListByFields(1:map<string, string> fields),
	list<i32> GetMineBaseIdListByField1(1:string field, 2:string value),
	list<i32> GetMineBaseIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<MineBase> GetMineBaseListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetMineBaseIdListByForeignKey(1:string fkey, 2:i32 id),

	//MineRegion 类型的CRUD操作
	i32 AddMineRegion(1:MineRegion mine_region),
	bool DeleteMineRegion(1:i32 id),
	bool UpdateMineRegion(1:MineRegion mine_region),
	MineRegion GetMineRegionById(1:i32 id),
	MineRegion GetMineRegionByForeignKey(1:string fkey, 2:i32 id),
	i32 GetMineRegionIdByForeignKey(1:string fkey, 2:i32 id),
	list<MineRegion> GetMineRegionList(),
	list<i32> GetMineRegionIds(),
	list<string> GetMineRegionNames(),
	void AddMoreMineRegion(1:list<MineRegion> objs),
	void DeleteMoreMineRegion(1:list<i32> obj_ids),
	MineRegion GetMineRegionByFields(1:map<string, string> fields),
	MineRegion GetMineRegionByField1(1:string field, 2:string value),
	MineRegion GetMineRegionByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<MineRegion> GetMineRegionListByFields(1:map<string, string> fields),
	list<MineRegion> GetMineRegionListByField1(1:string field, 2:string value),
	list<MineRegion> GetMineRegionListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetMineRegionIdByFields(1:map<string, string> fields),
	i32 GetMineRegionIdByField1(1:string field, 2:string value),
	i32 GetMineRegionIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetMineRegionIdListByFields(1:map<string, string> fields),
	list<i32> GetMineRegionIdListByField1(1:string field, 2:string value),
	list<i32> GetMineRegionIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<MineRegion> GetMineRegionListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetMineRegionIdListByForeignKey(1:string fkey, 2:i32 id),

	//PoreFlow 类型的CRUD操作
	i32 AddPoreFlow(1:PoreFlow pore_flow),
	bool DeletePoreFlow(1:i32 id),
	bool UpdatePoreFlow(1:PoreFlow pore_flow),
	PoreFlow GetPoreFlowById(1:i32 id),
	PoreFlow GetPoreFlowByForeignKey(1:string fkey, 2:i32 id),
	i32 GetPoreFlowIdByForeignKey(1:string fkey, 2:i32 id),
	list<PoreFlow> GetPoreFlowList(),
	list<i32> GetPoreFlowIds(),
	list<string> GetPoreFlowNames(),
	void AddMorePoreFlow(1:list<PoreFlow> objs),
	void DeleteMorePoreFlow(1:list<i32> obj_ids),
	PoreFlow GetPoreFlowByFields(1:map<string, string> fields),
	PoreFlow GetPoreFlowByField1(1:string field, 2:string value),
	PoreFlow GetPoreFlowByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<PoreFlow> GetPoreFlowListByFields(1:map<string, string> fields),
	list<PoreFlow> GetPoreFlowListByField1(1:string field, 2:string value),
	list<PoreFlow> GetPoreFlowListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetPoreFlowIdByFields(1:map<string, string> fields),
	i32 GetPoreFlowIdByField1(1:string field, 2:string value),
	i32 GetPoreFlowIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetPoreFlowIdListByFields(1:map<string, string> fields),
	list<i32> GetPoreFlowIdListByField1(1:string field, 2:string value),
	list<i32> GetPoreFlowIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<PoreFlow> GetPoreFlowListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetPoreFlowIdListByForeignKey(1:string fkey, 2:i32 id),

	//PoreSize 类型的CRUD操作
	i32 AddPoreSize(1:PoreSize pore_size),
	bool DeletePoreSize(1:i32 id),
	bool UpdatePoreSize(1:PoreSize pore_size),
	PoreSize GetPoreSizeById(1:i32 id),
	PoreSize GetPoreSizeByForeignKey(1:string fkey, 2:i32 id),
	i32 GetPoreSizeIdByForeignKey(1:string fkey, 2:i32 id),
	list<PoreSize> GetPoreSizeList(),
	list<i32> GetPoreSizeIds(),
	list<string> GetPoreSizeNames(),
	void AddMorePoreSize(1:list<PoreSize> objs),
	void DeleteMorePoreSize(1:list<i32> obj_ids),
	PoreSize GetPoreSizeByFields(1:map<string, string> fields),
	PoreSize GetPoreSizeByField1(1:string field, 2:string value),
	PoreSize GetPoreSizeByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<PoreSize> GetPoreSizeListByFields(1:map<string, string> fields),
	list<PoreSize> GetPoreSizeListByField1(1:string field, 2:string value),
	list<PoreSize> GetPoreSizeListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetPoreSizeIdByFields(1:map<string, string> fields),
	i32 GetPoreSizeIdByField1(1:string field, 2:string value),
	i32 GetPoreSizeIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetPoreSizeIdListByFields(1:map<string, string> fields),
	list<i32> GetPoreSizeIdListByField1(1:string field, 2:string value),
	list<i32> GetPoreSizeIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<PoreSize> GetPoreSizeListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetPoreSizeIdListByForeignKey(1:string fkey, 2:i32 id),

	//ResAbundance 类型的CRUD操作
	i32 AddResAbundance(1:ResAbundance res_abundance),
	bool DeleteResAbundance(1:i32 id),
	bool UpdateResAbundance(1:ResAbundance res_abundance),
	ResAbundance GetResAbundanceById(1:i32 id),
	ResAbundance GetResAbundanceByForeignKey(1:string fkey, 2:i32 id),
	i32 GetResAbundanceIdByForeignKey(1:string fkey, 2:i32 id),
	list<ResAbundance> GetResAbundanceList(),
	list<i32> GetResAbundanceIds(),
	list<string> GetResAbundanceNames(),
	void AddMoreResAbundance(1:list<ResAbundance> objs),
	void DeleteMoreResAbundance(1:list<i32> obj_ids),
	ResAbundance GetResAbundanceByFields(1:map<string, string> fields),
	ResAbundance GetResAbundanceByField1(1:string field, 2:string value),
	ResAbundance GetResAbundanceByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<ResAbundance> GetResAbundanceListByFields(1:map<string, string> fields),
	list<ResAbundance> GetResAbundanceListByField1(1:string field, 2:string value),
	list<ResAbundance> GetResAbundanceListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetResAbundanceIdByFields(1:map<string, string> fields),
	i32 GetResAbundanceIdByField1(1:string field, 2:string value),
	i32 GetResAbundanceIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetResAbundanceIdListByFields(1:map<string, string> fields),
	list<i32> GetResAbundanceIdListByField1(1:string field, 2:string value),
	list<i32> GetResAbundanceIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<ResAbundance> GetResAbundanceListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetResAbundanceIdListByForeignKey(1:string fkey, 2:i32 id),

	//Rock 类型的CRUD操作
	i32 AddRock(1:Rock rock),
	bool DeleteRock(1:i32 id),
	bool UpdateRock(1:Rock rock),
	Rock GetRockById(1:i32 id),
	Rock GetRockByForeignKey(1:string fkey, 2:i32 id),
	i32 GetRockIdByForeignKey(1:string fkey, 2:i32 id),
	list<Rock> GetRockList(),
	list<i32> GetRockIds(),
	list<string> GetRockNames(),
	void AddMoreRock(1:list<Rock> objs),
	void DeleteMoreRock(1:list<i32> obj_ids),
	Rock GetRockByFields(1:map<string, string> fields),
	Rock GetRockByField1(1:string field, 2:string value),
	Rock GetRockByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Rock> GetRockListByFields(1:map<string, string> fields),
	list<Rock> GetRockListByField1(1:string field, 2:string value),
	list<Rock> GetRockListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetRockIdByFields(1:map<string, string> fields),
	i32 GetRockIdByField1(1:string field, 2:string value),
	i32 GetRockIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetRockIdListByFields(1:map<string, string> fields),
	list<i32> GetRockIdListByField1(1:string field, 2:string value),
	list<i32> GetRockIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Rock> GetRockListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetRockIdListByForeignKey(1:string fkey, 2:i32 id),

	//SysInfo 类型的CRUD操作
	i32 AddSysInfo(1:SysInfo sys_info),
	bool DeleteSysInfo(1:i32 id),
	bool UpdateSysInfo(1:SysInfo sys_info),
	SysInfo GetSysInfoById(1:i32 id),
	SysInfo GetSysInfoByForeignKey(1:string fkey, 2:i32 id),
	i32 GetSysInfoIdByForeignKey(1:string fkey, 2:i32 id),
	list<SysInfo> GetSysInfoList(),
	list<i32> GetSysInfoIds(),
	list<string> GetSysInfoNames(),
	void AddMoreSysInfo(1:list<SysInfo> objs),
	void DeleteMoreSysInfo(1:list<i32> obj_ids),
	SysInfo GetSysInfoByFields(1:map<string, string> fields),
	SysInfo GetSysInfoByField1(1:string field, 2:string value),
	SysInfo GetSysInfoByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<SysInfo> GetSysInfoListByFields(1:map<string, string> fields),
	list<SysInfo> GetSysInfoListByField1(1:string field, 2:string value),
	list<SysInfo> GetSysInfoListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetSysInfoIdByFields(1:map<string, string> fields),
	i32 GetSysInfoIdByField1(1:string field, 2:string value),
	i32 GetSysInfoIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetSysInfoIdListByFields(1:map<string, string> fields),
	list<i32> GetSysInfoIdListByField1(1:string field, 2:string value),
	list<i32> GetSysInfoIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<SysInfo> GetSysInfoListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetSysInfoIdListByForeignKey(1:string fkey, 2:i32 id),

	//TechMode 类型的CRUD操作
	i32 AddTechMode(1:TechMode tech_mode),
	bool DeleteTechMode(1:i32 id),
	bool UpdateTechMode(1:TechMode tech_mode),
	TechMode GetTechModeById(1:i32 id),
	TechMode GetTechModeByForeignKey(1:string fkey, 2:i32 id),
	i32 GetTechModeIdByForeignKey(1:string fkey, 2:i32 id),
	list<TechMode> GetTechModeList(),
	list<i32> GetTechModeIds(),
	list<string> GetTechModeNames(),
	void AddMoreTechMode(1:list<TechMode> objs),
	void DeleteMoreTechMode(1:list<i32> obj_ids),
	TechMode GetTechModeByFields(1:map<string, string> fields),
	TechMode GetTechModeByField1(1:string field, 2:string value),
	TechMode GetTechModeByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<TechMode> GetTechModeListByFields(1:map<string, string> fields),
	list<TechMode> GetTechModeListByField1(1:string field, 2:string value),
	list<TechMode> GetTechModeListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetTechModeIdByFields(1:map<string, string> fields),
	i32 GetTechModeIdByField1(1:string field, 2:string value),
	i32 GetTechModeIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetTechModeIdListByFields(1:map<string, string> fields),
	list<i32> GetTechModeIdListByField1(1:string field, 2:string value),
	list<i32> GetTechModeIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<TechMode> GetTechModeListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetTechModeIdListByForeignKey(1:string fkey, 2:i32 id),

	//Technology 类型的CRUD操作
	i32 AddTechnology(1:Technology technology),
	bool DeleteTechnology(1:i32 id),
	bool UpdateTechnology(1:Technology technology),
	Technology GetTechnologyById(1:i32 id),
	Technology GetTechnologyByForeignKey(1:string fkey, 2:i32 id),
	i32 GetTechnologyIdByForeignKey(1:string fkey, 2:i32 id),
	list<Technology> GetTechnologyList(),
	list<i32> GetTechnologyIds(),
	list<string> GetTechnologyNames(),
	void AddMoreTechnology(1:list<Technology> objs),
	void DeleteMoreTechnology(1:list<i32> obj_ids),
	Technology GetTechnologyByFields(1:map<string, string> fields),
	Technology GetTechnologyByField1(1:string field, 2:string value),
	Technology GetTechnologyByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Technology> GetTechnologyListByFields(1:map<string, string> fields),
	list<Technology> GetTechnologyListByField1(1:string field, 2:string value),
	list<Technology> GetTechnologyListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetTechnologyIdByFields(1:map<string, string> fields),
	i32 GetTechnologyIdByField1(1:string field, 2:string value),
	i32 GetTechnologyIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetTechnologyIdListByFields(1:map<string, string> fields),
	list<i32> GetTechnologyIdListByField1(1:string field, 2:string value),
	list<i32> GetTechnologyIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Technology> GetTechnologyListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetTechnologyIdListByForeignKey(1:string fkey, 2:i32 id),

	//TopoGeo 类型的CRUD操作
	i32 AddTopoGeo(1:TopoGeo topo_geo),
	bool DeleteTopoGeo(1:i32 id),
	bool UpdateTopoGeo(1:TopoGeo topo_geo),
	TopoGeo GetTopoGeoById(1:i32 id),
	TopoGeo GetTopoGeoByForeignKey(1:string fkey, 2:i32 id),
	i32 GetTopoGeoIdByForeignKey(1:string fkey, 2:i32 id),
	list<TopoGeo> GetTopoGeoList(),
	list<i32> GetTopoGeoIds(),
	list<string> GetTopoGeoNames(),
	void AddMoreTopoGeo(1:list<TopoGeo> objs),
	void DeleteMoreTopoGeo(1:list<i32> obj_ids),
	TopoGeo GetTopoGeoByFields(1:map<string, string> fields),
	TopoGeo GetTopoGeoByField1(1:string field, 2:string value),
	TopoGeo GetTopoGeoByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<TopoGeo> GetTopoGeoListByFields(1:map<string, string> fields),
	list<TopoGeo> GetTopoGeoListByField1(1:string field, 2:string value),
	list<TopoGeo> GetTopoGeoListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetTopoGeoIdByFields(1:map<string, string> fields),
	i32 GetTopoGeoIdByField1(1:string field, 2:string value),
	i32 GetTopoGeoIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetTopoGeoIdListByFields(1:map<string, string> fields),
	list<i32> GetTopoGeoIdListByField1(1:string field, 2:string value),
	list<i32> GetTopoGeoIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<TopoGeo> GetTopoGeoListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetTopoGeoIdListByForeignKey(1:string fkey, 2:i32 id),

	//Tunnel 类型的CRUD操作
	i32 AddTunnel(1:Tunnel tunnel),
	bool DeleteTunnel(1:i32 id),
	bool UpdateTunnel(1:Tunnel tunnel),
	Tunnel GetTunnelById(1:i32 id),
	Tunnel GetTunnelByForeignKey(1:string fkey, 2:i32 id),
	i32 GetTunnelIdByForeignKey(1:string fkey, 2:i32 id),
	list<Tunnel> GetTunnelList(),
	list<i32> GetTunnelIds(),
	list<string> GetTunnelNames(),
	void AddMoreTunnel(1:list<Tunnel> objs),
	void DeleteMoreTunnel(1:list<i32> obj_ids),
	Tunnel GetTunnelByFields(1:map<string, string> fields),
	Tunnel GetTunnelByField1(1:string field, 2:string value),
	Tunnel GetTunnelByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Tunnel> GetTunnelListByFields(1:map<string, string> fields),
	list<Tunnel> GetTunnelListByField1(1:string field, 2:string value),
	list<Tunnel> GetTunnelListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetTunnelIdByFields(1:map<string, string> fields),
	i32 GetTunnelIdByField1(1:string field, 2:string value),
	i32 GetTunnelIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetTunnelIdListByFields(1:map<string, string> fields),
	list<i32> GetTunnelIdListByField1(1:string field, 2:string value),
	list<i32> GetTunnelIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Tunnel> GetTunnelListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetTunnelIdListByForeignKey(1:string fkey, 2:i32 id),

	//WorkArea 类型的CRUD操作
	i32 AddWorkArea(1:WorkArea work_area),
	bool DeleteWorkArea(1:i32 id),
	bool UpdateWorkArea(1:WorkArea work_area),
	WorkArea GetWorkAreaById(1:i32 id),
	WorkArea GetWorkAreaByForeignKey(1:string fkey, 2:i32 id),
	i32 GetWorkAreaIdByForeignKey(1:string fkey, 2:i32 id),
	list<WorkArea> GetWorkAreaList(),
	list<i32> GetWorkAreaIds(),
	list<string> GetWorkAreaNames(),
	void AddMoreWorkArea(1:list<WorkArea> objs),
	void DeleteMoreWorkArea(1:list<i32> obj_ids),
	WorkArea GetWorkAreaByFields(1:map<string, string> fields),
	WorkArea GetWorkAreaByField1(1:string field, 2:string value),
	WorkArea GetWorkAreaByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<WorkArea> GetWorkAreaListByFields(1:map<string, string> fields),
	list<WorkArea> GetWorkAreaListByField1(1:string field, 2:string value),
	list<WorkArea> GetWorkAreaListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetWorkAreaIdByFields(1:map<string, string> fields),
	i32 GetWorkAreaIdByField1(1:string field, 2:string value),
	i32 GetWorkAreaIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetWorkAreaIdListByFields(1:map<string, string> fields),
	list<i32> GetWorkAreaIdListByField1(1:string field, 2:string value),
	list<i32> GetWorkAreaIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<WorkArea> GetWorkAreaListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetWorkAreaIdListByForeignKey(1:string fkey, 2:i32 id),

	//WorkSurf 类型的CRUD操作
	i32 AddWorkSurf(1:WorkSurf work_surf),
	bool DeleteWorkSurf(1:i32 id),
	bool UpdateWorkSurf(1:WorkSurf work_surf),
	WorkSurf GetWorkSurfById(1:i32 id),
	WorkSurf GetWorkSurfByForeignKey(1:string fkey, 2:i32 id),
	i32 GetWorkSurfIdByForeignKey(1:string fkey, 2:i32 id),
	list<WorkSurf> GetWorkSurfList(),
	list<i32> GetWorkSurfIds(),
	list<string> GetWorkSurfNames(),
	void AddMoreWorkSurf(1:list<WorkSurf> objs),
	void DeleteMoreWorkSurf(1:list<i32> obj_ids),
	WorkSurf GetWorkSurfByFields(1:map<string, string> fields),
	WorkSurf GetWorkSurfByField1(1:string field, 2:string value),
	WorkSurf GetWorkSurfByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<WorkSurf> GetWorkSurfListByFields(1:map<string, string> fields),
	list<WorkSurf> GetWorkSurfListByField1(1:string field, 2:string value),
	list<WorkSurf> GetWorkSurfListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	i32 GetWorkSurfIdByFields(1:map<string, string> fields),
	i32 GetWorkSurfIdByField1(1:string field, 2:string value),
	i32 GetWorkSurfIdByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<i32> GetWorkSurfIdListByFields(1:map<string, string> fields),
	list<i32> GetWorkSurfIdListByField1(1:string field, 2:string value),
	list<i32> GetWorkSurfIdListByField2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<WorkSurf> GetWorkSurfListByForeignKey(1:string fkey, 2:i32 id),
	list<i32> GetWorkSurfIdListByForeignKey(1:string fkey, 2:i32 id),


//}


//service DaoService {
	//初始化示范矿区(虚拟的矿井和煤层)
	void InitSampleRegion(),
	//查询已登录用户的id
	i32 GetOnlineAccountId(),
	//获取已登录用户的矿井数据
	Mine GetOnlineMine(),
	//验证用户名和密码
	i32 VerifyMineAccount(1:string uname, 2:string pwd),
	//查询基地所有的矿区
	list<string> GetMineRegionsOfBase(1:string baseName),
	//根据矿区反查基地
	string GetBaseByRegion(1:string regionName),
	//查询示范矿区的虚拟矿井
	Mine GetSampleMineOfRegion(1:string regionName),
	//查询示范矿区的虚拟煤层
	Coal GetSampleCoalOfRegion(1:string regionName),
	//查询矿井所有的煤层名称
	list<string> GetCoalNamesOfMine(1:i32 mine_id),
	//查询矿井所有的煤层id
	list<i32> GetCoalIdsOfMine(1:i32 mine_id),
	//查询矿井所有的采区
	list<WorkArea> GetWorkAreasOfMine(1:i32 mine_id),
	//查询矿井所有的工作面
	list<WorkSurf> GetWorkSurfsOfMine(1:i32 mine_id),
	//查询矿井所有的掘进面
	list<DrillingSurf> GetDrillingSurfsOfMine(1:i32 mine_id),
	list<i32> GetWorkAreaIdsOfMine(1:i32 mine_id),
	list<i32> GetWorkSurfIdsOfMine(1:i32 mine_id),
	list<i32> GetDrillingSurfIdsOfMine(1:i32 mine_id),

	//抽采难易程度评价
	i32 DifficultEval(1:Coal coal),
	string DifficultEvalString(1:Coal coal),
	//可采煤层瓦斯涌出量计算W1
	double MineGasReservesW1(1:i32 mine_id),
	//不可采煤层瓦斯涌出量计算W2
	double MineGasReservesW2(1:i32 mine_id),
	//计算采区的瓦斯涌出量
	double WorkAreaGasFlow(1:WorkArea work_area, 2:double K1),
	//计算矿井的瓦斯涌出量
	double MineGasFlow(1:Mine mine),
	//工作面开采层瓦斯涌出量
	double WorkSurfGasFlow1(1:Coal coal, 2:WorkArea work_area, 3:WorkSurf work_surf),
	//工作面邻近层瓦斯涌出量
	double WorkSurfGasFlow2(1:Coal coal, 2:WorkArea work_area, 3:WorkSurf work_surf),
	//掘进面瓦斯涌出量
	DrillingSurfGasFlowResult DrillingSurfGasFlow(1:Coal coal, 2:DrillingSurf drilling_surf, 3:Tunnel tunnel),
	//查询设计方案下的所有钻孔
	list<DesignPore> GetAllPores(1:i32 design_id),
//}

// service FetchInfoService {
	// 发送命令到cad(例如zoom a),第2个参数switch_to_cad表示是否激活cad窗口到最前面
	bool SendCommandToCAD(1:string cmd, 2:bool switch_to_cad),
	// 向rpc请求需要cad提供数据,rpc会分配一个密钥(secret_key)
	string RequestJsonDatasFromCAD(1:string input_datas),
	// 通过密钥向rpc的缓存请求数据(cad的数据都放在rpc服务器的缓存里)
	string GetJsonDatasFromRpcCache(1:string secret_key),
	// cad主动发送数据到rpc,rpc将数据进行缓存,客户端凭借密钥从缓存中提取数据
	void PostJsonDatasFromCAD(1:string secret_key, 2:string input_datas, 4:string out_datas),
//}


}