
namespace cpp cbm
namespace php cbm
namespace py cbm

struct Account {
	1: i32 id,
	2: string username,
	3: string password,
	4: string comment,
}

struct AdjLayer {
	1: i32 id,
	2: i32 work_surf_id,
	3: i32 coal_id,
	4: string name,
	5: i32 num,
	6: double h,
	7: double hp,
	8: i32 in_cz,
	9: string comment,
}

struct Coal {
	1: i32 id,
	2: i32 mine_id,
	3: string name,
	4: i32 minable,
	5: double thick,
	6: double hw,
	7: double qa,
	8: double qr,
	9: double fore_qr,
	10: double fore_qa,
	11: i32 rank,
	12: i32 quality,
	13: double pressure,
	14: double gas_content,
	15: double gas_penetration,
	16: double f_value,
	17: i32 res_abundance,
	18: i32 complexity,
	19: double mine_index,
	20: double var_coeff,
	21: i32 stability,
	22: double dip_angle,
	23: double czh,
	24: double czk,
	25: double czw,
	26: double hw_sum,
	27: i32 rock,
	28: double hhh,
	29: double layer_gap,
	30: double influence_factor,
	31: double res_a1,
	32: double gas_x1,
	33: double res_a2,
	34: double gas_x2,
	35: double pump_wc,
	36: double pump_k,
	37: double pump_k2,
	38: double pump_k3,
	39: double pump_k4,
	40: double pump_k1,
	41: string pore_datas,
	42: double rho,
	43: double vr,
	44: double gas_w0,
	45: double gas_wc2,
	46: double gas_wc3,
	47: double gas_eta,
	48: double q0,
	49: i32 eval_method,
	50: double q0_alpha,
	51: double qt_alpha,
	52: double t_alpha,
	53: double q_lambda,
	54: double r_lambda,
	55: double p0_lambda,
	56: double p1_lambda,
	57: double t_lambda,
	58: double a_lambda,
	59: double p1_k,
	60: double p2_k,
	61: double gas_q,
	62: double core_height,
	63: double core_area,
	64: double gas_viscosity,
	65: double decay_alpha,
	66: double permeability_lambda,
	67: double permeability_k,
	68: i32 eval_difficult,
	69: string comment,
}

struct Complexity {
	1: i32 id,
	2: string name,
	3: string details,
	4: string comment,
}

struct DesignDrillingSurfTechnology {
	1: i32 id,
	2: i32 design_technology_id,
	3: string name,
	4: string comment,
	5: double v_offset,
	6: double h_offset,
	7: double dp,
	8: double gp,
	9: double leading_dist,
	10: double gbp,
	11: double l_stripe,
	12: double ls,
	13: double ws,
	14: double hs,
	15: double gs,
	16: double wd,
	17: double hd,
	18: double l1,
	19: double l2,
	20: double w,
	21: double h,
	22: double top_side,
	23: double bottom_side,
	24: double left_side,
	25: double right_side,
	26: double lm,
}

struct DesignGoafTechnology {
	1: i32 id,
	2: i32 design_technology_id,
	3: string name,
	4: string comment,
}

struct DesignPore {
	1: i32 id,
	2: i32 design_site_id,
	3: string name,
	4: double d,
	5: double x1,
	6: double y1,
	7: double z1,
	8: double x2,
	9: double y2,
	10: double z2,
	11: double length,
	12: double angle1,
	13: double angle2,
	14: string comment,
}

struct DesignSite {
	1: i32 id,
	2: i32 design_technology_id,
	3: string name,
	4: double w,
	5: double h,
	6: double x,
	7: double y,
	8: double z,
	9: string comment,
}

struct DesignTechnology {
	1: i32 id,
	2: i32 coal_id,
	3: string name,
	4: i32 mine_region,
	5: string comment,
}

struct DesignWorkSurfTechnology {
	1: i32 id,
	2: i32 design_technology_id,
	3: string name,
	4: string comment,
	5: double top_side,
	6: double bottom_side,
	7: double right_side,
	8: double l1,
	9: double w,
	10: double h,
	11: double l2,
	12: double left_side,
	13: double v_offset,
	14: double h_offset,
	15: double p_offset,
	16: double wd,
	17: double hd,
	18: double lm,
	19: double ws,
	20: double ls,
	21: double gs,
	22: double hs,
	23: double dp,
	24: double gp,
	25: i32 single_rock_tunnel,
	26: double d_offset,
	27: double pore_stubble,
	28: double pore_angle,
	29: i32 pore_type,
}

struct DrillingRadiusParam {
	1: i32 id,
	2: i32 coal_id,
	3: string name,
	4: double r,
	5: double l,
	6: double k1,
	7: double rho,
	8: double q0,
	9: double a,
	10: double t,
	11: double qm,
	12: double qsum,
	13: double eta,
}

struct DrillingSurf {
	1: i32 id,
	2: i32 work_area_id,
	3: i32 tunnel_id,
	4: string name,
	5: double qr,
	6: double qa,
	7: double fore_qr,
	8: double fore_qa,
	9: double q4,
	10: string comment,
}

struct EvalUnit {
	1: i32 id,
	2: i32 work_surf_id,
	3: string name,
	4: double l,
	5: double t,
	6: string comment,
}

struct HighDrillingPore {
	1: i32 id,
	2: i32 high_drilling_pore_param_id,
	3: i32 num,
	4: double length,
	5: double angle,
	6: i32 pore_type,
	7: string comment,
}

struct HighDrillingPoreParam {
	1: i32 id,
	2: i32 work_surf_id,
	3: string name,
	4: double lk,
	5: double lc,
	6: double lw,
	7: i32 n1,
	8: i32 n2,
	9: double beta,
	10: double ld,
	11: string comment,
}

struct HighDrillingSiteParam {
	1: i32 id,
	2: i32 work_surf_id,
	3: string name,
	4: double l1,
	5: double l2,
	6: double lg,
	7: double hn,
	8: double theta,
	9: double q,
	10: double rtn,
	11: double hs,
	12: string comment,
}

struct HighDrillingTunnel {
	1: i32 id,
	2: i32 work_surf_id,
	3: string name,
	4: double k,
	5: i32 rock,
	6: double hz_min,
	7: double hz_max,
	8: string comment,
}

struct HydrGeo {
	1: i32 id,
	2: string name,
	3: i32 x1,
	4: i32 x2,
	5: i32 x3,
	6: double x4,
	7: double x5,
	8: double x6,
	9: double x7,
	10: string x8,
}

struct Mine {
	1: i32 id,
	2: i32 tech_mode_id,
	3: i32 mine_region_id,
	4: i32 account_id,
	5: string name,
	6: string province,
	7: string city,
	8: double capacity,
	9: i32 topo_geo,
	10: i32 hydr_geo,
	11: i32 ground_condition,
	12: double qr,
	13: double qa,
	14: double fore_qr,
	15: double fore_qa,
	16: double gas_k1,
	17: double gas_k2,
	18: string stereo_schem_diagram,
	19: double rock_gas_k2,
	20: double reserve_w1,
	21: double reserve_w2,
	22: double reserve_w3,
	23: double gas_w0,
	24: double gas_wc2,
	25: double pump_k2,
	26: double pump_k3,
	27: double pump_k4,
	28: double pump_k1,
	29: double pump_k,
	30: double pump_wc,
	31: double reserve_gas,
	32: string comment,
}

struct MineBase {
	1: i32 id,
	2: string name,
	3: string comment,
}

struct MineRegion {
	1: i32 id,
	2: i32 mine_base_id,
	3: string name,
	4: string comment,
}

struct PoreFlow {
	1: i32 id,
	2: string name,
	3: double t,
	4: double a0,
	5: double d,
	6: double d1,
	7: double m,
	8: double k,
	9: double delta_t,
	10: double x,
	11: double p_test,
	12: double p_cur,
	13: double b,
	14: double pt,
	15: double delta_p,
	16: double dh,
	17: double q_hun,
	18: double q_chun,
}

struct PoreSize {
	1: i32 id,
	2: string name,
	3: double q,
	4: double v,
	5: double d,
	6: double p,
	7: double sigma,
	8: double delta,
	9: string comment,
}

struct ResAbundance {
	1: i32 id,
	2: string name,
	3: double min_abundance,
	4: double max_abundance,
}

struct Rock {
	1: i32 id,
	2: string name,
	3: double a,
	4: double b,
	5: double c,
	6: string comment,
}

struct SysInfo {
	1: i32 id,
	2: i32 account_id,
	3: string last_login_time,
	4: string comment,
}

struct TechMode {
	1: i32 id,
	2: i32 mine_region_id,
	3: string name,
	4: i32 mode_type,
	5: i32 c1,
	6: i32 c2,
	7: i32 c3,
	8: string comment,
}

struct Technology {
	1: i32 id,
	2: i32 mine_region_id,
	3: string name,
	4: i32 iskey,
	5: string doc,
	6: string video,
	7: string comment,
}

struct TopoGeo {
	1: i32 id,
	2: string name,
	3: string feature,
	4: string comment,
}

struct Tunnel {
	1: i32 id,
	2: string name,
	3: double b,
	4: double h,
	5: double l,
	6: double s,
	7: double d,
	8: double wh,
	9: double v,
	10: double q3,
	11: double q0,
	12: string comment,
	13: i32 tunnel_type,
	14: double top_side,
	15: double bottom_side,
	16: double left_side,
	17: double right_side,
	18: double x1,
	19: double y1,
	20: double z1,
	21: double x2,
	22: double y2,
	23: double z2,
}

struct WorkArea {
	1: i32 id,
	2: i32 coal_id,
	3: string name,
	4: i32 mode,
	5: double a,
	6: double qr,
	7: double qa,
	8: double fore_qr,
	9: double fore_qa,
	10: string comment,
}

struct WorkSurf {
	1: i32 id,
	2: i32 work_area_id,
	3: i32 tunnel_id,
	4: string name,
	5: double a,
	6: double qr,
	7: double qa,
	8: double fore_qr,
	9: double fore_qa,
	10: double l1,
	11: double l2,
	12: i32 layerable,
	13: double k1,
	14: double k2,
	15: double k3,
	16: double kf,
	17: i32 method,
	18: double last_t,
	19: double qr1,
	20: double qr2,
	21: string comment,
}

/*
DrillingSurfGasFlow函数返回多个参数
因此再定义一个struct作为返回参数
*/
struct DrillingSurfGasFlowResult {
	1:double q0,
	2:double q3,
	3:double q4,
	4:double qa
}
service CbmService {

//service SQLService {
	//Account 类型的CRUD操作
	i32 AddAccount(1:Account account),
	bool DeleteAccount(1:i32 id),
	bool UpdateAccount(1:Account account),
	Account GetAccountById(1:i32 id),
	Account GetAccountByForeignKey(1:string fkey, 2:i32 id),
	list<Account> GetAccountList(),
	list<i32> GetAccountIds(),
	list<string> GetAccountNames(),
	void AddMoreAccount(1:list<Account> objs),
	void DeleteMoreAccount(1:list<i32> obj_ids),
	Account GetAccountByFields(1:map<string, string> fields),
	Account GetAccountByFields1(1:string field, 2:string value),
	Account GetAccountByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Account> GetAccountListByFields(1:map<string, string> fields),
	list<Account> GetAccountListByFields1(1:string field, 2:string value),
	list<Account> GetAccountListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//AdjLayer 类型的CRUD操作
	i32 AddAdjLayer(1:AdjLayer adj_layer),
	bool DeleteAdjLayer(1:i32 id),
	bool UpdateAdjLayer(1:AdjLayer adj_layer),
	AdjLayer GetAdjLayerById(1:i32 id),
	AdjLayer GetAdjLayerByForeignKey(1:string fkey, 2:i32 id),
	list<AdjLayer> GetAdjLayerList(),
	list<i32> GetAdjLayerIds(),
	list<string> GetAdjLayerNames(),
	void AddMoreAdjLayer(1:list<AdjLayer> objs),
	void DeleteMoreAdjLayer(1:list<i32> obj_ids),
	AdjLayer GetAdjLayerByFields(1:map<string, string> fields),
	AdjLayer GetAdjLayerByFields1(1:string field, 2:string value),
	AdjLayer GetAdjLayerByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<AdjLayer> GetAdjLayerListByFields(1:map<string, string> fields),
	list<AdjLayer> GetAdjLayerListByFields1(1:string field, 2:string value),
	list<AdjLayer> GetAdjLayerListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//Coal 类型的CRUD操作
	i32 AddCoal(1:Coal coal),
	bool DeleteCoal(1:i32 id),
	bool UpdateCoal(1:Coal coal),
	Coal GetCoalById(1:i32 id),
	Coal GetCoalByForeignKey(1:string fkey, 2:i32 id),
	list<Coal> GetCoalList(),
	list<i32> GetCoalIds(),
	list<string> GetCoalNames(),
	void AddMoreCoal(1:list<Coal> objs),
	void DeleteMoreCoal(1:list<i32> obj_ids),
	Coal GetCoalByFields(1:map<string, string> fields),
	Coal GetCoalByFields1(1:string field, 2:string value),
	Coal GetCoalByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Coal> GetCoalListByFields(1:map<string, string> fields),
	list<Coal> GetCoalListByFields1(1:string field, 2:string value),
	list<Coal> GetCoalListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//Complexity 类型的CRUD操作
	i32 AddComplexity(1:Complexity complexity),
	bool DeleteComplexity(1:i32 id),
	bool UpdateComplexity(1:Complexity complexity),
	Complexity GetComplexityById(1:i32 id),
	Complexity GetComplexityByForeignKey(1:string fkey, 2:i32 id),
	list<Complexity> GetComplexityList(),
	list<i32> GetComplexityIds(),
	list<string> GetComplexityNames(),
	void AddMoreComplexity(1:list<Complexity> objs),
	void DeleteMoreComplexity(1:list<i32> obj_ids),
	Complexity GetComplexityByFields(1:map<string, string> fields),
	Complexity GetComplexityByFields1(1:string field, 2:string value),
	Complexity GetComplexityByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Complexity> GetComplexityListByFields(1:map<string, string> fields),
	list<Complexity> GetComplexityListByFields1(1:string field, 2:string value),
	list<Complexity> GetComplexityListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//DesignDrillingSurfTechnology 类型的CRUD操作
	i32 AddDesignDrillingSurfTechnology(1:DesignDrillingSurfTechnology design_drilling_surf_technology),
	bool DeleteDesignDrillingSurfTechnology(1:i32 id),
	bool UpdateDesignDrillingSurfTechnology(1:DesignDrillingSurfTechnology design_drilling_surf_technology),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyById(1:i32 id),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyByForeignKey(1:string fkey, 2:i32 id),
	list<DesignDrillingSurfTechnology> GetDesignDrillingSurfTechnologyList(),
	list<i32> GetDesignDrillingSurfTechnologyIds(),
	list<string> GetDesignDrillingSurfTechnologyNames(),
	void AddMoreDesignDrillingSurfTechnology(1:list<DesignDrillingSurfTechnology> objs),
	void DeleteMoreDesignDrillingSurfTechnology(1:list<i32> obj_ids),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyByFields(1:map<string, string> fields),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyByFields1(1:string field, 2:string value),
	DesignDrillingSurfTechnology GetDesignDrillingSurfTechnologyByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignDrillingSurfTechnology> GetDesignDrillingSurfTechnologyListByFields(1:map<string, string> fields),
	list<DesignDrillingSurfTechnology> GetDesignDrillingSurfTechnologyListByFields1(1:string field, 2:string value),
	list<DesignDrillingSurfTechnology> GetDesignDrillingSurfTechnologyListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//DesignGoafTechnology 类型的CRUD操作
	i32 AddDesignGoafTechnology(1:DesignGoafTechnology design_goaf_technology),
	bool DeleteDesignGoafTechnology(1:i32 id),
	bool UpdateDesignGoafTechnology(1:DesignGoafTechnology design_goaf_technology),
	DesignGoafTechnology GetDesignGoafTechnologyById(1:i32 id),
	DesignGoafTechnology GetDesignGoafTechnologyByForeignKey(1:string fkey, 2:i32 id),
	list<DesignGoafTechnology> GetDesignGoafTechnologyList(),
	list<i32> GetDesignGoafTechnologyIds(),
	list<string> GetDesignGoafTechnologyNames(),
	void AddMoreDesignGoafTechnology(1:list<DesignGoafTechnology> objs),
	void DeleteMoreDesignGoafTechnology(1:list<i32> obj_ids),
	DesignGoafTechnology GetDesignGoafTechnologyByFields(1:map<string, string> fields),
	DesignGoafTechnology GetDesignGoafTechnologyByFields1(1:string field, 2:string value),
	DesignGoafTechnology GetDesignGoafTechnologyByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignGoafTechnology> GetDesignGoafTechnologyListByFields(1:map<string, string> fields),
	list<DesignGoafTechnology> GetDesignGoafTechnologyListByFields1(1:string field, 2:string value),
	list<DesignGoafTechnology> GetDesignGoafTechnologyListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//DesignPore 类型的CRUD操作
	i32 AddDesignPore(1:DesignPore design_pore),
	bool DeleteDesignPore(1:i32 id),
	bool UpdateDesignPore(1:DesignPore design_pore),
	DesignPore GetDesignPoreById(1:i32 id),
	DesignPore GetDesignPoreByForeignKey(1:string fkey, 2:i32 id),
	list<DesignPore> GetDesignPoreList(),
	list<i32> GetDesignPoreIds(),
	list<string> GetDesignPoreNames(),
	void AddMoreDesignPore(1:list<DesignPore> objs),
	void DeleteMoreDesignPore(1:list<i32> obj_ids),
	DesignPore GetDesignPoreByFields(1:map<string, string> fields),
	DesignPore GetDesignPoreByFields1(1:string field, 2:string value),
	DesignPore GetDesignPoreByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignPore> GetDesignPoreListByFields(1:map<string, string> fields),
	list<DesignPore> GetDesignPoreListByFields1(1:string field, 2:string value),
	list<DesignPore> GetDesignPoreListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//DesignSite 类型的CRUD操作
	i32 AddDesignSite(1:DesignSite design_site),
	bool DeleteDesignSite(1:i32 id),
	bool UpdateDesignSite(1:DesignSite design_site),
	DesignSite GetDesignSiteById(1:i32 id),
	DesignSite GetDesignSiteByForeignKey(1:string fkey, 2:i32 id),
	list<DesignSite> GetDesignSiteList(),
	list<i32> GetDesignSiteIds(),
	list<string> GetDesignSiteNames(),
	void AddMoreDesignSite(1:list<DesignSite> objs),
	void DeleteMoreDesignSite(1:list<i32> obj_ids),
	DesignSite GetDesignSiteByFields(1:map<string, string> fields),
	DesignSite GetDesignSiteByFields1(1:string field, 2:string value),
	DesignSite GetDesignSiteByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignSite> GetDesignSiteListByFields(1:map<string, string> fields),
	list<DesignSite> GetDesignSiteListByFields1(1:string field, 2:string value),
	list<DesignSite> GetDesignSiteListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//DesignTechnology 类型的CRUD操作
	i32 AddDesignTechnology(1:DesignTechnology design_technology),
	bool DeleteDesignTechnology(1:i32 id),
	bool UpdateDesignTechnology(1:DesignTechnology design_technology),
	DesignTechnology GetDesignTechnologyById(1:i32 id),
	DesignTechnology GetDesignTechnologyByForeignKey(1:string fkey, 2:i32 id),
	list<DesignTechnology> GetDesignTechnologyList(),
	list<i32> GetDesignTechnologyIds(),
	list<string> GetDesignTechnologyNames(),
	void AddMoreDesignTechnology(1:list<DesignTechnology> objs),
	void DeleteMoreDesignTechnology(1:list<i32> obj_ids),
	DesignTechnology GetDesignTechnologyByFields(1:map<string, string> fields),
	DesignTechnology GetDesignTechnologyByFields1(1:string field, 2:string value),
	DesignTechnology GetDesignTechnologyByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignTechnology> GetDesignTechnologyListByFields(1:map<string, string> fields),
	list<DesignTechnology> GetDesignTechnologyListByFields1(1:string field, 2:string value),
	list<DesignTechnology> GetDesignTechnologyListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//DesignWorkSurfTechnology 类型的CRUD操作
	i32 AddDesignWorkSurfTechnology(1:DesignWorkSurfTechnology design_work_surf_technology),
	bool DeleteDesignWorkSurfTechnology(1:i32 id),
	bool UpdateDesignWorkSurfTechnology(1:DesignWorkSurfTechnology design_work_surf_technology),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyById(1:i32 id),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyByForeignKey(1:string fkey, 2:i32 id),
	list<DesignWorkSurfTechnology> GetDesignWorkSurfTechnologyList(),
	list<i32> GetDesignWorkSurfTechnologyIds(),
	list<string> GetDesignWorkSurfTechnologyNames(),
	void AddMoreDesignWorkSurfTechnology(1:list<DesignWorkSurfTechnology> objs),
	void DeleteMoreDesignWorkSurfTechnology(1:list<i32> obj_ids),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyByFields(1:map<string, string> fields),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyByFields1(1:string field, 2:string value),
	DesignWorkSurfTechnology GetDesignWorkSurfTechnologyByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DesignWorkSurfTechnology> GetDesignWorkSurfTechnologyListByFields(1:map<string, string> fields),
	list<DesignWorkSurfTechnology> GetDesignWorkSurfTechnologyListByFields1(1:string field, 2:string value),
	list<DesignWorkSurfTechnology> GetDesignWorkSurfTechnologyListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//DrillingRadiusParam 类型的CRUD操作
	i32 AddDrillingRadiusParam(1:DrillingRadiusParam drilling_radius_param),
	bool DeleteDrillingRadiusParam(1:i32 id),
	bool UpdateDrillingRadiusParam(1:DrillingRadiusParam drilling_radius_param),
	DrillingRadiusParam GetDrillingRadiusParamById(1:i32 id),
	DrillingRadiusParam GetDrillingRadiusParamByForeignKey(1:string fkey, 2:i32 id),
	list<DrillingRadiusParam> GetDrillingRadiusParamList(),
	list<i32> GetDrillingRadiusParamIds(),
	list<string> GetDrillingRadiusParamNames(),
	void AddMoreDrillingRadiusParam(1:list<DrillingRadiusParam> objs),
	void DeleteMoreDrillingRadiusParam(1:list<i32> obj_ids),
	DrillingRadiusParam GetDrillingRadiusParamByFields(1:map<string, string> fields),
	DrillingRadiusParam GetDrillingRadiusParamByFields1(1:string field, 2:string value),
	DrillingRadiusParam GetDrillingRadiusParamByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DrillingRadiusParam> GetDrillingRadiusParamListByFields(1:map<string, string> fields),
	list<DrillingRadiusParam> GetDrillingRadiusParamListByFields1(1:string field, 2:string value),
	list<DrillingRadiusParam> GetDrillingRadiusParamListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//DrillingSurf 类型的CRUD操作
	i32 AddDrillingSurf(1:DrillingSurf drilling_surf),
	bool DeleteDrillingSurf(1:i32 id),
	bool UpdateDrillingSurf(1:DrillingSurf drilling_surf),
	DrillingSurf GetDrillingSurfById(1:i32 id),
	DrillingSurf GetDrillingSurfByForeignKey(1:string fkey, 2:i32 id),
	list<DrillingSurf> GetDrillingSurfList(),
	list<i32> GetDrillingSurfIds(),
	list<string> GetDrillingSurfNames(),
	void AddMoreDrillingSurf(1:list<DrillingSurf> objs),
	void DeleteMoreDrillingSurf(1:list<i32> obj_ids),
	DrillingSurf GetDrillingSurfByFields(1:map<string, string> fields),
	DrillingSurf GetDrillingSurfByFields1(1:string field, 2:string value),
	DrillingSurf GetDrillingSurfByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<DrillingSurf> GetDrillingSurfListByFields(1:map<string, string> fields),
	list<DrillingSurf> GetDrillingSurfListByFields1(1:string field, 2:string value),
	list<DrillingSurf> GetDrillingSurfListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//EvalUnit 类型的CRUD操作
	i32 AddEvalUnit(1:EvalUnit eval_unit),
	bool DeleteEvalUnit(1:i32 id),
	bool UpdateEvalUnit(1:EvalUnit eval_unit),
	EvalUnit GetEvalUnitById(1:i32 id),
	EvalUnit GetEvalUnitByForeignKey(1:string fkey, 2:i32 id),
	list<EvalUnit> GetEvalUnitList(),
	list<i32> GetEvalUnitIds(),
	list<string> GetEvalUnitNames(),
	void AddMoreEvalUnit(1:list<EvalUnit> objs),
	void DeleteMoreEvalUnit(1:list<i32> obj_ids),
	EvalUnit GetEvalUnitByFields(1:map<string, string> fields),
	EvalUnit GetEvalUnitByFields1(1:string field, 2:string value),
	EvalUnit GetEvalUnitByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<EvalUnit> GetEvalUnitListByFields(1:map<string, string> fields),
	list<EvalUnit> GetEvalUnitListByFields1(1:string field, 2:string value),
	list<EvalUnit> GetEvalUnitListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//HighDrillingPore 类型的CRUD操作
	i32 AddHighDrillingPore(1:HighDrillingPore high_drilling_pore),
	bool DeleteHighDrillingPore(1:i32 id),
	bool UpdateHighDrillingPore(1:HighDrillingPore high_drilling_pore),
	HighDrillingPore GetHighDrillingPoreById(1:i32 id),
	HighDrillingPore GetHighDrillingPoreByForeignKey(1:string fkey, 2:i32 id),
	list<HighDrillingPore> GetHighDrillingPoreList(),
	list<i32> GetHighDrillingPoreIds(),
	list<string> GetHighDrillingPoreNames(),
	void AddMoreHighDrillingPore(1:list<HighDrillingPore> objs),
	void DeleteMoreHighDrillingPore(1:list<i32> obj_ids),
	HighDrillingPore GetHighDrillingPoreByFields(1:map<string, string> fields),
	HighDrillingPore GetHighDrillingPoreByFields1(1:string field, 2:string value),
	HighDrillingPore GetHighDrillingPoreByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingPore> GetHighDrillingPoreListByFields(1:map<string, string> fields),
	list<HighDrillingPore> GetHighDrillingPoreListByFields1(1:string field, 2:string value),
	list<HighDrillingPore> GetHighDrillingPoreListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//HighDrillingPoreParam 类型的CRUD操作
	i32 AddHighDrillingPoreParam(1:HighDrillingPoreParam high_drilling_pore_param),
	bool DeleteHighDrillingPoreParam(1:i32 id),
	bool UpdateHighDrillingPoreParam(1:HighDrillingPoreParam high_drilling_pore_param),
	HighDrillingPoreParam GetHighDrillingPoreParamById(1:i32 id),
	HighDrillingPoreParam GetHighDrillingPoreParamByForeignKey(1:string fkey, 2:i32 id),
	list<HighDrillingPoreParam> GetHighDrillingPoreParamList(),
	list<i32> GetHighDrillingPoreParamIds(),
	list<string> GetHighDrillingPoreParamNames(),
	void AddMoreHighDrillingPoreParam(1:list<HighDrillingPoreParam> objs),
	void DeleteMoreHighDrillingPoreParam(1:list<i32> obj_ids),
	HighDrillingPoreParam GetHighDrillingPoreParamByFields(1:map<string, string> fields),
	HighDrillingPoreParam GetHighDrillingPoreParamByFields1(1:string field, 2:string value),
	HighDrillingPoreParam GetHighDrillingPoreParamByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingPoreParam> GetHighDrillingPoreParamListByFields(1:map<string, string> fields),
	list<HighDrillingPoreParam> GetHighDrillingPoreParamListByFields1(1:string field, 2:string value),
	list<HighDrillingPoreParam> GetHighDrillingPoreParamListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//HighDrillingSiteParam 类型的CRUD操作
	i32 AddHighDrillingSiteParam(1:HighDrillingSiteParam high_drilling_site_param),
	bool DeleteHighDrillingSiteParam(1:i32 id),
	bool UpdateHighDrillingSiteParam(1:HighDrillingSiteParam high_drilling_site_param),
	HighDrillingSiteParam GetHighDrillingSiteParamById(1:i32 id),
	HighDrillingSiteParam GetHighDrillingSiteParamByForeignKey(1:string fkey, 2:i32 id),
	list<HighDrillingSiteParam> GetHighDrillingSiteParamList(),
	list<i32> GetHighDrillingSiteParamIds(),
	list<string> GetHighDrillingSiteParamNames(),
	void AddMoreHighDrillingSiteParam(1:list<HighDrillingSiteParam> objs),
	void DeleteMoreHighDrillingSiteParam(1:list<i32> obj_ids),
	HighDrillingSiteParam GetHighDrillingSiteParamByFields(1:map<string, string> fields),
	HighDrillingSiteParam GetHighDrillingSiteParamByFields1(1:string field, 2:string value),
	HighDrillingSiteParam GetHighDrillingSiteParamByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingSiteParam> GetHighDrillingSiteParamListByFields(1:map<string, string> fields),
	list<HighDrillingSiteParam> GetHighDrillingSiteParamListByFields1(1:string field, 2:string value),
	list<HighDrillingSiteParam> GetHighDrillingSiteParamListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//HighDrillingTunnel 类型的CRUD操作
	i32 AddHighDrillingTunnel(1:HighDrillingTunnel high_drilling_tunnel),
	bool DeleteHighDrillingTunnel(1:i32 id),
	bool UpdateHighDrillingTunnel(1:HighDrillingTunnel high_drilling_tunnel),
	HighDrillingTunnel GetHighDrillingTunnelById(1:i32 id),
	HighDrillingTunnel GetHighDrillingTunnelByForeignKey(1:string fkey, 2:i32 id),
	list<HighDrillingTunnel> GetHighDrillingTunnelList(),
	list<i32> GetHighDrillingTunnelIds(),
	list<string> GetHighDrillingTunnelNames(),
	void AddMoreHighDrillingTunnel(1:list<HighDrillingTunnel> objs),
	void DeleteMoreHighDrillingTunnel(1:list<i32> obj_ids),
	HighDrillingTunnel GetHighDrillingTunnelByFields(1:map<string, string> fields),
	HighDrillingTunnel GetHighDrillingTunnelByFields1(1:string field, 2:string value),
	HighDrillingTunnel GetHighDrillingTunnelByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HighDrillingTunnel> GetHighDrillingTunnelListByFields(1:map<string, string> fields),
	list<HighDrillingTunnel> GetHighDrillingTunnelListByFields1(1:string field, 2:string value),
	list<HighDrillingTunnel> GetHighDrillingTunnelListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//HydrGeo 类型的CRUD操作
	i32 AddHydrGeo(1:HydrGeo hydr_geo),
	bool DeleteHydrGeo(1:i32 id),
	bool UpdateHydrGeo(1:HydrGeo hydr_geo),
	HydrGeo GetHydrGeoById(1:i32 id),
	HydrGeo GetHydrGeoByForeignKey(1:string fkey, 2:i32 id),
	list<HydrGeo> GetHydrGeoList(),
	list<i32> GetHydrGeoIds(),
	list<string> GetHydrGeoNames(),
	void AddMoreHydrGeo(1:list<HydrGeo> objs),
	void DeleteMoreHydrGeo(1:list<i32> obj_ids),
	HydrGeo GetHydrGeoByFields(1:map<string, string> fields),
	HydrGeo GetHydrGeoByFields1(1:string field, 2:string value),
	HydrGeo GetHydrGeoByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<HydrGeo> GetHydrGeoListByFields(1:map<string, string> fields),
	list<HydrGeo> GetHydrGeoListByFields1(1:string field, 2:string value),
	list<HydrGeo> GetHydrGeoListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//Mine 类型的CRUD操作
	i32 AddMine(1:Mine mine),
	bool DeleteMine(1:i32 id),
	bool UpdateMine(1:Mine mine),
	Mine GetMineById(1:i32 id),
	Mine GetMineByForeignKey(1:string fkey, 2:i32 id),
	list<Mine> GetMineList(),
	list<i32> GetMineIds(),
	list<string> GetMineNames(),
	void AddMoreMine(1:list<Mine> objs),
	void DeleteMoreMine(1:list<i32> obj_ids),
	Mine GetMineByFields(1:map<string, string> fields),
	Mine GetMineByFields1(1:string field, 2:string value),
	Mine GetMineByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Mine> GetMineListByFields(1:map<string, string> fields),
	list<Mine> GetMineListByFields1(1:string field, 2:string value),
	list<Mine> GetMineListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//MineBase 类型的CRUD操作
	i32 AddMineBase(1:MineBase mine_base),
	bool DeleteMineBase(1:i32 id),
	bool UpdateMineBase(1:MineBase mine_base),
	MineBase GetMineBaseById(1:i32 id),
	MineBase GetMineBaseByForeignKey(1:string fkey, 2:i32 id),
	list<MineBase> GetMineBaseList(),
	list<i32> GetMineBaseIds(),
	list<string> GetMineBaseNames(),
	void AddMoreMineBase(1:list<MineBase> objs),
	void DeleteMoreMineBase(1:list<i32> obj_ids),
	MineBase GetMineBaseByFields(1:map<string, string> fields),
	MineBase GetMineBaseByFields1(1:string field, 2:string value),
	MineBase GetMineBaseByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<MineBase> GetMineBaseListByFields(1:map<string, string> fields),
	list<MineBase> GetMineBaseListByFields1(1:string field, 2:string value),
	list<MineBase> GetMineBaseListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//MineRegion 类型的CRUD操作
	i32 AddMineRegion(1:MineRegion mine_region),
	bool DeleteMineRegion(1:i32 id),
	bool UpdateMineRegion(1:MineRegion mine_region),
	MineRegion GetMineRegionById(1:i32 id),
	MineRegion GetMineRegionByForeignKey(1:string fkey, 2:i32 id),
	list<MineRegion> GetMineRegionList(),
	list<i32> GetMineRegionIds(),
	list<string> GetMineRegionNames(),
	void AddMoreMineRegion(1:list<MineRegion> objs),
	void DeleteMoreMineRegion(1:list<i32> obj_ids),
	MineRegion GetMineRegionByFields(1:map<string, string> fields),
	MineRegion GetMineRegionByFields1(1:string field, 2:string value),
	MineRegion GetMineRegionByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<MineRegion> GetMineRegionListByFields(1:map<string, string> fields),
	list<MineRegion> GetMineRegionListByFields1(1:string field, 2:string value),
	list<MineRegion> GetMineRegionListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//PoreFlow 类型的CRUD操作
	i32 AddPoreFlow(1:PoreFlow pore_flow),
	bool DeletePoreFlow(1:i32 id),
	bool UpdatePoreFlow(1:PoreFlow pore_flow),
	PoreFlow GetPoreFlowById(1:i32 id),
	PoreFlow GetPoreFlowByForeignKey(1:string fkey, 2:i32 id),
	list<PoreFlow> GetPoreFlowList(),
	list<i32> GetPoreFlowIds(),
	list<string> GetPoreFlowNames(),
	void AddMorePoreFlow(1:list<PoreFlow> objs),
	void DeleteMorePoreFlow(1:list<i32> obj_ids),
	PoreFlow GetPoreFlowByFields(1:map<string, string> fields),
	PoreFlow GetPoreFlowByFields1(1:string field, 2:string value),
	PoreFlow GetPoreFlowByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<PoreFlow> GetPoreFlowListByFields(1:map<string, string> fields),
	list<PoreFlow> GetPoreFlowListByFields1(1:string field, 2:string value),
	list<PoreFlow> GetPoreFlowListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//PoreSize 类型的CRUD操作
	i32 AddPoreSize(1:PoreSize pore_size),
	bool DeletePoreSize(1:i32 id),
	bool UpdatePoreSize(1:PoreSize pore_size),
	PoreSize GetPoreSizeById(1:i32 id),
	PoreSize GetPoreSizeByForeignKey(1:string fkey, 2:i32 id),
	list<PoreSize> GetPoreSizeList(),
	list<i32> GetPoreSizeIds(),
	list<string> GetPoreSizeNames(),
	void AddMorePoreSize(1:list<PoreSize> objs),
	void DeleteMorePoreSize(1:list<i32> obj_ids),
	PoreSize GetPoreSizeByFields(1:map<string, string> fields),
	PoreSize GetPoreSizeByFields1(1:string field, 2:string value),
	PoreSize GetPoreSizeByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<PoreSize> GetPoreSizeListByFields(1:map<string, string> fields),
	list<PoreSize> GetPoreSizeListByFields1(1:string field, 2:string value),
	list<PoreSize> GetPoreSizeListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//ResAbundance 类型的CRUD操作
	i32 AddResAbundance(1:ResAbundance res_abundance),
	bool DeleteResAbundance(1:i32 id),
	bool UpdateResAbundance(1:ResAbundance res_abundance),
	ResAbundance GetResAbundanceById(1:i32 id),
	ResAbundance GetResAbundanceByForeignKey(1:string fkey, 2:i32 id),
	list<ResAbundance> GetResAbundanceList(),
	list<i32> GetResAbundanceIds(),
	list<string> GetResAbundanceNames(),
	void AddMoreResAbundance(1:list<ResAbundance> objs),
	void DeleteMoreResAbundance(1:list<i32> obj_ids),
	ResAbundance GetResAbundanceByFields(1:map<string, string> fields),
	ResAbundance GetResAbundanceByFields1(1:string field, 2:string value),
	ResAbundance GetResAbundanceByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<ResAbundance> GetResAbundanceListByFields(1:map<string, string> fields),
	list<ResAbundance> GetResAbundanceListByFields1(1:string field, 2:string value),
	list<ResAbundance> GetResAbundanceListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//Rock 类型的CRUD操作
	i32 AddRock(1:Rock rock),
	bool DeleteRock(1:i32 id),
	bool UpdateRock(1:Rock rock),
	Rock GetRockById(1:i32 id),
	Rock GetRockByForeignKey(1:string fkey, 2:i32 id),
	list<Rock> GetRockList(),
	list<i32> GetRockIds(),
	list<string> GetRockNames(),
	void AddMoreRock(1:list<Rock> objs),
	void DeleteMoreRock(1:list<i32> obj_ids),
	Rock GetRockByFields(1:map<string, string> fields),
	Rock GetRockByFields1(1:string field, 2:string value),
	Rock GetRockByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Rock> GetRockListByFields(1:map<string, string> fields),
	list<Rock> GetRockListByFields1(1:string field, 2:string value),
	list<Rock> GetRockListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//SysInfo 类型的CRUD操作
	i32 AddSysInfo(1:SysInfo sys_info),
	bool DeleteSysInfo(1:i32 id),
	bool UpdateSysInfo(1:SysInfo sys_info),
	SysInfo GetSysInfoById(1:i32 id),
	SysInfo GetSysInfoByForeignKey(1:string fkey, 2:i32 id),
	list<SysInfo> GetSysInfoList(),
	list<i32> GetSysInfoIds(),
	list<string> GetSysInfoNames(),
	void AddMoreSysInfo(1:list<SysInfo> objs),
	void DeleteMoreSysInfo(1:list<i32> obj_ids),
	SysInfo GetSysInfoByFields(1:map<string, string> fields),
	SysInfo GetSysInfoByFields1(1:string field, 2:string value),
	SysInfo GetSysInfoByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<SysInfo> GetSysInfoListByFields(1:map<string, string> fields),
	list<SysInfo> GetSysInfoListByFields1(1:string field, 2:string value),
	list<SysInfo> GetSysInfoListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//TechMode 类型的CRUD操作
	i32 AddTechMode(1:TechMode tech_mode),
	bool DeleteTechMode(1:i32 id),
	bool UpdateTechMode(1:TechMode tech_mode),
	TechMode GetTechModeById(1:i32 id),
	TechMode GetTechModeByForeignKey(1:string fkey, 2:i32 id),
	list<TechMode> GetTechModeList(),
	list<i32> GetTechModeIds(),
	list<string> GetTechModeNames(),
	void AddMoreTechMode(1:list<TechMode> objs),
	void DeleteMoreTechMode(1:list<i32> obj_ids),
	TechMode GetTechModeByFields(1:map<string, string> fields),
	TechMode GetTechModeByFields1(1:string field, 2:string value),
	TechMode GetTechModeByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<TechMode> GetTechModeListByFields(1:map<string, string> fields),
	list<TechMode> GetTechModeListByFields1(1:string field, 2:string value),
	list<TechMode> GetTechModeListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//Technology 类型的CRUD操作
	i32 AddTechnology(1:Technology technology),
	bool DeleteTechnology(1:i32 id),
	bool UpdateTechnology(1:Technology technology),
	Technology GetTechnologyById(1:i32 id),
	Technology GetTechnologyByForeignKey(1:string fkey, 2:i32 id),
	list<Technology> GetTechnologyList(),
	list<i32> GetTechnologyIds(),
	list<string> GetTechnologyNames(),
	void AddMoreTechnology(1:list<Technology> objs),
	void DeleteMoreTechnology(1:list<i32> obj_ids),
	Technology GetTechnologyByFields(1:map<string, string> fields),
	Technology GetTechnologyByFields1(1:string field, 2:string value),
	Technology GetTechnologyByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Technology> GetTechnologyListByFields(1:map<string, string> fields),
	list<Technology> GetTechnologyListByFields1(1:string field, 2:string value),
	list<Technology> GetTechnologyListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//TopoGeo 类型的CRUD操作
	i32 AddTopoGeo(1:TopoGeo topo_geo),
	bool DeleteTopoGeo(1:i32 id),
	bool UpdateTopoGeo(1:TopoGeo topo_geo),
	TopoGeo GetTopoGeoById(1:i32 id),
	TopoGeo GetTopoGeoByForeignKey(1:string fkey, 2:i32 id),
	list<TopoGeo> GetTopoGeoList(),
	list<i32> GetTopoGeoIds(),
	list<string> GetTopoGeoNames(),
	void AddMoreTopoGeo(1:list<TopoGeo> objs),
	void DeleteMoreTopoGeo(1:list<i32> obj_ids),
	TopoGeo GetTopoGeoByFields(1:map<string, string> fields),
	TopoGeo GetTopoGeoByFields1(1:string field, 2:string value),
	TopoGeo GetTopoGeoByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<TopoGeo> GetTopoGeoListByFields(1:map<string, string> fields),
	list<TopoGeo> GetTopoGeoListByFields1(1:string field, 2:string value),
	list<TopoGeo> GetTopoGeoListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//Tunnel 类型的CRUD操作
	i32 AddTunnel(1:Tunnel tunnel),
	bool DeleteTunnel(1:i32 id),
	bool UpdateTunnel(1:Tunnel tunnel),
	Tunnel GetTunnelById(1:i32 id),
	Tunnel GetTunnelByForeignKey(1:string fkey, 2:i32 id),
	list<Tunnel> GetTunnelList(),
	list<i32> GetTunnelIds(),
	list<string> GetTunnelNames(),
	void AddMoreTunnel(1:list<Tunnel> objs),
	void DeleteMoreTunnel(1:list<i32> obj_ids),
	Tunnel GetTunnelByFields(1:map<string, string> fields),
	Tunnel GetTunnelByFields1(1:string field, 2:string value),
	Tunnel GetTunnelByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<Tunnel> GetTunnelListByFields(1:map<string, string> fields),
	list<Tunnel> GetTunnelListByFields1(1:string field, 2:string value),
	list<Tunnel> GetTunnelListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//WorkArea 类型的CRUD操作
	i32 AddWorkArea(1:WorkArea work_area),
	bool DeleteWorkArea(1:i32 id),
	bool UpdateWorkArea(1:WorkArea work_area),
	WorkArea GetWorkAreaById(1:i32 id),
	WorkArea GetWorkAreaByForeignKey(1:string fkey, 2:i32 id),
	list<WorkArea> GetWorkAreaList(),
	list<i32> GetWorkAreaIds(),
	list<string> GetWorkAreaNames(),
	void AddMoreWorkArea(1:list<WorkArea> objs),
	void DeleteMoreWorkArea(1:list<i32> obj_ids),
	WorkArea GetWorkAreaByFields(1:map<string, string> fields),
	WorkArea GetWorkAreaByFields1(1:string field, 2:string value),
	WorkArea GetWorkAreaByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<WorkArea> GetWorkAreaListByFields(1:map<string, string> fields),
	list<WorkArea> GetWorkAreaListByFields1(1:string field, 2:string value),
	list<WorkArea> GetWorkAreaListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),

	//WorkSurf 类型的CRUD操作
	i32 AddWorkSurf(1:WorkSurf work_surf),
	bool DeleteWorkSurf(1:i32 id),
	bool UpdateWorkSurf(1:WorkSurf work_surf),
	WorkSurf GetWorkSurfById(1:i32 id),
	WorkSurf GetWorkSurfByForeignKey(1:string fkey, 2:i32 id),
	list<WorkSurf> GetWorkSurfList(),
	list<i32> GetWorkSurfIds(),
	list<string> GetWorkSurfNames(),
	void AddMoreWorkSurf(1:list<WorkSurf> objs),
	void DeleteMoreWorkSurf(1:list<i32> obj_ids),
	WorkSurf GetWorkSurfByFields(1:map<string, string> fields),
	WorkSurf GetWorkSurfByFields1(1:string field, 2:string value),
	WorkSurf GetWorkSurfByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),
	list<WorkSurf> GetWorkSurfListByFields(1:map<string, string> fields),
	list<WorkSurf> GetWorkSurfListByFields1(1:string field, 2:string value),
	list<WorkSurf> GetWorkSurfListByFields2(1:string field1, 2:string value1, 3:string field2, 4:string value2),


//}


//service DaoService {
	//初始化示范矿区(虚拟的矿井和煤层)
	void InitSampleRegion(),
	//查询已登录用户的id
	i32 GetOnlineAccountId(),
	//获取已登录用户的矿井数据
	Mine GetOnlineMine(),
	//验证用户名和密码
	i32 VerifyMineAccount(1:string username, 2:string pwd),
	//查询基地所有的矿区
	list<string> GetMineRegionsOfBase(1:string baseName),
	//根据矿区反查基地
	string GetBaseByRegion(1:string regionName),
	//查询示范矿区的虚拟矿井
	Mine GetSampleMineOfRegion(1:string regionName),
	//查询示范矿区的虚拟煤层
	Coal GetSampleCoalOfRegion(1:string regionName),
	//查询矿井所有的煤层名称
	list<string> GetCoalNamesOfMine(1:i32 mine_id),
	//查询矿井所有的煤层id
	list<i32> GetCoalIdsOfMine(1:i32 mine_id),
	//查询矿井所有的采区
	list<WorkArea> GetWorkAreasOfMine(1:i32 mine_id),
	//查询矿井所有的工作面
	list<WorkSurf> GetWorkSurfsOfMine(1:i32 mine_id),
	//查询矿井所有的掘进面
	list<DrillingSurf> GetDrillingSurfsOfMine(1:i32 mine_id),
	list<i32> GetWorkAreaIdsOfMine(1:i32 mine_id),
	list<i32> GetWorkSurfIdsOfMine(1:i32 mine_id),
	list<i32> GetDrillingSurfIdsOfMine(1:i32 mine_id),

	//抽采难易程度评价
	i32 DifficultEval(1:Coal coal),
	string DifficultEvalString(1:Coal coal),
	//可采煤层瓦斯涌出量计算W1
	double MineGasReservesW1(1:i32 mine_id),
	//不可采煤层瓦斯涌出量计算W2
	double MineGasReservesW2(1:i32 mine_id),
	//计算采区的瓦斯涌出量
	double WorkAreaGasFlow(1:WorkArea work_area, 2:double K1),
	//计算矿井的瓦斯涌出量
	double MineGasFlow(1:Mine mine),
	//工作面开采层瓦斯涌出量
	double WorkSurfGasFlow1(1:Coal coal, 2:WorkArea work_area, 3:WorkSurf work_surf),
	//工作面邻近层瓦斯涌出量
	double WorkSurfGasFlow2(1:Coal coal, 2:WorkArea work_area, 3:WorkSurf work_surf),
	//掘进面瓦斯涌出量
	DrillingSurfGasFlowResult DrillingSurfGasFlow(1:Coal coal, 2:DrillingSurf drilling_surf, 3:Tunnel tunnel),
//}


}