/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cbm_CONSTANTS_H
#define cbm_CONSTANTS_H

#include "cbm_types.h"

namespace cbm {

class cbmConstants {
 public:
  cbmConstants();

};

extern const cbmConstants g_cbm_constants;

} // namespace

#endif
