// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "CbmService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::cbm;

class CbmServiceHandler : virtual public CbmServiceIf {
 public:
  CbmServiceHandler() {
    // Your initialization goes here
  }

  int32_t VerifyMineAccount(const std::string& username, const std::string& pwd) {
    // Your implementation goes here
    printf("VerifyMineAccount\n");
  }

  void GetAllMineBases(std::vector<std::string> & _return) {
    // Your implementation goes here
    printf("GetAllMineBases\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<CbmServiceHandler> handler(new CbmServiceHandler());
  shared_ptr<TProcessor> processor(new CbmServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

