/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ctrl_CONSTANTS_H
#define ctrl_CONSTANTS_H

#include "ctrl_types.h"

namespace cbm {

class ctrlConstants {
 public:
  ctrlConstants();

};

extern const ctrlConstants g_ctrl_constants;

} // namespace

#endif
