/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "entity_constants.h"

namespace cbm {

const entityConstants g_entity_constants;

entityConstants::entityConstants() {
}

} // namespace

