/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef msis_CONSTANTS_H
#define msis_CONSTANTS_H

#include "msis_types.h"

namespace msis {

class msisConstants {
 public:
  msisConstants();

};

extern const msisConstants g_msis_constants;

} // namespace

#endif
