/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "stdafx.h"
#include "msis_constants.h"

namespace msis {

const msisConstants g_msis_constants;

msisConstants::msisConstants() {
}

} // namespace

