/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ServerControl_H
#define ServerControl_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "ctrl_types.h"

namespace cbm {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ServerControlIf {
 public:
  virtual ~ServerControlIf() {}
  virtual void shutdown() = 0;
};

class ServerControlIfFactory {
 public:
  typedef ServerControlIf Handler;

  virtual ~ServerControlIfFactory() {}

  virtual ServerControlIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ServerControlIf* /* handler */) = 0;
};

class ServerControlIfSingletonFactory : virtual public ServerControlIfFactory {
 public:
  ServerControlIfSingletonFactory(const boost::shared_ptr<ServerControlIf>& iface) : iface_(iface) {}
  virtual ~ServerControlIfSingletonFactory() {}

  virtual ServerControlIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ServerControlIf* /* handler */) {}

 protected:
  boost::shared_ptr<ServerControlIf> iface_;
};

class ServerControlNull : virtual public ServerControlIf {
 public:
  virtual ~ServerControlNull() {}
  void shutdown() {
    return;
  }
};


class ServerControl_shutdown_args {
 public:

  ServerControl_shutdown_args(const ServerControl_shutdown_args&);
  ServerControl_shutdown_args& operator=(const ServerControl_shutdown_args&);
  ServerControl_shutdown_args() {
  }

  virtual ~ServerControl_shutdown_args() throw();

  bool operator == (const ServerControl_shutdown_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ServerControl_shutdown_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServerControl_shutdown_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ServerControl_shutdown_pargs {
 public:


  virtual ~ServerControl_shutdown_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ServerControl_shutdown_result {
 public:

  ServerControl_shutdown_result(const ServerControl_shutdown_result&);
  ServerControl_shutdown_result& operator=(const ServerControl_shutdown_result&);
  ServerControl_shutdown_result() {
  }

  virtual ~ServerControl_shutdown_result() throw();

  bool operator == (const ServerControl_shutdown_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ServerControl_shutdown_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServerControl_shutdown_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ServerControl_shutdown_presult {
 public:


  virtual ~ServerControl_shutdown_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ServerControlClient : virtual public ServerControlIf {
 public:
  ServerControlClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ServerControlClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void shutdown();
  void send_shutdown();
  void recv_shutdown();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ServerControlProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ServerControlIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ServerControlProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_shutdown(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ServerControlProcessor(boost::shared_ptr<ServerControlIf> iface) :
    iface_(iface) {
    processMap_["shutdown"] = &ServerControlProcessor::process_shutdown;
  }

  virtual ~ServerControlProcessor() {}
};

class ServerControlProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ServerControlProcessorFactory(const ::boost::shared_ptr< ServerControlIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ServerControlIfFactory > handlerFactory_;
};

class ServerControlMultiface : virtual public ServerControlIf {
 public:
  ServerControlMultiface(std::vector<boost::shared_ptr<ServerControlIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ServerControlMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ServerControlIf> > ifaces_;
  ServerControlMultiface() {}
  void add(boost::shared_ptr<ServerControlIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void shutdown() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->shutdown();
    }
    ifaces_[i]->shutdown();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ServerControlConcurrentClient : virtual public ServerControlIf {
 public:
  ServerControlConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ServerControlConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void shutdown();
  int32_t send_shutdown();
  void recv_shutdown(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
