# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\drilling_radius_dlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_drilling_radius_dlg(object):
    def setupUi(self, drilling_radius_dlg):
        drilling_radius_dlg.setObjectName(_fromUtf8("drilling_radius_dlg"))
        drilling_radius_dlg.resize(335, 485)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cbm.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        drilling_radius_dlg.setWindowIcon(icon)
        self.label = QtGui.QLabel(drilling_radius_dlg)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.coal = QtGui.QComboBox(drilling_radius_dlg)
        self.coal.setGeometry(QtCore.QRect(70, 10, 111, 22))
        self.coal.setObjectName(_fromUtf8("coal"))
        self.groupBox = QtGui.QGroupBox(drilling_radius_dlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 311, 231))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.QSum = QtGui.QLineEdit(self.groupBox)
        self.QSum.setGeometry(QtCore.QRect(220, 200, 51, 20))
        self.QSum.setObjectName(_fromUtf8("QSum"))
        self.R = QtGui.QLineEdit(self.groupBox)
        self.R.setGeometry(QtCore.QRect(80, 20, 51, 20))
        self.R.setObjectName(_fromUtf8("R"))
        self.K1 = QtGui.QLineEdit(self.groupBox)
        self.K1.setGeometry(QtCore.QRect(250, 50, 41, 20))
        self.K1.setObjectName(_fromUtf8("K1"))
        self.mineName_label_14 = QtGui.QLabel(self.groupBox)
        self.mineName_label_14.setGeometry(QtCore.QRect(20, 110, 131, 21))
        self.mineName_label_14.setObjectName(_fromUtf8("mineName_label_14"))
        self.t = QtGui.QLineEdit(self.groupBox)
        self.t.setGeometry(QtCore.QRect(130, 170, 51, 20))
        self.t.setObjectName(_fromUtf8("t"))
        self.mineName_label_9 = QtGui.QLabel(self.groupBox)
        self.mineName_label_9.setGeometry(QtCore.QRect(20, 50, 231, 21))
        self.mineName_label_9.setObjectName(_fromUtf8("mineName_label_9"))
        self.mineName_label_8 = QtGui.QLabel(self.groupBox)
        self.mineName_label_8.setGeometry(QtCore.QRect(170, 20, 71, 21))
        self.mineName_label_8.setObjectName(_fromUtf8("mineName_label_8"))
        self.L = QtGui.QLineEdit(self.groupBox)
        self.L.setGeometry(QtCore.QRect(240, 20, 51, 20))
        self.L.setObjectName(_fromUtf8("L"))
        self.mineName_label_11 = QtGui.QLabel(self.groupBox)
        self.mineName_label_11.setGeometry(QtCore.QRect(20, 140, 161, 21))
        self.mineName_label_11.setObjectName(_fromUtf8("mineName_label_11"))
        self.rho = QtGui.QLineEdit(self.groupBox)
        self.rho.setGeometry(QtCore.QRect(160, 80, 51, 20))
        self.rho.setObjectName(_fromUtf8("rho"))
        self.mineName_label_7 = QtGui.QLabel(self.groupBox)
        self.mineName_label_7.setGeometry(QtCore.QRect(20, 20, 61, 21))
        self.mineName_label_7.setObjectName(_fromUtf8("mineName_label_7"))
        self.q0 = QtGui.QLineEdit(self.groupBox)
        self.q0.setGeometry(QtCore.QRect(160, 110, 51, 20))
        self.q0.setObjectName(_fromUtf8("q0"))
        self.mineName_label_12 = QtGui.QLabel(self.groupBox)
        self.mineName_label_12.setGeometry(QtCore.QRect(20, 170, 111, 21))
        self.mineName_label_12.setObjectName(_fromUtf8("mineName_label_12"))
        self.mineName_label_13 = QtGui.QLabel(self.groupBox)
        self.mineName_label_13.setGeometry(QtCore.QRect(20, 200, 201, 21))
        self.mineName_label_13.setObjectName(_fromUtf8("mineName_label_13"))
        self.mineName_label_10 = QtGui.QLabel(self.groupBox)
        self.mineName_label_10.setGeometry(QtCore.QRect(20, 80, 131, 21))
        self.mineName_label_10.setObjectName(_fromUtf8("mineName_label_10"))
        self.a = QtGui.QLineEdit(self.groupBox)
        self.a.setGeometry(QtCore.QRect(180, 140, 61, 20))
        self.a.setObjectName(_fromUtf8("a"))
        self.groupBox_2 = QtGui.QGroupBox(drilling_radius_dlg)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 311, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gas_W0 = QtGui.QLineEdit(self.groupBox_2)
        self.gas_W0.setGeometry(QtCore.QRect(130, 20, 51, 20))
        self.gas_W0.setObjectName(_fromUtf8("gas_W0"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 111, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.hw = QtGui.QLineEdit(self.groupBox_2)
        self.hw.setGeometry(QtCore.QRect(250, 20, 41, 20))
        self.hw.setObjectName(_fromUtf8("hw"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(210, 20, 31, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.groupBox_3 = QtGui.QGroupBox(drilling_radius_dlg)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 360, 311, 80))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gas_Wc3 = QtGui.QLineEdit(self.groupBox_3)
        self.gas_Wc3.setGeometry(QtCore.QRect(160, 50, 51, 20))
        self.gas_Wc3.setObjectName(_fromUtf8("gas_Wc3"))
        self.eta = QtGui.QLineEdit(self.groupBox_3)
        self.eta.setGeometry(QtCore.QRect(240, 20, 61, 20))
        self.eta.setObjectName(_fromUtf8("eta"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(190, 20, 51, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 151, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.Qm = QtGui.QLineEdit(self.groupBox_3)
        self.Qm.setGeometry(QtCore.QRect(110, 20, 61, 20))
        self.Qm.setObjectName(_fromUtf8("Qm"))
        self.save = QtGui.QPushButton(drilling_radius_dlg)
        self.save.setGeometry(QtCore.QRect(190, 450, 81, 31))
        self.save.setObjectName(_fromUtf8("save"))
        self.cacl = QtGui.QPushButton(drilling_radius_dlg)
        self.cacl.setGeometry(QtCore.QRect(60, 450, 81, 31))
        self.cacl.setObjectName(_fromUtf8("cacl"))

        self.retranslateUi(drilling_radius_dlg)
        QtCore.QMetaObject.connectSlotsByName(drilling_radius_dlg)
        drilling_radius_dlg.setTabOrder(self.coal, self.R)
        drilling_radius_dlg.setTabOrder(self.R, self.L)
        drilling_radius_dlg.setTabOrder(self.L, self.K1)
        drilling_radius_dlg.setTabOrder(self.K1, self.rho)
        drilling_radius_dlg.setTabOrder(self.rho, self.q0)
        drilling_radius_dlg.setTabOrder(self.q0, self.a)
        drilling_radius_dlg.setTabOrder(self.a, self.t)
        drilling_radius_dlg.setTabOrder(self.t, self.QSum)
        drilling_radius_dlg.setTabOrder(self.QSum, self.gas_W0)
        drilling_radius_dlg.setTabOrder(self.gas_W0, self.hw)
        drilling_radius_dlg.setTabOrder(self.hw, self.Qm)
        drilling_radius_dlg.setTabOrder(self.Qm, self.eta)
        drilling_radius_dlg.setTabOrder(self.eta, self.gas_Wc3)
        drilling_radius_dlg.setTabOrder(self.gas_Wc3, self.cacl)
        drilling_radius_dlg.setTabOrder(self.cacl, self.save)

    def retranslateUi(self, drilling_radius_dlg):
        drilling_radius_dlg.setWindowTitle(_translate("drilling_radius_dlg", "瓦斯抽采半径计算", None))
        self.label.setText(_translate("drilling_radius_dlg", "煤层列表", None))
        self.groupBox.setTitle(_translate("drilling_radius_dlg", ">>钻孔抽采参数", None))
        self.mineName_label_14.setText(_translate("drilling_radius_dlg", "钻孔初始瓦斯抽采流量q0", None))
        self.mineName_label_9.setText(_translate("drilling_radius_dlg", "抽采负压后，较自然瓦斯涌出量的增大值K1", None))
        self.mineName_label_8.setText(_translate("drilling_radius_dlg", "抽采孔孔长L", None))
        self.mineName_label_11.setText(_translate("drilling_radius_dlg", "钻孔瓦斯抽采流量衰减系数α", None))
        self.mineName_label_7.setText(_translate("drilling_radius_dlg", "抽采半径R", None))
        self.mineName_label_12.setText(_translate("drilling_radius_dlg", "钻孔抽采瓦斯时间t", None))
        self.mineName_label_13.setText(_translate("drilling_radius_dlg", "抽采时间内，钻孔的累计瓦斯抽采量Q", None))
        self.mineName_label_10.setText(_translate("drilling_radius_dlg", "抽采范围内煤的视密度ρ", None))
        self.groupBox_2.setTitle(_translate("drilling_radius_dlg", ">>煤层参数", None))
        self.label_10.setText(_translate("drilling_radius_dlg", "煤层原始瓦斯含量W", None))
        self.label_11.setText(_translate("drilling_radius_dlg", "采高h", None))
        self.groupBox_3.setTitle(_translate("drilling_radius_dlg", ">>计算结果", None))
        self.label_12.setText(_translate("drilling_radius_dlg", "吨煤瓦斯抽采量Qm", None))
        self.label_13.setText(_translate("drilling_radius_dlg", "抽采率η", None))
        self.label_14.setText(_translate("drilling_radius_dlg", "抽采后煤层残存瓦斯含量Wc", None))
        self.save.setText(_translate("drilling_radius_dlg", "保 存", None))
        self.cacl.setText(_translate("drilling_radius_dlg", "计 算", None))

import usecad_rc
